### ISSUE TITLE
Is the path in the exe.config file correct?

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#10]
Linux is case sensitive. I see that (on Windows) the **B**in sub-directory from the <HS root> directory is capitalized whereas the path info recommended for .config files is all lower case.
I believe this is an issue for Linux installs but if I'm wrong, just toss this issues.

**Comment by spudwebb** [comment]
I think it was already like that in HS3:
Bin on windows
bin on Linux

so lower case bin in .config file should work on both systems

**Comment by dcorsus** [comment]
you would be right, Windows ignores the uppercase "B" and config is in line with Linux definitions.
Thanks,
Dirk

**Comment by jldubz** [comment]
@dcorsus is this an issue that needs to be fixed in code?  It sounds like we have identified that there is no issue, but I want to check with you to be sure.

**Comment by dcorsus** [comment]
No code fix needed, it might be wise to fix the updater script, but as Spud rightfully stated, it just works because Windows doesn't care
