### ISSUE TITLE
Cannot retrieve category ID

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#101]
**Environment and System Config**
- OS: Windows
- Language: VB
- IDE: VS2019
- HomeSeer Version: v4.0.10.0]
- PluginSDK Version: [v1.2.0.0]

**Describe the issue**
Thanks for adding the Category functions. However, there is no easy way to get the ID of the category, which is required for most of the related functions.  I believe there is an issue with the GetAllCategories() return values. It returns the name of the category for both Key and Value. I was expecting the ID for Key, and Name for Value.

**Steps to Reproduce**
Dim test = hs.GetAllCategories().First
result: {[Appliances, Appliances]}

**Expected behavior**
I was expecting the ID for Key, and Name for Value.

**Comment by stefxx** [comment]
Also, a new function "GetCategoryByName(Name as String) as String" returning the GUID would be a useful additional.

**Comment by stefxx** [comment]
Also, shouldn't "CreateCategory("name", "image")" return the GUID? Currently it returns en empty string.

**Comment by rjhdakota** [comment]
> Also, shouldn't "CreateCategory("name", "image")" return the GUID? Currently it returns an empty string.

Yes, I have put in a fix for build 4.1

**Comment by stefxx** [comment]
Works in 4.1.0.0, so I guess we can close this. Thanks!
