### ISSUE TITLE
Querystring parameters on not cleared on new page or refresh

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#103]
HS4 Version 4.1.0.0

Issue existed in Alpha and reintroduced between 4.0.9.0 and 4.1.0.0

mcsMQTT and mcsShelly use  querystrings to pass information between html pages.  In the HTML the following code exists on a page that has been registered with HS4.  (less-than and greater-than brackets removed to avert potential posting issue of HTML.

    div class="tab-content" container
    		{{
			parms = ['MQTT', '']
			udn=queries['Edit']
			if (udn != empty) && (udn != '')
			  parms = ['Edit', udn]
			end
		}}
        {{plugin_function 'mcsMQTT' 'PagePreLoad' parms}}
    /div

When a hyperlink is executed from the html page such as /mcsMQTT/MQTT.html?Edit=1234 the proper response is obtained with the Edit querystring parameter delivered to the plugin function.  If  /mcsMQTT/MQTT.html is again used in the URL either from the HS plugin menu or manually via same or new browser window the querystring parameter Edit=1234 continues to be returned to the plugin.  The only way to clear the querysting is to restart HS4.

What is expected is that the querystring parameter persists only for the one page being delivered.  A new URL should clear the querystring (i.e. clear the queries collection return data).

**Comment by spudwebb** [comment]
I tried to replicate this problem with 4.1.9.0 but I couldn't.
Is it still a problem for you?

**Comment by mcsSolutions** [comment]
It is not an issue with 4.1.9.0.
