### ISSUE TITLE
ValuesRangSlider generates 2 events when changed. Same issue for HS3 or HS4 plugin

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#11]
Running sdk .04 and HS4 v.20

the PI receives 2 back to back events when I adjust the range slider in the devices view. First with correct new value followed immediately by an event with new value = 0

9/25/2019 1:56:05 PM   Sonos 
  TreatSetIOEx called for Zone = Deck with Ref = 5081, Index 1, controlFlag = False, ControlString, ControlType = ValuesRangeSlider, ControlValue = 15, Label = Volume (value)% 
 
9/25/2019 1:56:05 PM 
  Device Control 
  Device: Sonos Deck Volume to Volume (value)% (0) by/from: CAPI Control Handler 
 
9/25/2019 1:56:05 PM 
  Sonos 
  SetIOEx called for Ref = 5081, Index 1, controlFlag = False, ControlString, ControlType = ValuesRangeSlider, ControlValue = 15, Label = Volume (value)% 
 
9/25/2019 1:56:05 PM 
  Device Control 
  Device: Sonos Deck Volume to Volume (value)% (15) by/from: CAPI Control Handler

**Comment by jldubz** [comment]
This might be an issue with the HS4 UI; in which case, this should be posted to the sub forum and addressed by Rich.  More investigation is needed to figure this out though.

This happens when you are controlling something through the HS4 UI correct?

**Comment by dcorsus** [comment]
For completeness, here is what I found and email Rich about. Could be of learning value for other developers to understand some of the code & functions

It really is an event when you click on the slider to move the slider. Not sure anyone would use or need an onclick event for a slider. Unfortunately, it shows up in my PI as an event with (new) value = 0.
Next is to go figure out why there is no dynamic updates, albeit I see the ajax functions doing something and design the best way to navigate content.
Dirk

From: Richard J Helmke <rjh@homeseer.com> 
Sent: Saturday, October 5, 2019 5:13 AM
To: Dirk Corsus <dirk@famcorsus.com>
Subject: Re: Hopefully easy question about html

Looks like there may be 2 handlers for input, I will fix.

Rich

On Sat, Oct 5, 2019 at 1:43 AM Dirk Corsus <dirk@famcorsus.com> wrote:
Ah the problem is here
 
$(document).on('click','button,a,input,i', {} ,function(e){ 
 
If I remove the a,input and make it 
 
$(document).on('click','button, i', {} ,function(e){ 
 
No more dual events and my buttons still work, not sure what ‘a’ and ‘input’ are ….
 
 
 
 
From: Dirk Corsus <dirk@famcorsus.com> 
Sent: Friday, October 4, 2019 10:35 PM
To: 'Richard J Helmke' <rjh@homeseer.com>
Subject: RE: Hopefully easy question about html
 
Making good progress here 😊 When the volume slider is changed we get 2 events.
 
One is generated here and is correct:
 
    function initsliders() {
        $('.custom-range').add().off();
        $('.custom-range').on('change', function(e){    
            var data;
            $(this.attributes).each(function() {
                var parts = this.nodeName+"="+this.nodeValue;
                if(data==null) {
                    data = parts;
                }
                else {
                    data = data+"&"+parts;
                }            
            });
            data = data+"&new_value="+$(this).val();
            alert('Value Changed:'+data);
            AjaxPost(data,"devices.html");
        });
    }
Value Changed:type=range&class=custom-range flex-fill&id=justvolume&ref=3567&ccindex=0&action=control&min=0&max=100&step=1&value=0&new_value=11
 
 
 
The other fires here and is not correct. Not sure why this fires
 
    $(document).on('click','button,a,input,i', {} ,function(e){            
        
        var data;
        $(this.attributes).each(function() {
            var parts = this.nodeName+"="+this.nodeValue;
            if(data==null) {
                data = parts;
            }
            else {
                data = data+"&"+parts;
            }
        });
 
        var fdata = $('#searchform').serialize();
        if(fdata != null) {
            data = data+"&"+fdata
        }  
        alert('Value Changed2:'+data);
        AjaxPost(data,"devices.html");
    });  
Value Changed2:type=range&class=custom-range flex-fill&id=justvolume&ref=3567&ccindex=0&action=control&min=0&max=100&step=1&value=0&search_data=

**Comment by rjhdakota** [comment]
Slider event issue is fixed in HS4 build 4.0.0.25.
