### ISSUE TITLE
Range suffix  value not used in the device status text

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#110]
When I create a range for a control and add a suffix to the range (a % sign for example), this is never used in the device display.
Code used creating a range:

   ```
 Dim Range As New Devices.ValueRange(1, 100)
    Range.Suffix = "%"
    Range.Min = 1
    Range.Max = 100
    Range.DecimalPlaces = 0
    Control = New Devices.Controls.StatusControl(Devices.Controls.EControlType.ValueRangeSlider) With {
                .ControlUse = Devices.Controls.EControlUse.Dim,
                .Location = location,
                .TargetRange = Range,
                .Label = "Dim",
                .IsRange = True,
                .ControlType = Devices.Controls.EControlType.ValueRangeSlider
                 }
     HS.AddStatusControlToFeature(ref, Control)

```
Am I missing something here, or is this a bug in the PlusinSDK?

Wim

**Comment by spudwebb** [comment]
not 100% sure this is the problem but did you try to add the same range with the suffix to a StatusGraphic? 
This is how I do it and it works.

**Comment by wvuyk** [comment]
Will try this, it will probably work. But this is not found in any documentation that this setting is only used in the StatusGraphic. One would expect the StatusControl (offering the same parameters) would also show the sign - or not offer it if it is not being used there...
