### ISSUE TITLE
AssociatedDevices list update is not committed

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#112]
HS4 4.1.3.0 Windows (untested in Linux)

The objective is move an existing feature to a different device.  No provisions appear to exist in the SDK for this, but based upon HS3 SDK the AssociatedDevices property contains the root/child relationship pointers.  The AssociatedDevices pointer list can be updated as viewed in Visual Studio, but after using UpdatePropertyByRef the updated list is not retained in the feature or devices.  Example code below.

Dim aFeatureList As Generic.HashSet(Of Integer) = hs.GetPropertyByRef(iFeatureRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices)
Dim aDeviceList As Generic.HashSet(Of Integer) = hs.GetPropertyByRef(iDeviceRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices)
Dim aOtherDeviceList As Generic.HashSet(Of Integer) = hs.GetPropertyByRef(iOtherDeviceRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices)

aFeatureList.Remove(iDeviceRef)
aFeatureList.Add(iOtherDeviceRef)
hs.UpdatePropertyByRef(iFeatureRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices, aFeatureList)

aDeviceList.Remove(iDeviceRef)
hs.UpdatePropertyByRef(iDeviceRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices, aDeviceList)

aOtherDeviceList.Add(iFeatureRef)
hs.UpdatePropertyByRef(iOtherDeviceRef, HomeSeer.PluginSdk.Devices.EProperty.AssociatedDevices, aOtherDeviceList)

**Comment by stefxx** [comment]
I have the same issue. It does not seem possible to "move" a feature (child device) to another device (root device). I really need this in my plugins. Thanks!

**Comment by mcsSolutions** [comment]
In 4.1.7.0 I am able to create a new HS4 device and then manipulate a HS3-created child device  so that the AssociatedDevices property can be altered so that the HS3 child device becomes a feature of the new HS4 device.  

I have not tried to reproduce the reported issue since 4.1.3.0

**Comment by spudwebb** [comment]
I have reproduced this problem and identified its cause.  It is now tracked as HS-1075

**Comment by spudwebb** [comment]
Fixed in HS 4.1.11.0
