### ISSUE TITLE
A status graphic with that value set already exists when getting a device.

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#114]
**Environment and System Config**
- OS: [Windows, Linux, Mac, etc]
- Language: [VB or C#]
- IDE: [VS2017, VS2019, JetBrains Rider, etc]
- HomeSeer Version: [v4.1.4.0]
- PluginSDK Version: [v1.2.0]

**Describe the issue**

On running the following code I get the error "A status graphic with that value set already exists when getting a device." but I am not trying to do anything with status graphics. I believe the error is to do with getting a device ref with hs.GetFeatureByRef(Ref) and should read "You can not get a device with hs.GetFeatureByRef." I have spent many hours looking at device status graphics trying to find this problem that turns out to be a wrongly labelled error in HS.
Ref 6093 is a device and not a feature

        Dim Feat As HomeSeer.PluginSdk.Devices.HsFeature
         Feat = hs.GetFeatureByRef(6093)

HomeSeer	Error	Error while getting feature 6093 : A status graphic with that value set already exists

**Expected behavior**
I would expect an error "You can not get a device with hs.GetFeatureByRef." 

-----

**Comment by spudwebb** [comment]
@Enigmatheatre  Is it still a problem with HS 4.1.15.0 and PluginSdk 1.2.4? We have recently fixed a couple of bugs related to this error. ("A status graphic with that value set already exists")

and yes right now I believe HS let you load a device with GetFeatureByRef, and a feature with GetDeviceByRef, but you shouldn't do it.

**Comment by alexbk66** [comment]
> and yes right now I believe HS let you load a device with GetFeatureByRef, and a feature with GetDeviceByRef, but you shouldn't do it.

I don't get why there's so much separation in SDK for HsDevice vs HsFeature?  Why don't just GetAbstractHsDeviceByRef?

**Comment by spudwebb** [comment]
@Enigmatheatre , I'm closing this, if it is still a problem with PluginSdk 1.3.0 and HS 4.1.17.0, please reopen.
