### ISSUE TITLE
HSDevice.Features returns a blank list.

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#115]
HomeSeer Version: [V4.1.4.0]
PluginSDK Version: [v1.2.0]

**Describe the issue**
Every time I use HSDevice.Features it returns a blank list. I am sure this was working before as I have it code in my plugin using this but now it returns a blank list with all devices.

 Dim Dev As HomeSeer.PluginSdk.Devices.HsDevice

            Dev = hs.GetDeviceWithFeaturesByRef(6093))

            Console.WriteLine("Main device no:" & Dev.Ref)

            Dim FeatList As List(Of HsFeature) = Dev.Features()

            Console.WriteLine("No of features = " & FeatList.Count)

**Expected behavior**
To return a list of all features attached to the device.

-----

**Comment by spudwebb** [comment]
I have fixed a few issues related to this recently. Could you send me your devices.json and the ref of the device you have trouble with so that I can check if it is the same problem?

**Comment by Enigmatheatre** [comment]
I have run tests on HS4.1.10.0 with SDKV1.2.1 and all is working fine now.

Thanks.
