### ISSUE TITLE
hs.device property not working

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#116]
**Environment and System Config**
- OS: windows
- Language: [VB 
- IDE: vs2019
- HomeSeer Version: v4..1.4.0
- PluginSDK Version:v1.2.0.0

dv.address is not saved properly to the device. i use this as my primary key to find my devices in the database.

**Priority**
Highest - level 5
5. Blocking

**Comment by spudwebb** [comment]
Can you show the code you use  to save this property?

**Comment by mnsandler** [comment]
very basic assignment, but the value i set doesn't persist. the SDK shows a put/get for the Address property
dv.Address = DeviceID

**Comment by spudwebb** [comment]
any change you make to a property of AbstractHsDevice is local to your plugin, you need to call IHsController.UpdatePropertyByRef() so that HS saves it.

`_hs.UpdatePropertyByRef(dvRef, EProperty.Address, "deviceAddress" ); `

**Comment by mnsandler** [comment]
I am able to set the following property without issue: it sets and save!
	dv.Interface = IFACE_NAME

**why can't the .Address property work the same?**

UpdatePropertyByRef isn't documented in the API (https://homeseer.github.io/Plugin-SDK-Docs/api/index.html)

how do we know when we can do a straight assignment vs using the UpdatePropertyByRef  method; kind of confusing

**Comment by spudwebb** [comment]
a straight assignment never saves the property in HS database. If you don't believe me just look at the open source code:

```csharp
        /// <summary>
        /// The ID of the interface that is responsible for processing interactions with this device/feature
        /// </summary>
        public string Interface {
            get {
                if (Changes.ContainsKey(EProperty.Interface)) {
                    return (string) Changes[EProperty.Interface];
                }

                return _interface;
            }
            set {
                if (value == _interface) {
                    Changes.Remove(EProperty.Interface);
                    return;
                }
                if (Changes.ContainsKey(EProperty.Interface)) {
                    Changes[EProperty.Interface] = value;
                }
                else {
                    Changes.Add(EProperty.Interface, value);
                }
                
                if (_cacheChanges) {
                    return;
                }
                _interface = value ?? "";
            }
        }
```

the set just change the _interface local member and add the change to the Changes local dictionary, it never calls HS4 to set or save the property.

you need to call either UpdatePropertyByRef if you want to save a single property or  UpdateDeviceByRef/UpdateFeatureByRef if you want to save all the changes you made to your local HsDevice or HsFeature

not sure why the search function do not find them but they are in the docs:

https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.IHsController.html#HomeSeer_PluginSdk_IHsController_UpdatePropertyByRef_System_Int32_HomeSeer_PluginSdk_Devices_EProperty_System_Object_
https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.IHsController.html#HomeSeer_PluginSdk_IHsController_UpdateDeviceByRef_System_Int32_System_Collections_Generic_Dictionary_HomeSeer_PluginSdk_Devices_EProperty_System_Object__
https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.IHsController.html#HomeSeer_PluginSdk_IHsController_UpdateFeatureByRef_System_Int32_System_Collections_Generic_Dictionary_HomeSeer_PluginSdk_Devices_EProperty_System_Object__
