### ISSUE TITLE
need slider 0 to 100, and On/Off for values 0/100

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#117]
I want to add a slider to a Feature with values from 0 to 100. 0 is Off and 100 is On. I also need add an On button (value 100) and Off button (value 0)

HS3 didn't support this very well, or at least not in the beginning.

How can I do this in HS4?

i can add the on and off values, but when i add the range 0 to 100, it breaks the Off value. strangely the On still seems work work.

**Comment by mnsandler** [comment]
im getting close to what i want however, THE PROBLEM: the dim labels are not being honored/used on the UI.  My preference would be unique dim levels between 1 and 99 but i will take steps of 10 if that works.

![image](https://user-images.githubusercontent.com/67801043/91051016-7f103580-e5ed-11ea-9dea-cdf00c5ff55c.png)

![image](https://user-images.githubusercontent.com/67801043/91051044-8a636100-e5ed-11ea-93f9-be15aab67813.png)

**I'm using the following code to generate the slider**

```
				Dim Control As StatusControl
				Dim Graphic As StatusGraphic

				Control = New StatusControl(EControlType.ValueRangeSlider)
				Control.IsRange = True

				Dim DimmerRange As New ValueRange(0, 100)
				'DimmerRange.Prefix = "Dim "
				'DimmerRange.Suffix = "%"

				Control.TargetRange = DimmerRange
				Control.ControlUse = EControlUse.Dim

				Control.Location.Row = 1 ' putting the slider on row 2 below On/Off doesn't look good
				Control.Location.Column = 3

				hs4.AddStatusControlToFeature(Ref, Control)

				REM Add graphics
				For Index = 0 To 90 Step 10
					Graphic = New StatusGraphic("/images/HomeSeer/status/dim-" & Index.ToString("00") & ".gif", Math.Max(1, Index), Index + 9)
					Graphic.Label = "Dim " + Math.Max(1, Index).ToString + "%"
					hs4.AddStatusGraphicToFeature(Ref, Graphic)
				Next
```

**Comment by spudwebb** [comment]
you can use the StatusGraphic constructor that takes a ValueRange as last parameter, so that prefix and suffix set in that ValueRange will be honored

```csharp
            ValueRange range = new ValueRange(1, 100);
            range.DecimalPlaces = 0;
            range.Suffix = "%";
            StatusControl statusControl = new StatusControl(EControlType.ValueRangeSlider);
            statusControl.TargetRange = range;
            statusControl.ControlUse = EControlUse.Dim;
            _hs.AddStatusControlToFeature(featRef, statusControl);

            StatusGraphic statusGraphic = new StatusGraphic(BridgeController.ImagesStatusDir + "luminance-100.png", range);
            _hs.AddStatusGraphicToFeature(featRef, statusGraphic);
```

**Comment by mnsandler** [comment]
thanks for the reply. can you tell me why the Labels in my screen shot above aren't showing up on the device page?

i dont want the same label format for every number in the Range

**Comment by spudwebb** [comment]
> thanks for the reply. can you tell me why the Labels in my screen shot above aren't showing up on the device page?

I guess when the StatusGraphic is a range, HS4 just ignore the label and build the status text as "prefix + value + suffix"

> i dont want the same label format for every number in the Range

not sure I understand, can you give an example of what you want?
can't you use several ValueRange with different prefix and suffix?

**Comment by mnsandler** [comment]
in the screen shot i provided at the top, i have all the status Labels it want. however the "Dim X%" labels aren't showing on the device status. I only get the the actual status value. see the pic below, it shows "50" instead of "Dim 50%"

![image](https://user-images.githubusercontent.com/67801043/91178722-8a2d9900-e6b3-11ea-887d-db5677485df0.png)

**the problem is the hs device isn't honoring the Dim Labels i successfully set**

i can't use the the valuerange.prefix and valuerange.suffix props, because i have set the range value 0 label = Off and range value 100 = On. i dont want them to display as DIM 0% or Dim 100%

**Comment by spudwebb** [comment]
> i can't use the the valuerange.prefix and valuerange.suffix props, because i have set the range value 0 label = Off and range value 100 = On. i dont want them to display as DIM 0% or Dim 100%

did you create the StatusGraphic for 0 and 100 as ranges or as single values? If you created it as single values the associated label should display fine.

**Comment by mnsandler** [comment]
I provided the code i used to create the range, and assign the various graphics and labels.

can you give it a try and see if you get the appropriate labels to show on the device

**Comment by spudwebb** [comment]
sorry, but unless I missed something you did not provide the code that creates the StatusGraphic for Off=0 and On=100

as I said, for ranges, you need to use the prefix/suffix in the ValueRange, so change your For loop to use ValueRanges
and for on/off use signle values with labels

**Comment by mnsandler** [comment]
i converted my loop to the following and it seems to do what i expected; each value between 1 and 99 displays as Dim X%

i think we can close this ticket

I still don't understand what the StatusGraphic.label property is used for, but oh well.

```
				For Index = 0 To 90 Step 10
					DimmerRange = New ValueRange(Math.Max(1, Index), Index + 9)
					DimmerRange.Prefix = "Dim "
					DimmerRange.Suffix = "%"

					Graphic = New StatusGraphic("/images/HomeSeer/status/dim-" & Index.ToString("00") & ".gif", DimmerRange)
					hs4.AddStatusGraphicToFeature(Ref, Graphic)
				Next
```

**Comment by spudwebb** [comment]
the StatusGraphic.label is only used for single value, not ranges
