### ISSUE TITLE
HS4 with my HS3 plugin...my page refresh isn't working anymore

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#118]
My HS3 plugin UI page isn’t refreshing based on my meta tag. In hs3 I was generating my page header with the following call

HS.GetPageHeader("Insteon Plug-in Configuration", "<meta http-equiv=""refresh"" content=""3;url=/" + link + """>", "", False, False, False, False, False).Trim

The Link variable above is my plugin config page, ‘insteon’

**something is is broken in HS4 regarding the HS3.GetPageHeader**. its not processing the extra meta tag)

I need this fixed in the next hs4 update

**Comment by mnsandler** [comment]
@spudwebb , would appreciate your insight on this issue. If you aren't the right person for this, can you point me in the right direction.

**Comment by spudwebb** [comment]
I think you will have to ask @rjhdakota for this one

**Comment by rjhdakota** [comment]
Are you saying that the meta tag is not getting inserted into the page header if you view source?

**Comment by mnsandler** [comment]
yes, exactly

**Comment by mnsandler** [comment]
Guys, any update on this?

**Comment by rjhdakota** [comment]
Is there a way I can re-create this without any Insteon devices?

**Comment by mnsandler** [comment]
you would need the minimum hw of an insteon plm or hub? you can run the "display interface links" from the config page

**Comment by mnsandler** [comment]
this was fixed in HS4 4.1.7.0
