### ISSUE TITLE
Can we add SpeakToFile back to the Interface?

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#12]
One of the more important functions of the Sonos PI is to play announcements based on TTS. The PI makes use of the SpeakToFile HS3 functions to create a .wav file which subsequently gets transferred via the embedded HTTP webserver to the Sonos player.
Rich ask me to open a ticket here to better track bringing this back.
Dirk

**Comment by spudwebb** [comment]
+1
already reported internally.

**Comment by jldubz** [comment]
Working on an integrated implementation for next week's v1.0.7 release using [AbstractSpeakerClient](https://github.com/HomeSeer/Plugin-SDK/blob/master/Speech/AbstractSpeakerClient.cs)

**Comment by jldubz** [comment]
Combining this with [GitHub issue 3](https://github.com/HomeSeer/Plugin-SDK/issues/3)
