### ISSUE TITLE
GetStatusControlCountByRef returns incorrect result

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#121]
4.1.7.0 Windows

Device created by HS3 plugin with single value and range status-only VSP

In HS4 plugin the following two methods used to assess if the device has controls

Dim bControl As Boolean = (hs.GetStatusControlCountByRef(dvRef) > 0)
Dim ControlList As Generic.List(Of HomeSeer.PluginSdk.Devices.Controls.StatusControl) = hs.GetStatusControlsByRef(dvRef)
Dim bControlListCount as Boolean = (ControlList.count > 0)

bControl returns true
bControlListCount returns false

The same should be returned by either method.

**Comment by spudwebb** [comment]
Logged as HS-1072

**Comment by spudwebb** [comment]
Fixed in HS 4.1.11.0
