### ISSUE TITLE
ControlEvent Incorrectly populates Label/ControlString for TextSelectList

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#123]
HS4 4.1.8.0 Windows

A Text select list was created and the 4th item in the list selected.  A breakpoint at SetIOMulti was set to observe the ControlEvent properties.  The expected ControlValue of 3 was observed.  The ControlString was null and the Label has the value of the first item (not the 4th) in the list.  Expected Label (or ControlString) to be the text that was selected.

Public Sub SetIOMulti(colSend As List(Of Devices.Controls.ControlEvent))
  For Each oCAPI As Devices.Controls.ControlEvent In colSend
      selection = oCAPI.Label

?oCAPI
{HomeSeer.PluginSdk.Devices.Controls.ControlEvent}
    CCIndex: 0
    ControlString: ""
    ControlType: TextSelectList {3}
    ControlUse: NotSpecified {0}
    ControlValue: 3
    Label: "alloff"
    TargetRef: 5658

**Comment by spudwebb** [comment]
Fixed in HS4, the Label field will now be correctly populated.
The reference issue is HS-1059.
Thanks for reporting this bug.

**Comment by spudwebb** [comment]
Fixed in HS 4.1.10.0
