### ISSUE TITLE
Linux Tools Links have incorrect URL

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#127]
4.1.10.0 (and earlier) Windows and Linux
When any of the Linux Tools such as Shutdown Homeseer is used the URL is relative to the current page so if done from a plugin page the URL will be incorrect

For example http://192.168.0.67/mcsShelly/system.html?action=shutdown_system is the URL being requested if a mcsShelly page is currently being shown.

I suspect the issue is that the URL does not start with / to designate the HS server root.

**Comment by spudwebb** [comment]
I can reproduce this problem. I logged it as HS-1079
Thanks for reporting!

**Comment by spudwebb** [comment]
Fixed in HS 4.1.11.0
