### ISSUE TITLE
Plugin Ini File Retained Internally Within HS

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#128]
4.1.10.0 Windows, Untested in Linux

1. Plugin uses hs.SaveIniSetting to save user settings.  .ini file is created as expected in \Config folder.
2. HS is shutdown. 
3. .ini file is deleted from \Config folder.
4. HS is started.
5. All prior data in the deleted .ini file restored to .ini file on the first hs.SaveIniSetting.  Expect only the one setting to be saved and all others to no longer exist. 

If prior to step 5 a hs.ClearIniSection is used to clear part of the .ini file settings, then on the first hs.SaveIniSetting of step 5 the cleared section has been cleared in the newly created .ini file

While persistence of settings in case a file is deleted does have merit, there needs to be an API to provide means for a plugin to clear out settings of the entire file.  In some cases the Section names are user-data dependent so the plugin will not know what Sections had been previously created.

**Comment by spudwebb** [comment]
At step 3 do you mean, you manually delete the ini file?
For each plugin.ini file, HS creates a backup file plugin.ini.bak, if you delete plugin.ini manually HS will recreate it from plugin.ini.bak next time it needs to access it. So if you want to delete completely the user settings you need to delete both plugin.ini and plugin.ini.bak. Another way is to edit plugin.ini and delete all its content.

So, what you want is a hs.DeleteIni method which would delete both the .ini and .ini.bak files?

**Comment by mcsSolutions** [comment]
No need for additional method knowing that deleting the .bak file will remove the settings.  This can be closed.
