### ISSUE TITLE
PluginFunction should be marked virtual

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#130]
1. Can AbstractPlugin.PluginFunction be marked virtual? I override the function in my derived HSPI to redirect calls to the controller class:
```
public override object PluginFunction(string functionName, object[] parameters)
{
    return controller.PluginFunction(functionName, parameters);
}
```
2. Also, I think GetMethod should take the array of types in case there are multiple functions with different signatures:
```
IEnumerable<Type> types = parameters.Select(p => p.GetType());
var mi = ty.GetMethod(functionName, types.ToArray());
```

3.  And silently swallowing exceptions and just returning null - is really bad practice.

**Comment by spudwebb** [comment]
I agree the PluginFunction implementation could be enhanced, but I don't understand why you need to be able to override it? Is it only because your scripting functions are not defined in your HSPI class?
Ideally the PluginFunction implementation should be the same for all plugins, so I'm not sure it's a good idea to make it virtual.

**Comment by alexbk66** [comment]
Yes, I define the functions in the device class and any function takes the firts argument device ID, so controller finds the device by ID and calls the function in the device.

If the first argument is not valid device ID - then normal plugin function is called.
I don't want to define **every** function in HSPI.  And it's simple to make PluginFunction virtual.

**Comment by alexbk66** [comment]
> your scripting functions are not defined in your HSPI class

I don't have any scripting functions specifically, I expose any public finction defined in the device class, so the user is free to call anything they want

**Comment by spudwebb** [comment]
tracked as PSDK-214

**Comment by jldubz** [comment]
This was changed in [v1.4.0.0](https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_4_0_0.html)
