### ISSUE TITLE
best practice for providing multiple Actions within the plugin

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#134]
I see two options, but am open to other ideas:

(1) One master AbstractActionType Class where the plugin handles the actual 'action list' using a View  
(2) make each plugin action a separate AbstractActionType Class, and let HS4 handle the list of actions.

I have about 13 actions to build

what's the preferred method

**Comment by spudwebb** [comment]
I think (1) would be better because if each plugin adds a dozen action types we would end up with a huge SelectList to choose from.
