### ISSUE TITLE
OnEditAction vs OnConfigItemUpdate

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#135]
what is the real different between these two methods?

i dont see oneditaction in the lifecycle on this page
https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.Events.AbstractActionType.html?tabs=cs

**Comment by spudwebb** [comment]
OnEditAction  default implementation calls OnConfigItemUpdate, you usually only need to override OnConfigItemUpdate

```c#
protected virtual void OnEditAction(Page viewChanges) {
            var viewCount = ConfigPage?.ViewCount ?? 0;
            foreach (var changedView in viewChanges.Views) {

                if (!(ConfigPage?.ContainsViewWithId(changedView.Id) ?? false)) {
                    continue;
                }

                if (OnConfigItemUpdate(changedView)) {
                    ConfigPage.UpdateViewById(changedView);
                }

                if (viewCount != (ConfigPage?.ViewCount ?? 0)) {
                    break;
                }
            }
        }
```

**Comment by alexbk66** [comment]
It's the same for all types of config pages - there's virtual function which takes **all** changed views, and it iterates the views and calls another virtual function which takes **one** view.
