### ISSUE TITLE
EProperty.Image property returns empty

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#138]
**Environment and System Config**
- OS: Windows
- Language: C#
- HomeSeer Version: latest
- PluginSDK Version: latest

**Describe the issue**
The EProperty.Image is supposed to return "The address of an image that represents the current status of the device/feature" - but it's always empty?

**Comment by spudwebb** [comment]
It actually return the old product image that you were able to set in HS3. So this is a bug, but I wonder why you would ever need to get the current status image?

**Comment by alexbk66** [comment]
In all my plugins on device summary page I display the real time device status (in timer callback)
I checked my HS3 code - I use `hs.DeviceVGP_GetGraphic(RefId, Value)` for that.  Is it avaliable in HS4?

![image](https://user-images.githubusercontent.com/2533315/104206770-0a4a7480-5484-11eb-91c9-c0b3c585451a.png)

**Comment by alexbk66** [comment]
Found it - GetStatusGraphicForValue?

**Comment by spudwebb** [comment]
yes GetStatusGraphicForValue should do what you want

**Comment by alexbk66** [comment]
> It actually return the old product image that you were able to set in HS3. 

And just to confirm - "the old product image" is not required/used anymore in HS4?

**Comment by spudwebb** [comment]
> And just to confirm - "the old product image" is not required/used anymore in HS4?

Correct.
We are going to remove EProperty.Image from the PluginSdk

**Comment by alexbk66** [comment]
Cool, thank you
