### ISSUE TITLE
Status is not updating in the "controls" view

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#139]
When I click on the "Controls" in grid view - and control a device in the "Features" window - the device status isn't updating.
If I close and re-open the window - it does show the new status.

![image](https://user-images.githubusercontent.com/2533315/104704813-3b20f700-576d-11eb-83a4-176de4fe60f1.png)

**Comment by spudwebb** [comment]
This is a known problem, tracked by HS-787

**Comment by alexbk66** [comment]
> This is a known problem, tracked by HS-787

Where?

**Comment by spudwebb** [comment]
> > This is a known problem, tracked by HS-787
> 
> Where?

it's a reference to an issue in HomeSeer internal bug tracker, you don't have access to it.

**Comment by spudwebb** [comment]
This problem has been fixed in HS 4.1.17.0, the status of the features are now updated in the features dialog in grid view
