### ISSUE TITLE
Change RegisterFeaturePage to allow param to be passed

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#14]
Can this function 

 Sub RegisterFeaturePage(pluginId As String, pageFilename As String, linkText As String)

be changed to either allow a URL (with query params) to be passed or an optional parameter to pass parameters? Each of my players has a feature page (player control page with navigating content etc) and I really don't think creating multiple .html files on the fly for each player, with exact same content, just pointing to a different instance of a player is a recommend strategy.

In HS3, we had the "instance" parameter AND we could add  query parameters so generating the page was common for all players and embedded  JS made sure the right info was presented.

**Comment by rjhdakota** [comment]
You should be able to add a query string to each register call like:

plugin_feature.html?player=3456

Then in your single feature page you can get the query string with:

{{player=queries['player']}}

**Comment by dcorsus** [comment]
@rjhdakota , I just tried to implement the above suggestion but I get an error:
 
404 Bad Request: /SonosV4/sonos-test.html&deviceudn=RINCON_7828CA05E5CE01400

This is exactly what I had in mind BUT doesn't this also cause issues when you try to:

UnregisterFeaturePage (id, filename)  where there are now x links esablished with same filename but different querystring.

Thoughts?

**Comment by dcorsus** [comment]
OOOOOPS, I should have used a ? character instead of a &
Stay tuned, didn't have enough coffee this moring

**Comment by dcorsus** [comment]
Update: the use of a query string is working. I don't see any errors unregistering the FeaturePage using the filename and query string, doesn't mean it works because the PI terminates and I believe HS is just cleaning up all registered weblinks.
I'll do some more testing because there were always issues in HS3 when a weblink was unregistered and I've seen the same in HS4. I see this in the case where a user changes the name of a player. When that happens, I unregister the existing weblink and register a new one with the new player name. When I do that, I can see a bunch of links (in the menu) go missing.
On a final note, perhaps you should update the docs to show that you can use query strings when you register a feature page, a very powerful capability.

**Comment by dcorsus** [comment]
@rjhdakota 
Rich, the queries function is supposed to return the last query, correct?

This is what the documentation says:
**Holds the queries from the last request. Can be used to see if any queries were added to the URL**

However, I see it holding ALL query keys/value as a SUM of ALL webpage queries for my PI. It overwrites a key/value with the current web request, but the returned dictionary has every different key/value of any web request. This is causing issues when I have a webpage that is checking whether a parameter is present in the current web request and mistakenly gets information from a totally different webpage request.

Could you have a look at that. If that is expected behavior how do I get the query STRING (as opposed to a dictionary) of the current webrequest so I can use it in my html page?

Thanks for looking into this.

Dirk

trace, note the different pagenames but growing Query dictionary

10/12/2019 10:54:35 AM : GetPageDevice for UPnPDebugWindow called with pageName = UPNPViewer and queryString = UDN = uuid:RINCON_7828CA058C1C01400, subpage = log_div_logentries.html, _ = 1570901421119

10/12/2019 10:56:42 AM : GetPagePlugin for SonosLinktableConfig called with pageName = sonos-linkgroup.html and user =  and userRights = 0 and queryString = UDN = uuid:RINCON_7828CA058C1C01400, subpage = log_div_logentries.html, _ = 1570901421119

10/12/2019 10:58:43 AM : GetPagePlugin for SonosLinktableConfig called with pageName = sonos-linkgroup.html and user =  and userRights = 0 and queryString = UDN = uuid:RINCON_7828CA058C1C01400, subpage = log_div_logentries.html, _ = 1570901421119, deviceudn = RINCON_347E5C00D79101400, devicename = Kitchen

10/12/2019 11:00:31 AM : GetPageDevice for UPnPDebugWindow called with pageName = UPNPViewer and queryString = UDN = uuid:RINCON_7828CA058C1C01400, subpage = log_div_logentries.html, _ = 1570901421119, deviceudn = RINCON_000E5832D2D401400, devicename = Patio

**Comment by rjhelmke** [comment]
Is this still an issue, I believe we put in some fixes for this.
