### ISSUE TITLE
HS.SaveVar(string Name, object obj)

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#142]
I can't find anything for Variables mahagement in HS4 i.e.

string SaveVar(string Name, object obj)
string CreateVar(string Name);
object GetVar(string Name);

**Comment by rjhdakota** [comment]
Can I ask what you need this for? I think we left them out waiting for a use case. You are the first to ask about them. You can easily create global vars in scripts. You can also use the INI file functions to save info that needs to persist.

**Comment by alexbk66** [comment]
> I think we left them out waiting for a use case

here's the use case [AK Google Calendar plugin introduction / instructions / screenshots](https://forums.homeseer.com/forum/internet-or-network-related-plug-ins/internet-or-network-discussion/ak-google-calendar-alexbk66/1299279-ak-google-calendar-plugin-introduction-instructions-screenshots)

![image](https://user-images.githubusercontent.com/2533315/104978323-ba584880-5a55-11eb-926c-543d6cee745b.png)

**Comment by alexbk66** [comment]
> You are the first to ask about them. You can easily create global vars in scripts. You can also use the INI file functions to save info that needs to persist.

I create the variables at run time in my plugin.  So please add them back.

**Comment by rjhdakota** [comment]
Ok, I see that the variables can be accessed using the global replacement variables, I did not even know that. I will see about getting them added back. They are actually still there, just need the API.

**Comment by alexbk66** [comment]
> Ok, I see that the variables can be accessed using the global replacement variables, I did not even know that. I will see about getting them added back. They are actually still there, just need the API.

Thank you

**Comment by spudwebb** [comment]
Tracked as PSDK-119

**Comment by alexbk66** [comment]
FYI, using old HS3 `IHSApplication` global variables still work, thanks god:

![image](https://user-images.githubusercontent.com/2533315/106009166-28fb6d00-610c-11eb-85e1-01dfe625e8d1.png)

**Comment by spudwebb** [comment]
The following methods have been added to Plugin SDK version 1.2.2

```
IHsController.CreateVar()
IHsController.DeleteVar()
IHsController.GetVar()
IHsController.SaveVar()
```
