### ISSUE TITLE
has hs.appstarting been removed

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#143]
hs.appstarting doesn't appear to exist anymore

is there an alternative approach to determine when HS4 is complete initialized/ready?

@spudwebb , @rjhdakota

**Comment by spudwebb** [comment]
why do you need this?
the start of the plugins is the last task during HS4 initialization, so HS4 should already be ready when your plugin is started.

**Comment by mnsandler** [comment]
i guess i dont based on what you said. in hs2/hs3, plugins could initialize before hs was ready this causing problems for triggers and actions. I also interface with other insteon plugins so i need to make sure everything is ready before i start
