### ISSUE TITLE
What's the deal with Root device?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#144]
Can anybody please clarify what can / can't / should I do with root device?

Ok, I get may be I can't add controls to the root, but can I add Status Graphics?  My understanding is that I should be able to use root to display status at least?

BTW, in HS UI (Status/Graphics devprop page) itself I am able to add any control/status graphics to the root, no problems.  And it even works - the root graphics does reflect current state.

By why then IHsController has only AddStatusGraphicToFeature?  Why can't I  AddStatusGraphicTo Device?

**Comment by alexbk66** [comment]
![image](https://user-images.githubusercontent.com/2533315/104975335-888fb380-5a4e-11eb-82e7-fb60e5b8e408.png)

**Comment by spudwebb** [comment]
You should not add any StatusGraphic or StatusControl  to a root device.
If you can add/edit StatusGraphic and StatusControl through HS UI then I think it's a bug, you should only be able to do that for HS3 devices.

**Comment by alexbk66** [comment]
> You should not add any StatusGraphic or StatusControl to a root device.
> If you can add/edit StatusGraphic and StatusControl through HS UI then I think it's a bug, you should only be able to do that for HS3 devices.

It does work and is displayed correctly in the grid view.  I don't get why I can't use the root device? 
I.e. if I have **only one** HS device which shows the comms state good/bad - do you suggest to add **another** device just to display the state? Weird.

**Comment by alexbk66** [comment]
![image](https://user-images.githubusercontent.com/2533315/105196238-85e8a780-5b8f-11eb-97ea-3b3c4dbbc93a.png)

**Comment by spudwebb** [comment]
> I.e. if I have **only one** HS device which shows the comms state good/bad - do you suggest to add **another** device just to display the state? Weird.

yes

**Comment by alexbk66** [comment]
Closing as "No intention to implement"
