### ISSUE TITLE
TimeSpan view

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#147]
Can we expect support for TimeSpan in Views, Actions, Triggers?

**Comment by spudwebb** [comment]
Yes this is on the roadmap (tracked as PSDK-1), but unfortunately bootstrap does not provide a good timespan picker component so this is not as easy as it looks.

**Comment by alexbk66** [comment]
I'm sure it's possible 
https://getdatepicker.com/4/
https://www.jqueryscript.net/tags.php?/Time%20Picker/

Also, what I did in my code - just use InputView and then parse user input. It's actually pretty good because, say, by default I just use only seconds (for polling rate) - then user can simply enter a number. But also they can enter 5M, or 1:30, etc.

You can add the time picker view asap - and until you find a good Bootstrap control - just use this parsing approach internally.

Later you can change to use the control, but the beauty is - existing plugins won't need to change because the timepicker view interface won't change.

**Comment by alexbk66** [comment]
I created a TimeSpan view composed of three SelectListViews.
![image](https://user-images.githubusercontent.com/2533315/108192314-38e4fa80-7168-11eb-9c37-b51d57737662.png)

It works fine. Just wondering why I need to spend (waste) a day on something which already existed in HS3, and you had 2 years to port to HS4...

**Comment by spudwebb** [comment]
A TimeSpanView class has been implemented in PluginSdk 1.3.0.0 / HS 4.1.17.0

https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.Jui.Views.TimeSpanView.html?tabs=cs
