### ISSUE TITLE
question about ConvertLegacyData(inData As Byte())

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#148]
@spudwebb 

in hs3, I used more than one 'MyLegacyEventActionDataClass'. I had one base class and several inherited classes

I used strTrigActInfo.TANumber to determine which inherited class was represented in the strTrigActInfo.DataIn() byte array. I would deserialize from them.

So in HS4, I'm not sure how I will determine which action is represented in the inData argument above

thoughts?

**Comment by alexbk66** [comment]
The new actions and triggers are just wrappers for old TrigActInfo stuff.  What I have to do - and that's sad wasting my life on this -
Download PluginSdk source and include it in my VS solution (instead of using pre-build library). Then you can debug it and see what's going on there.  I override Action constructors (all 4) in my derived class, so you can trace where it's called from, you cand do some additional processing, etc:

![image](https://user-images.githubusercontent.com/2533315/105618522-45fa1c80-5e3c-11eb-849a-ad1b5c570afc.png)

**Comment by alexbk66** [comment]
![image](https://user-images.githubusercontent.com/2533315/105618551-b1dc8500-5e3c-11eb-8868-b9ff035f8d64.png)

**Comment by alexbk66** [comment]
Not sure if that's what you are after, but to get all your actions:

```
List<TrigActInfo> acts3 = hs.GetActionsByInterface(plugin.Name);
foreach(TrigActInfo ai in acts3)
{
    Page page = DeSerialize(ai.DataIn);
}
```

**Comment by mnsandler** [comment]
Alex,
thanks for the reply.

i built a completely new set of triggers and one action using the hs4 new classes.

I thought hs4 would call ConvertLegacyData if there was any hs3 data to be converted.

So to test this, I loaded an hs3 database (with trigs and actions), and started hs4, but I don't see the triggers or actions displayed and ConvertLegacyData is never called

I have an email to Rich on this

**Comment by alexbk66** [comment]
> I thought hs4 would call ConvertLegacyData if there was any hs3 data to be converted.

It does, I'll PM you in HS forum

**Comment by alexbk66** [comment]
If you look at AbstractActionType.cs - _ConvertLegacyData_ is called from _ProcessData(byte[] inData)_ which in turn is called from three constructors of _AbstractActionType_.  So to make sure _ConvertLegacyData_ is called - you need to override all four constructors.  Because they use Reflection to check if you provide a ctor which takes _byte[] dataIn_.

**Comment by spudwebb** [comment]
> in hs3, I used more than one 'MyLegacyEventActionDataClass'. I had one base class and several inherited classes
> 
> I used strTrigActInfo.TANumber to determine which inherited class was represented in the strTrigActInfo.DataIn() byte array. I would deserialize from them.
> 
> So in HS4, I'm not sure how I will determine which action is represented in the inData argument above
> 
> thoughts?

To answer your original question
In your HS4 plugin, in your HSPI constructor you should add as many action type as you had in the HS3 plugin, so something like that:
```
ActionTypes.AddActionType(typeof(Action1Type));
ActionTypes.AddActionType(typeof(Action2Type));
ActionTypes.AddActionType(typeof(Action3Type));
```
Action1Type will be the HS4 equivalent of TANumber=1
Action2Type will be the HS4 equivalent of TANumber=2
etc...

in each of your ActionXType class you should have a ConvertLegacyData method specific to that action which will convert the data for that specific action.

**Comment by mnsandler** [comment]
@spudwebb,
can I just write some one time code to ready existing hs3 event data (in my hs4 plugin) and convert it up front and be done with it?

I have already built out all my prev actions as 'sub' actions under one primary actiontype. no going back now.

**Comment by spudwebb** [comment]
you could try to get all your actions using GetActionsByInterface(), then convert the data, and save them using UpdatePlugAction() but I don't think this has ever been tested by anyone:

see
https://github.com/HomeSeer/Plugin-SDK/issues/68#issuecomment-595481935

**Comment by alexbk66** [comment]
> you could try to get all your actions using GetActionsByInterface(), then convert the data, and save them using UpdatePlugAction() but I don't think this has ever been tested by anyone:
> 
> see
> [#68 (comment)](https://github.com/HomeSeer/Plugin-SDK/issues/68#issuecomment-595481935)

I didn't know about UpdatePlugAction, I was sure we don't have control over saving actions.

**Comment by alexbk66** [comment]
> Action1Type will be the HS4 equivalent of TANumber=1
> Action2Type will be the HS4 equivalent of TANumber=2

I **hate** code based on assumptions - when you have two separate places in you code for related stuff, i.e. later accidently you change the order of adding actions (ActionTypes.AddActionType) - and everything is broken and you don't have any idea why...

So in my code I add **static** TANumber to every action/trigger class, then the functions registering the action/trigger set this static TANumber:

![image](https://user-images.githubusercontent.com/2533315/105785975-3ca1b900-5fd0-11eb-9f96-a98af6aec891.png)

**Comment by alexbk66** [comment]
Same for adding sub-triggers to SubTriggerTypeNames and then using the magic numbers in switch statements.

Instead I use enums (converted to string when adding to SubTriggerTypeNames)

![image](https://user-images.githubusercontent.com/2533315/105786476-42e46500-5fd1-11eb-9c82-fac362cfeb58.png)
![image](https://user-images.githubusercontent.com/2533315/105786562-6effe600-5fd1-11eb-9855-53dec5d3b8a0.png)

**Comment by mnsandler** [comment]
@spudwebb 

something funny going on here
hs.GetActionsByInterface(plugin.Name) & hs.GetActionsByInterface(plugin.ID) returns a different list of Actions

using ID seems to return HS3 actions only, and using Name returns HS4 actions

for me ID="Insteon", Name="Insteon Plugin"

my understanding is Name is supposed to be for display purposes only; not for an internal key

**Comment by spudwebb** [comment]
> @spudwebb
> 
> something funny going on here
> hs.GetActionsByInterface(plugin.Name) & hs.GetActionsByInterface(plugin.ID) returns a different list of Actions
> 
> using ID seems to return HS3 actions only, and using Name returns HS4 actions
> 
> for me ID="Insteon", Name="Insteon Plugin"
> 
> my understanding is Name is supposed to be for display purposes only; not for an internal key

your understanding is correct and you're right there is definitely an issue here. I would advise to set ID = Name = "Insteon" until we fix this.

**Comment by mnsandler** [comment]
thanks for the confirmation. I will make this adjustment temporarily.

**Comment by alexbk66** [comment]
> your understanding is correct and you're right there is definitely an issue here. I would advise to set ID = Name = "Insteon" until we fix this.

So it means we have to do it in all plugins with Actions?  Does it apply to Triggers as well?

**Comment by spudwebb** [comment]
FYI, the issue of plugin Id vs plugin Name has been fixed in HS 4.1.14.0 and the inline documentation has been fixed in PluginSdk 1.2.3.
Now you should always pass the plugin ID instead of the plugin Name to methods that manipulate triggers and actions.

If you are using a plugin Id different from the plugin name, and if your plugin implements some triggers or actions please update your plugin code ASAP as it will no longer work with HS 4.1.14.0

**Comment by alexbk66** [comment]
Thank you @spudwebb

**Comment by alexbk66** [comment]
@spudwebb does it apply to all functions, i.e. 
TriggerMatches, 
GetTriggersByType, 
GetTriggersByInterface
TriggerFire
GetTriggersByInterface
GetActionsByInterface
?

**Comment by spudwebb** [comment]
> @spudwebb does it apply to all functions, i.e.
> TriggerMatches,
> GetTriggersByType,
> GetTriggersByInterface
> TriggerFire
> GetTriggersByInterface
> GetActionsByInterface
> ?

yes
