### ISSUE TITLE
how to test the migration of triggers and actions from hs3 to hs4

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#149]
i thought if i copied an hs3 homeseerdata.hsd file to the hs4 data folder, i would be able to test ConvertLegacyData

i also put the following in to the settings.ini file
gConfigFilename=homeseerdata.hsd

I can see the legacy events and actions but the event action isn't complete
i see a lot of this msg: "The plug-in Insteon is not running or is not connected to HomeSeer."

doesn't seem to be working: ConvertLegacyData isn't called.

how do i get hs4 to work with an hs3 legacy database?

**Comment by spudwebb** [comment]
Here is the guide to upgrade from HS3 to HS4 on windows: https://docs.homeseer.com/display/HS4/Windows+and+S6
However ConvertLegacyData will not be called during this upgrade procedure, it will only be called when you try to edit a trigger or action that was created with your HS3 plugin.

Here is a quicker way to test your ConvertLegacyData that I used for example for the Chromecast plugin:
1.  install your HS3 plugin on your HS4 system
2.  create a few triggers and actions specific to this plugin
3.  upgrade the plugin to its HS4 version 
4.  try to edit the triggers and actions created at step 2., , here the ConvertLegacyData should be called.

**Comment by mnsandler** [comment]
ConvertLegacyData isn't going to work for me since I'm trying to collapse all my hs3 actions into 1 hs4 action with several sub actions. i have no way to determine my old action number from DataIn.

**Comment by alexbk66** [comment]
> ConvertLegacyData isn't going to work for me since I'm trying to collapse all my hs3 actions into 1 hs4 action with several sub actions. i have no way to determine my old action number from DataIn.

Isn't TANumber the action number (one based)?

**Comment by mnsandler** [comment]
ConvertLegacyData only provides access to DataIn(). Where/how would I get a trigactioninfo object within ConvertLegacyData  to get access to TANumber?

I believe HST assumes you are doing 1-1 actionclass mapping and thus you don't need trigactinfo. this doesn't work for me right now.

**Comment by alexbk66** [comment]
> I believe HST assumes you are doing 1-1 actionclass mapping

Yeah, you are right - `ActionTypeCollection.GetObjectFromActInfo` assumes that you register action types in the order of TANumber, which is pretty dodgy.  I.e. if you change the order or remove some action - everything is broken.

But still, `GetObjectFromActInfo` is called from AbstractPlugin ActionBuildUI => ActionTypes?.OnGetActionUi(actInfo), which is not declared 'virtual' unfortunately, but you still can trick it by declaring the function as `new` in your HSPI class:
```
public new string ActionBuildUI(TrigActInfo actInfo)
```
From there you have access to `TrigActInfo.TANumber`

**Comment by mnsandler** [comment]
Alex, thanks again for the ideas

I've been working the CheckEventActionIntegrity() route based on the code posted here somewhere.

i like the idea of running this routine once to convert hs3 actions to hs4 actions and be done with it.

so I loop thought hs4.GetActionsByInterface(IFACE_NAME) to get the infoactinfo objects

i can convert them to my new hs4 values and develop new datain, but the new actions aren't showing on the event page

there is something broken on the inside 

**i think the following might be related to my problem:**

for me GetActionsByInterface(Id) gets a different list than GetActionsByInterface(Name). My plugin properties do not return the same values

i think hs4 actions are registered using Name instead of Id

**Comment by alexbk66** [comment]
Mess

**Comment by mnsandler** [comment]
fwiw, using the same value in my Name property fixed my problem of migrating hs3 actions to hs4. I expect the same issue with Trigger migration.  I'll wait for the permeant fix before going live. I'm sure we will find other bugs like this.

hang in there

**Comment by alexbk66** [comment]
> I'm sure we will find other bugs like this

Yeah, problem is we are wasting our life doing testing for HST for free.  No, not free - they charge us 30% :(
