### ISSUE TITLE
AJAX appears not to update any child devices in devices.html

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#15]
Information based on devices or primeryreference of devices are updated in the tile view but not in the list view. None of the child features such as track info, tack position etc seem to be updated at all.

**Comment by dcorsus** [comment]
actually in the list view I see this code

  <div id='11stimgprim_{{d.primary_ref}}' class="mr-2"><img src='{{ status_image_file d.primary_ref }}' width='40' height='40' data-toggle='tooltip' data-placement='top' title='{{ status_text d.primary_ref }}'></div>

and I wonder whether the 11 in 11stimgprim_ was added for test purpose, mistake or by design. If I remove the "11" at least the primary reference device/feature gets updated dynamically.

I think the div-ids for child devices need to be created & added or if they exist, what is the syntax so we can use them or you can add them to the devices.html file.

**Comment by rjhdakota** [comment]
Still working on the auto update on the devices page, this will be fixed in update 4.0.0.25.

**Comment by dcorsus** [comment]
Not sure why this was closed as it is not fixed today (v29)

**Comment by rjhdakota** [comment]
I should have this fixed by build 4.0.0.31.
