### ISSUE TITLE
When adding new event - it's really difficult to enter new event name 

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#151]
In the "New Event" window the area for clicking to activate the input field is very small and not obvious.  And the input field should be activated (have focus) by default anyway:
![image](https://user-images.githubusercontent.com/2533315/105649068-c08d6f80-5f02-11eb-907e-2d04d7ea2d8f.png)

**Comment by spudwebb** [comment]
I have just fixed this problem. (tracked as HS-1099). Before the fix if you clicked on "Event Name" label nothing happened you had to click on  the empty space on the right of the label to activate the input field.

The fix should be in HS4 next release (4.1.12.0)

**Comment by alexbk66** [comment]
Great.  And is it possible to set focus to the input field, so the user can start typing without need to click?

**Comment by spudwebb** [comment]
Fixed in HS 4.1.12.0
