### ISSUE TITLE
Why TriggerTypeCollection.GetObjectFromActInfo is declared 'private', not 'public'?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#152]
Why `TriggerTypeCollection.GetObjectFromActInfo` is declared _private_, not _public_?

If I need to construct AbstractTriggerType from TrigActInfo (inside HSPI class) - I could use the function.

In your sample plugin you construct `SampleTriggerType` **explicitly** because you have **only one trigger type**.

![image](https://user-images.githubusercontent.com/2533315/105663729-1aa02c00-5f27-11eb-95b0-fc263e56c011.png)

But if I have multiple trigger types and sub-types and I want to implement `ShouldTriggerFire` function to pass some data (like you do) - how can I do that?

Another option is to change signature of `public bool TriggerTrue(TrigActInfo trigInfo, bool isCondition = false)` to pass some data (i.e. object or object[])

**Comment by alexbk66** [comment]
Hey anybody, @spudwebb - I may be completely stupid, but I struggle to understand how to use Triggers in HS4.

I want to check if particular trigger should be fired, obviously.  So I call one of 
```
hs.TriggerMatches
hs.GetTriggersByType
hs.GetTriggersByInterface
```
(already confusing - which one?)

So I get an array of `TrigActInfo`.  Now I need to compare some property of each trigger with some value.  How?  I need to de-serialize `TrigActInfo` to `AbstractTriggerType`, right? 

In your sample plugin you construct `SampleTriggerType` explicitly because you have only one trigger type.  If I have multiple triggers/subtriggers - what do I do?  Just try to construct each one from `TrigActInfo` and see if it fails?  I'm lost...

**Comment by alexbk66** [comment]
I think that basically what we need - 
```
hs.TriggerMatches
hs.GetTriggersByType
hs.GetTriggersByInterface
```
instead of returning "legacy" `TrigActInfo[]` - should return `AbstractTrigger[]`.  Right?

**Comment by alexbk66** [comment]
It's nice to know that you are actually improving it, it's been more than a year from my original request - you can't expect plugin developers to wait that long?

**Comment by jldubz** [comment]
Change has been submitted in #299 for release in v1.4.2.0 alongside v4.2.14.0 of HomeSeer. Add comments to the pull request if there are any issues with the change.

**Comment by alexbk66** [comment]
It's been 1.5 years from the original request, I honestly don't remember what it was about...
