### ISSUE TITLE
Main device selected in Grid View

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#153]
It's been discussed many times, but this is slightly different (still related to setting priority)

I have multiple equal devices. Why Grid view picks the last one, not first?
The first device (next calendar event) is most important

![image](https://user-images.githubusercontent.com/2533315/105703276-155fd300-5f61-11eb-915b-7b82311ed517.png)
![image](https://user-images.githubusercontent.com/2533315/105703318-2577b280-5f61-11eb-9b41-bb5aa9160b85.png)

**Comment by spudwebb** [comment]
Not sure what is the exact algorithm to pick up the main feature, but this problem will become moot once you can set a priority for each feature.

**Comment by alexbk66** [comment]
> Not sure what is the exact algorithm to pick up the main feature, but this problem will become moot once you can set a priority for each feature.

ETA?

**Comment by alexbk66** [comment]
Is it implemented yet?

**Comment by spudwebb** [comment]
In the PluginSdk version 1.3.0.0 there is some preview code for this, but it won't be functional until HS 4.2 is released

see release notes: https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_3_0_0.html

**Comment by dcorsus** [comment]
Do we PI authors get early access to R4.2, is there a release strategy? ETA?

**Comment by spudwebb** [comment]
I'm closing this because since HS 4.2 you can set the DisplayPriority and DisplayType for each feature
