### ISSUE TITLE
ColorPicker Inconsistencies in Value Change and HS3/HS4

### ISSUE THREAD

**Issue by RVCTinker** [HomeSeer/Plugin-SDK#154]
**Environment and System Config**
- OS: [Windows]
- Language: [VB and C#]
- IDE: [VS2019]
- HomeSeer Version: [v4.1.11.0]
- PluginSDK Version: [v1.2.1]

**Describe what you would like to see added or changed**
Color picker control: Using /Events page (HS3 Legacy) I get a nice color picker, and when I run the event, it calls SetIOMulti like I was expecting and my new plug-in handles it fine.  Under HS4, I can use the same color picker on the device and when I make a selection it calls SetIOMulti and we're good - BUT if I add that feature to a control device action under the HS4 events, then I do not get a color picker (only a list of random number values) and - here is the kicker - run the event after picking a number and SetIOMulti is not called at all.

**Priority**
How important is this to you on a scale of 1-5?
5. Blocking

**Comment by spudwebb** [comment]
This problem has been fixed recently, the fix will be in the next release of HS4 (4.1.12.0)
Tracked as HS-1090

**Comment by RVCTinker** [comment]
Thanks Chris!

Rick

------ Original Message ------

**Comment by spudwebb** [comment]
Fixed in HS 4.1.12.0

**Comment by RVCTinker** [comment]
Thank you!
