### ISSUE TITLE
If only one of children devices has only one control - it should be displayed in Grid view

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#158]
![image](https://user-images.githubusercontent.com/2533315/106266713-e2795000-627c-11eb-81e4-98ec1fc00696.png)

![image](https://user-images.githubusercontent.com/2533315/106266759-f02ed580-627c-11eb-92bb-abd5aabc2654.png)

**Comment by spudwebb** [comment]
It is supposed to and on the few examples that I checked it seemed to work.
Could you send me your devices.json so that I can take a look.

**Comment by alexbk66** [comment]
[devices.zip](https://github.com/HomeSeer/Plugin-SDK/files/5922659/devices.zip)

**Comment by spudwebb** [comment]
All your features have controls but most of them have their type set to StatusOnly. HS4 wrongly consider StatusOnly controls like any other controls when it tries to guess which feature should be displayed as the primary feature in grid view. We will fix that.

That being said in a HS4 plugin I don't see any good reason to create a "StatusOnly" control. By definition a StatusGraphic is status only so you don't have to duplicate this value as a StatusControl. So for the feature in the screenshot below I would recommend to not create any o the 4 Status/Controls that you have right now, (which will also solve your original problem)

![image](https://user-images.githubusercontent.com/5427056/106909196-0b12a700-66ce-11eb-9d0f-1e8bc1695ce6.png)

**Comment by alexbk66** [comment]
Thank you, I'll have a look

**Comment by alexbk66** [comment]
Ok, I'm lost a bit.  

Do I need to do hs.AddStatusControlToFeature() if it's status only device?
Or hs.AddStatusGraphicToFeature() is sufficient?
What's "StatusOnly controls"?  Doesn't make sense.

**Comment by alexbk66** [comment]
If not setting Status/Controls at all (only Status/Graphics) - then it works as expected - first child is displayed.
Still, questions above need answers.  Is it documented anuwhere?

![image](https://user-images.githubusercontent.com/2533315/107108134-e9f6b580-6889-11eb-87dc-ee73bd53deaf.png)

**Comment by spudwebb** [comment]
> Do I need to do hs.AddStatusControlToFeature() if it's status only device?

No you don't

> Or hs.AddStatusGraphicToFeature() is sufficient?

AddStatusGraphicToFeature is sufficient

> What's "StatusOnly controls"? Doesn't make sense.

EControlType.StatusOnly  is the equivalent of  EControlType.Not_Specified we had in HS3, so basically it is a control that is not rendered on the Devices page. The only time I used this in a HS3 plugin is when I didn't want the control to appear on the devices page but still wanted the user to be able to select this control value from an event.
So I agree "StatusOnly" is a misleading name.

> Is it documented anywhere?

It's documented here:
https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.Devices.Controls.StatusControl.html?tabs=cs#constructors

> Remarks
> Legacy VSPairs used to be able to be defined as either status-only, control-only, or both, but this is no longer allowed. All StatusControls are considered both, and a StatusGraphic will override the Status on the feature if it is configured for the feature's current Value.
> 
> If you are looking to add a status-only control to a feature, create a StatusGraphic instead.

**Comment by alexbk66** [comment]
Thank you @spudwebb 
While we are here - I logged (I think) a bug when user tries to edit the label for status graphics - and other graphics just disappears (just a reminder)

**Comment by spudwebb** [comment]
Original problem is fixed in HS 4.1.12.0
