### ISSUE TITLE
Only three controls are created for device

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#159]
When I add controls (VSPairs) to the device - and don't **explicitly set the controls layout** (row/column) - HS only creates **three** controls!

![image](https://user-images.githubusercontent.com/2533315/106552349-43e63b00-656b-11eb-845f-1d7d05ee4ce5.png)

![image](https://user-images.githubusercontent.com/2533315/106552381-595b6500-656b-11eb-91fb-dca2d513dfbb.png)

**Comment by spudwebb** [comment]
How do you create your controls? If you don't set explicitly the rows/columns then they should be 0. Yours are all set to 1 which is wrong.

I rarely set the rows/colums explicitly, and for me the default value is 0 which works ok:

![image](https://user-images.githubusercontent.com/5427056/106803258-03052980-6632-11eb-869a-68b200233ca8.png)

![image](https://user-images.githubusercontent.com/5427056/106803321-14e6cc80-6632-11eb-8e2b-40cb7c2bf136.png)

**Comment by alexbk66** [comment]
I do set them to "0" by default:
![image](https://user-images.githubusercontent.com/2533315/106834605-df051f00-66e9-11eb-987f-c8a003b68b37.png)

But Controllocation ctor changes them to "1":
![image](https://user-images.githubusercontent.com/2533315/106835403-669f5d80-66eb-11eb-839f-3c6d0f5b807a.png)

So I guess I need to:
```
if (Row > 0 && Column > 0)
    sc.Location = new ControlLocation(Row, Column, ColumnSpan);
```

**Comment by alexbk66** [comment]
**Not setting** ControlLocation does the trick, so closing.
