### ISSUE TITLE
Volume slider for player tile view always zero

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#16]
Fix this in device.html. From value='0' to value='{{c.value}}'

here:

									
									{{ for c in d.children }}
										{{if c.device_sub_type==4}}
											<div class="col-9">
												<div class='mr-1 ml-1 flex-fill' style='width:100%; '>
												<input type='range' class='custom-range flex-fill' id='volume_{{c.ref}}' ref='{{c.ref}}' ccindex='0' action='control' min='{{c.vspairs[0].range_start}}' max='{{c.vspairs[0].range_end}}' step='1' value='{{c.value}}'/>
												</div>
											</div>
										{{end}}
									{{end}}

**Comment by spudwebb** [comment]
this one is fixed in HS 4.0.0.27, I think you can close it.

**Comment by dcorsus** [comment]
Agree
