### ISSUE TITLE
When renaming VSPair label in device settings (Status Graphics tab) - other VSPair is deleted

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#160]
I rename "On" label - the "Off" is gone:
![image](https://user-images.githubusercontent.com/2533315/106682104-e824bc00-6615-11eb-82b5-dd49cae8e9e4.png)
![image](https://user-images.githubusercontent.com/2533315/106682113-eb1fac80-6615-11eb-8840-81cf0b955b73.png)
![image](https://user-images.githubusercontent.com/2533315/106682116-eeb33380-6615-11eb-9d66-b4aafd9b4509.png)

**Comment by spudwebb** [comment]
Tracked as HS-1124. This should be fixed in HS 4.1.13.0

**Comment by spudwebb** [comment]
Closing this because it has been fixed in HS 4.1.13.0
