### ISSUE TITLE
migrating hs3 triggers to hs4

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#162]
I created a new HS4 TrigActInfo object from my HS3 object; convert the hs3 datain byte array, and then setting every property to the new object. then used the following to save it back to the hs4 database

`hs4.UpdatePlugTrigger(Id, newTrigActInfo.evRef, newTrigActInfo)`

my problem is the actually subtrigger isn't getting set/displayed when i return to the event trigger definition. you can see this in the below trigger defintion.  the subtrigger isn't selected even though my custom view to select a device shows just fine

**what am i missing, or is this a bug?**

![image](https://user-images.githubusercontent.com/67801043/107149956-77d5ad80-6929-11eb-92e1-e1dc5dd30f5e.png)

**Comment by spudwebb** [comment]
To determine where is the problem, can you check that newTrigActInfo.SubTANumber is correctly set before you call UpdatePlugTrigger?
If it's ok then can you edit  Data\HomeSeerData.json\events.json and look for your event in there and check that SubTANumber is correctly saved?

**Comment by mnsandler** [comment]
@spudwebb 
thanks for the reply

in my code i see TA=1, SubTA = 0 (which is correct)

in the events.json file I see "TANumber":7,"SubTANumber":0

i only have one trigger class with 15 sub triggers.

**Comment by spudwebb** [comment]
Don't ask me why but it looks like TANumber and SubTANumber are 1-based, so your first subtrigger should be SubTANumber=1.
SubTANumber=0 is not a valid subtrigger number.
As for TANumber=7 in the events.json, are you sure you are looking at the correct  trigger? Can you post your events.json and tell me the name of the event I should look at?

**Comment by alexbk66** [comment]
> looks like TANumber and SubTANumber are 1-based

Yes, they always been 1-based, but `SelectedSubTriggerIndex` is 0-based, so I do

```
public int SubTANumber => SelectedSubTriggerIndex + 1;
```

**Comment by mnsandler** [comment]
here is the json file
[events.json.txt](https://github.com/HomeSeer/Plugin-SDK/files/5958910/events.json.txt)

the events name is  "z trigger 1". 

there is  "z Trigger 2" event as well but this one seems to be ok.

**switching back and forth from 0-based to 1-based is crazy**

**Comment by spudwebb** [comment]
TANumber=1 for this event trigger (I guess you were looking at the next event action), so if you fix the SubTANumber, this should work.

```json
{
		"mvarGroupRef": 2146481243,
		"Last_Trigger_Time": "0001-01-01T00:00:00",
		"Triggers": {
			"TrigGroups": {
				"K0": {
					"$type": "System.Collections.Generic.List`1[[Scheduler.Classes.EvTrig_BASE, Scheduler]], mscorlib",
					"$values": [
						{
							"$type": "Scheduler.Classes.EvTrig_PLUGIN, Scheduler",
							"mvarPlugName": "Insteon",
							"mvarInstance": "",
							"mvarTI": {
								"evRef": 12,
								"UID": 1552,
								"TANumber": 1,
								"SubTANumber": 0,
								"DataIn": "eyJ2aWV3cy......UiOm51bGx9",
								"Instance": ""
							},
							"TriggerCount": 1,
							"evRef": 12,
							"PlugTriggerType": 1,
							"TriggerSubType": 0
						}
					]
				}
			}
		},
		"Actions": {
			"mvarActions": {}
		},
		"Version": 1.2,
		"evRef": 12,
		"Name": "Z Trigger 1",
		"EvGroup": {
			"GlobalActions": {
				"mvarActions": {}
			},
			"GlobalConditions": {
				"TrigGroups": {}
			},
			"Version": 1.2,
			"Group": "Insteon",
			"Ref": 2146481243
		},
		"PlugExtraData": {}
	},
```

**Comment by mnsandler** [comment]
Ok, using the same TANumber and TASubNumber for migration between hs3 and hs4 seems to work. i didn't need to do any adjustments.

this 0-based vs 1-based is a little crazy

is hs3, I had a blank subtrigger value for index 0 so everything lined up starting at 1. i might do this in HS4 just to keep things neat.

**Comment by mnsandler** [comment]
@spudwebb 

> Don't ask me why but it looks like TANumber and SubTANumber are 1-based, so your first subtrigger should be SubTANumber=1.
> SubTANumber=0 is not a valid subtrigger number.
> As for TANumber=7 in the events.json, are you sure you are looking at the correct trigger? Can you post your events.json and tell me the name of the event I should look at?

**does this base-1 vs base-0 apply to Actions?** 

in my Action conversion code, I did a SubTANumber - 1 between hs3 and hs4 actions and it looks like it worked, but i will retest

**Comment by mnsandler** [comment]
actions seem to follow the 1-base tasubnumber as well. closing this
