### ISSUE TITLE
Unable to add/edit label property for StatusGraphic of existing feature

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#166]
Version 4.1.12.0, Windows.  Untested in other versions.

It is possible to set the label property of StatusGraphic when a feature is being created through feature factory.  Subsequently the label cannot be set.  Consider following code sequence where iRef is the device reference of an existing feature.

            hs.ClearStatusGraphicsByRef(iRef)
            Dim vgPair As New HomeSeer.PluginSdk.Devices.StatusGraphic("images/HomeSeer/status/off.gif", 0 With {
                .Label = "Closed"
            }
            hs.AddStatusGraphicToFeature(iRef, vgPair)

When viewed with /deviceutility the status-control remains at both.  When viewed with /devices.html the label under the status/graphic remains blank.  

The label on the status/control is properly edited using similar logic with hs.AddStatusControlToFeature

**Comment by spudwebb** [comment]
I just tested that from the Sample plugin and it seems to work for me:

```c#
            HomeSeerSystem.ClearStatusGraphicsByRef(4483);
            StatusGraphic sg = new StatusGraphic("images/HomeSeer/status/off.gif", 0, "Closed");
            HomeSeerSystem.AddStatusGraphicToFeature(4483, sg);
```

![image](https://user-images.githubusercontent.com/5427056/108118879-f7bbf000-706c-11eb-93e1-02756217e968.png)

I'm not a VB .NET expert, but are you sure of this "With " syntax? looks like there is a parenthesis missing somewhere. Why don't you pass the label as a normal third parameter of the Statusgraphic constructor?

**Comment by mcsSolutions** [comment]
My mistake.  My code later cleared the sg as it was adding icons.  This can be closed.  Thank you for the quick look.
