### ISSUE TITLE
Triggers now show as "Error retrieving trigger name" in dropdown list

### ISSUE THREAD

**Issue by BladeZX9123** [HomeSeer/Plugin-SDK#167]
Since updating to .12... when I go to my events with a my plugin trigger it says "Error retrieving trigger name"
This was working fine
What has changed to cause this?

Thanks

**Comment by BladeZX9123** [comment]
Is anyone from HST monitoring these issues?

**Comment by spudwebb** [comment]
I don't think there is any change related to plugin triggers in HS 4.1.12.2 or in PluginSdk  1.2.2
https://docs.homeseer.com/display/HSPI/HS4+Release+4.1.12.0
https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_2_2_0.html

Is there a plugin I can test to reproduce this error? or can you share the code you use to handle those triggers?

**Comment by BladeZX9123** [comment]
Let me check my other plugin and confirm it has the same issue and I will get back to you

**Comment by BladeZX9123** [comment]
OK I found the issue
Apparently in one plugin the Initialize() is not being called which is where I have the triggers added
It is calling InitIO directly instead of calling Initialize()
Do u know why one HS4 plugin would call Initialize() and one would not?

**Comment by spudwebb** [comment]
The InitIO method is implemented in AbstractPlugin.cs and calls Initialize
```c#
        /// <inheritdoc cref="IPlugin.InitIO"/>
        /// <summary>
        /// Called by HomeSeer to initialize the plugin.
        /// <para>Perform all initialization logic in <see cref="Initialize"/></para>
        /// </summary>
        public bool InitIO() {
            try {
                if (LogDebug) {
                    Console.WriteLine("InitIO called by HomeSeer");
                }
                Initialize();
                return true;
            }
            catch (Exception exception) {
                if (LogDebug) {
                    Console.WriteLine(exception);
                }
                _isShutdown = true;
                throw new Exception("Error on InitIO: " + exception.Message, exception);
            }
        }
```

In your plugin you must override the Initialize method but you must not override the InitIO method

**Comment by BladeZX9123** [comment]
Ok got ya - thanks
