### ISSUE TITLE
StatusControlCollection - use inheritance instead of composition

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#168]
Instead of doing
```
public class StatusControlCollection 
{
      private SortedDictionary<double, StatusControl> _statusControls = new SortedDictionary<double, StatusControl>();
}
```
I would do 
```
public class StatusControlCollection : SortedDictionary<double, StatusControl>
```

So you don't need to override `Count`, `Values` and `Keys` (which you don't have).

BTW, why using `KeyNotFoundException` in `Contains()` to check if value exists?  
In general, Exceptions are considered for exceptional situations, not for normal code flow.
Instead better move the code from `this[double value]` into a function
```
public StatusControl this[double value]
{
  StatusControl sc = findStatusControl(value);
  if(sc == null)
    throw new KeyNotFoundException();
  return sc;
}

public bool Contains(StatusControl statusControl) 
{
  return null != findStatusControl(statusControl.IsRange ? this[statusControl.TargetRange.Min] : this[statusControl.TargetValue]);
}

```

**Comment by alexbk66** [comment]
And comments?  It's a **public** SDK - so you could add one line comments, not too much effort?

**Comment by spudwebb** [comment]
Contains method no longer use exceptions in 1.2.4, if you feel some other improvements should be done, please provide PR
