### ISSUE TITLE
Image resizes to standard 40x40 after ajax refresh 

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#17]
The art image on the devices "tiled" view is set in devices.html to be 80x80px. However once updated by what I would think ajax they revert to a 40x40. Is this hardcoded somewhere when (at least) this div id stimgprim_ is being refreshed?

**Comment by rjhdakota** [comment]
While the goal was to put 100% of the UI in the HTML pages, the controls required more complex logic to format the display so some of that HTML you are referring to is generated in code. I will look at this image though it is probably resizing and should not.

**Comment by rjhdakota** [comment]
This is fixed in HS4 build 4.0.1.5 issue HS-49. Was tested and confirmed.
