### ISSUE TITLE
Can we have a setting that identifies Triggers over Conditions!

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#171]
**Environment and System Config**
- OS: [Windows, Linux, Mac, etc]
- Language: [VB or C#]
- IDE: [VS2017, VS2019, JetBrains Rider, etc]
- HomeSeer Version: [v4.0.0.30]
- PluginSDK Version: [v1.0.6.0]

**Describe what you would like to see added or changed**
A clear description of what change you would like to see implemented and why.  Add screenshots to help further explain your request if you can.

**Priority**
How important is this to you on a scale of 1-5?
1. Trivial
2. Low
3. Medium
4. Critical
5. Blocking

Issue#80 was started and subsequently closed but I'm still stuck in that I have clear triggers and clear conditions (and ONLY conditions)!

Can we add a flag or pass information that when an user creates an event and he/she is adding a trigger, I have a way to ONLY provide trigger names and NOT conditions!

In today's implementation, you can override the CanBeCondition flag and set it to true, but there is no CanBeTrigger flag equivalent.

I've tried 2 distinct inplementations:

Implementation 1:
============
I crearte ONE instance of AbstractTriggerType, override CanBeCondition to true but now all trigger and condition names will show when an event is created, irrespective whether the check is IF or ORIF versus AND or ANDIF. If HS would pass a flag indicating this is a trigger or a condition, the PI could return the proper selectable names.

Implementation 2:
============
I create TWO instances of AbstractTriggerType, one that encapsulates my triggers with CanBeCondition to false and one instance of my Conditions but this would need an equivalent CanBeTrigger property (to be set false) and now HS can call the correct instance depending on what is being built in the event (a trigger or a condition).

@spudwebb @jldubz @rjhdakota Not sure who nowadays looks at the issues and/or works on this area of the code.

**Comment by spudwebb** [comment]
let's move this to #237 which is about the same topic
