### ISSUE TITLE
Protocol for assigning TypeInfo.Type to Devices and Features

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#172]
What is the best practice for assigning the following enumerator values to the TypeInfo.Type for root Devices and Features?

if i assign the appropriate EDeviceType to my Root Devices, do I need anything more the Generic as the EFeatureType?

there is almost no information in the SDK docs that explains how these values are used

    Public Enum EDeviceType
        Generic = 0
        Door = 1
        Fan = 2
        Light = 3
        Lock = 4
        Outlet = 5
        RemoteControl = 6
        Switch = 7
        Thermostat = 8
        Window = 9
        Media = 10
    End Enum

    Public Enum EFeatureType
        Generic = 0
        Security = 8
        ThermostatStatus = 16
        ThermostatControl = 17
        Media = 32
        Energy = 256
    End Enum

**Comment by spudwebb** [comment]
read this: https://github.com/HomeSeer/Plugin-SDK/issues/137#issuecomment-759477692
