### ISSUE TITLE
Suggested override for UpdateDeviceByRef & UpdateFeatureByRef 

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#173]
HSDevice and HSFeature both have a Changes property that track changes as one updates various properties.

Instead of making the following call

`UpdateDeviceByRef(123, dv.Changes)`

could be simplified to

`UpdateDeviceByRef(123) `

and internally the Changes would be saved

I understand there are some items in the Changes collection that can't be saved using the first code reference above. I can copy the Changes collection and remove them, but this seems excessive, if they could be ignored using the second code reference above.

**Comment by spudwebb** [comment]
I don't think that would work because the changes are not sent to HS4 until you call UpdateDeviceByRef, so if this function had only one parameter being the ref of the device, then HS4 wouldn't be aware of any change.

What we could add to the PluginSdk is a convenience method like this

```c#
void UpdateDevice(HsDevice dev) 
{
     HomeSeerSystem.UpdateDeviceByRef(dev.Ref, dev.Changes);
}
```

**Comment by mnsandler** [comment]
@spudwebb , thanks for the reply
as I mentioned I've tried that but I get exceptions that certain entries in the Changes collection cannot be updated using the your suggestion:

`UpdateDeviceByRef(dev.Ref, dev.Changes);`

So, i wrote the following to remove certain items from the collection before running UpdateDeviceByRef

```
		Public Sub UpdateDevice(dv As HsDevice)

			Try
				Dim ChangesCopy = dv.Changes
				ChangesCopy.Remove(EProperty.StatusControls)
				ChangesCopy.Remove(EProperty.StatusGraphics)
				ChangesCopy.Remove(EProperty.AdditionalStatusData)

				hs4.UpdateDeviceByRef(dv.Ref, ChangesCopy)

			Catch ex As Exception
			End Try
		End Sub
```

It seems unnecessary that we have to remove certain items in order to exec UpdateDeviceByRef. the HS4/SDK should take care of what to save and what to ignore on the call.

**Comment by alexbk66** [comment]
> What we could add to the PluginSdk is a convenience method like this
> 
> ```cs
> void UpdateDevice(HsDevice dev) 
> {
>      HomeSeerSystem.UpdateDeviceByRef(dev.Ref, dev.Changes);
> }
> ```

In OOP it should really be just `dev.Update()`?

**Comment by spudwebb** [comment]
> @spudwebb , thanks for the reply
> as I mentioned I've tried that but I get exceptions that certain entries in the Changes collection cannot be updated using the your suggestion:
> 
> `UpdateDeviceByRef(dev.Ref, dev.Changes);`
> 
> So, i wrote the following to remove certain items from the collection before running UpdateDeviceByRef
> 
> ```
> 		Public Sub UpdateDevice(dv As HsDevice)
> 
> 			Try
> 				Dim ChangesCopy = dv.Changes
> 				ChangesCopy.Remove(EProperty.StatusControls)
> 				ChangesCopy.Remove(EProperty.StatusGraphics)
> 				ChangesCopy.Remove(EProperty.AdditionalStatusData)
> 
> 				hs4.UpdateDeviceByRef(dv.Ref, ChangesCopy)
> 
> 			Catch ex As Exception
> 			End Try
> 		End Sub
> ```
> 
> It seems unnecessary that we have to remove certain items in order to exec UpdateDeviceByRef. the HS4/SDK should take care of what to save and what to ignore on the call.

I think the underlying problem here is that when you retrieve a HsFeature or HsDevice from HS (using for example GetFeatureByRef), it basically has all its current properties already in the Changes dictionary. I think this is a bug (logged as HS-1135), HS should return HsFeature and HsDevice with an empty Changes dictionary, then you can set some properties from your plugin and send the changes to HS using UpdateDeviceByRef to save them.

**Comment by mnsandler** [comment]
@spudwebb 
I hear you about the bug HS-1135 but i dont think that changes my suggestion. as we make changes to hsdevice/hsfeature objects, the changes will be collected in Changes, right?. So, we shouldn't need to build our own Changes collection

the call to UpdateDeviceByRef should uses the Changes in the collection internally

**Comment by mnsandler** [comment]
> In OOP it should really be just `dev.Update()`?

@alexbk66 ,  how would this work since the dev object probably doesn't have access to the hs object. 

this is one thing i disliked about hs3, we had to do things like `dev.Update(hs)` to change any property on a deviceclass

**Comment by alexbk66** [comment]
> > In OOP it should really be just `dev.Update()`?
> 
> @alexbk66 , how would this work since the dev object probably doesn't have access to the hs object. 
> this is one thing i disliked about hs3, we had to do things like `dev.Update(hs)` to change any property on a deviceclass

That's exactly what I mean!  The device should know how to update itself.  It should encapsulate HS object internally. The's what I did for HS3: https://forums.homeseer.com/forum/developer-support/programming-plug-in-development/programming-with-homeseer/1289533-yet-another-hspi-plugin-library

**Comment by spudwebb** [comment]
> @spudwebb
> I hear you about the bug HS-1135 but i dont think that changes my suggestion. as we make changes to hsdevice/hsfeature objects, the changes will be collected in Changes, right?. So, we shouldn't need to build our own Changes collection
> 
> the call to UpdateDeviceByRef should uses the Changes in the collection internally

Yes the changes are collected in the Changes, so once this bug is fixed you would just have to call the following line and the changes will be saved without any exception raise and without the need to copy the Changes dictionary.

`HomeSeerSystem.UpdateDeviceByRef(dev.Ref, dev.Changes);`

As for encapsulating the hs object in HsFeature and HsDevice, the problem with that is that those classes are also use internally by HS, so when used there it does not make much sense to have an IHsController object in there.

**Comment by alexbk66** [comment]
> As for encapsulating the hs object in HsFeature and HsDevice, the problem with that is that those classes are also use internally by HS, so when used there it does not make much sense to have an IHsController object in there.

Well, then class derived from HsDevice

**Comment by mnsandler** [comment]
thanks for all the feedback. I will close this

**Comment by spudwebb** [comment]
HS-1135 is fixed in HS 4.1.14.0, now when you retrieve a HsFeature or HsDevice from HS (using for example GetFeatureByRef) the Changes dictionary is empty.

**Comment by mnsandler** [comment]
thanks for the update. So can now use the following without throwing exceptions?

`HomeSeerSystem.UpdateDeviceByRef(dev.Ref, dev.Changes);`


do you know what will happen if we make changes to the StatusControls or StatusGraphics? will they be added to the Changes collection? Thus we would still need to remove the following before using the above call

				ChangesCopy.Remove(EProperty.StatusControls)
				ChangesCopy.Remove(EProperty.StatusGraphics)

**Comment by spudwebb** [comment]
if you make changes to StatusControls or StatusGraphics they will still be added to the Changes dictionary, thus it will still throw an exception when you call UpdateFeatureByRef(feat.Ref, feat.Changes).
Basically you can't update StatusControls or StatusGraphics using UpdateFeatureByRef, you have to use the following methods instead:

```c#
        void AddStatusControlToFeature(int featRef, StatusControl statusControl);
        bool DeleteStatusControlByValue(int featRef, double value);
        void ClearStatusControlsByRef(int featRef);
        
        void AddStatusGraphicToFeature(int featRef, StatusGraphic statusGraphic);
        bool DeleteStatusGraphicByValue(int featRef, double value);
        void ClearStatusGraphicsByRef(int featRef);
```

I'm not sure of what is the rationale behind this so I will have to discuss this internally and get back to you.

**Comment by mnsandler** [comment]
once i call AddStatusControlToFeature or AddStatusGraphicToFeature, will the 'changes' be removed from the Dictionary?

if so, then there is no issue.

**Comment by spudwebb** [comment]
AddStatusControlToFeature  and AddStatusGraphicToFeature are in IHsController, so they do not change your local HsFeature object. So you have to call AddStatusControlToFeature/AddStatusGraphicToFeature  and then retrieve your HsFeature again using GetFeatureByRef if you want an up to date HsFeature object.

**Comment by mnsandler** [comment]
ok. makes sense. thanks
