### ISSUE TITLE
When label for the input field doesn't fit in one line

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#175]
When label for the input field doesn't fit in one line - it wraps on the second line which covers the input itself:

![image](https://user-images.githubusercontent.com/2533315/109378307-8c540700-7925-11eb-91b8-222423fb2399.png)

![image](https://user-images.githubusercontent.com/2533315/109378291-747c8300-7925-11eb-866f-1c059b9d7f66.png)

**Comment by spudwebb** [comment]
tracked as PSDK-139

**Comment by jldubz** [comment]
@alexbk66,

How do you imagine it looks when it is fixed? We can either elipse at a certain character count or pull the label text out and place it above in its own element.

**Comment by alexbk66** [comment]
@jldubz Both would work, but probably the second one is better, however I'm not sure how it will look?

**Comment by spudwebb** [comment]
This is fixed in HS 4.2.14.0, long labels now ellipse when they get too long.
