### ISSUE TITLE
devices.html seems to be reserved for hs4 use only

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#176]
i tried to create a devices.html file in my insteon plugin, thus the url would be insteon/devices.html. its not working

i believe i discussed this with @rjhdakota months ago

hs4 should be able to differentiate between devices.html in the root vs a subfolder

**Comment by alexbk66** [comment]
I call it my-devices.html

**Comment by rjhdakota** [comment]
> i tried to create a devices.html file in my insteon plugin, thus the url would be insteon/devices.html. its not working
> 
> i believe i discussed this with @rjhdakota months ago
> 
> hs4 should be able to differentiate between devices.html in the root vs a subfolder

I do agree that you should be able to use duplicate names. I will create an issue on this.

**Comment by spudwebb** [comment]
Tracked as HS-1147

**Comment by spudwebb** [comment]
This is fixed in HS version 4.1.15.0. Please test and reopen this issue if you still have problems.
