### ISSUE TITLE
UpdateFeatureByRef throws exception

### ISSUE THREAD

**Issue by dpmurphy** [HomeSeer/Plugin-SDK#177]
**Environment and System Config**
- OS: [Windows]
- Language: [C#]
- IDE: [VS2019]
- HomeSeer Version: [HS4 Pro Edition 4.1.14.0 (Windows)]
- PluginSDK Version: [v1.2.3]

**Describe the issue**
When you are trying to add StatusControls or StatusGraphics to an existing Feature, using the AbstractHSDevice.Changes cache and error is thrown.

**Steps to Reproduce**

This functions throws the error.

        public void AddOnOffToFeature()
        {
            EProperty[] toCopy = new EProperty[] { EProperty.StatusGraphics, EProperty.StatusControls };

            var changes = hsDevice.Changes
                          .Where(v => toCopy.Contains(v.Key))
                          .ToDictionary(v => v.Key, v => v.Value);

            var currentStatusGraphics = new StatusGraphicCollection();
            if (changes.ContainsKey(EProperty.StatusGraphics))
            {
                currentStatusGraphics = changes[EProperty.StatusGraphics] as StatusGraphicCollection ?? new StatusGraphicCollection();
            }

            //var button = new StatusControl(EControlType.Button) {
            //	TargetValue = 0,
            //	Label = "Off"
            //};

            var statusGraphic = new StatusGraphic("/images/HomeSeer/status/off.gif", 0, "OOff");
            currentStatusGraphics.Add(statusGraphic);

            if (changes.ContainsKey(EProperty.StatusGraphics))
            {
                changes[EProperty.StatusGraphics] = currentStatusGraphics;
            }
            else
            {
                changes.Add(EProperty.StatusGraphics, currentStatusGraphics);
            }
            Hs.UpdateFeatureByRef(RefId, changes);
        }

**Logs**
// HSCF.Communication.ScsServices.Communication.Messages.ScsRem oteException
// HResult = 0x80131500
// Message=Do not set StatusGraphics directly
// Source = mscorlib
// StackTrace:
// at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessag e(IMessage reqMsg, IMessage retMsg)
// at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(Mess ageData& msgData, Int32 type)
// at HomeSeer.PluginSdk.IHsController.UpdateFeatureByRef(Int32 featRef, Dictionary`2 changes)
// at HSPI_DMTemplate.DeviceBase.AddOnOffToFeature() in C:\Users\dmurphy\Documents\source\repos\HSPI_DMTemplate\HSPI _DMBase\Features\OnOffFeature.cs:line 133
// at HSPI_HS4Test.Controller.RunHomeseerCreateDeviceTest() in C:\Users\dmurphy\Documents\source\repos\hspi_hs4test\Control ler.cs:line 186
// at HSPI_HS4Test.Controller.DoControllerWork() in C:\Users\dmurphy\Documents\source\repos\hspi_hs4test\Control ler.cs:line 78
// at System.Threading.ExecutionContext.RunInternal(ExecutionConte xt executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
// at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
// at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
// at System.Threading.ThreadHelper.ThreadStart()

//Inner Exception 1:
//ArgumentException: Do not set StatusGraphics directly

**Additional info**
This functions works and updates the Feature Address.

        public void Test()
        {
            EProperty[] toCopy = new EProperty[] { EProperty.Address };

            var changes = hsDevice.Changes
                          .Where(v => toCopy.Contains(v.Key))
                          .ToDictionary(v => v.Key, v => v.Value);

            changes[EProperty.Address] = "ffffff";
            Hs.UpdateFeatureByRef(RefId, changes);
        }

**Comment by spudwebb** [comment]
You can't add/delete or update StatusControls or StatusGraphics direclty using UpdateFeatureByRef, you have to use the following methods instead:

```c#
        void AddStatusControlToFeature(int featRef, StatusControl statusControl);
        bool DeleteStatusControlByValue(int featRef, double value);
        void ClearStatusControlsByRef(int featRef);
        
        void AddStatusGraphicToFeature(int featRef, StatusGraphic statusGraphic);
        bool DeleteStatusGraphicByValue(int featRef, double value);
        void ClearStatusGraphicsByRef(int featRef);
```

**Comment by dpmurphy** [comment]
thanks for the update....It would save time if the exception thrown had a cref to one of these functions....

**Comment by spudwebb** [comment]
The doc for UpdateFeatureByRef has been updated:

https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.IHsController.html#HomeSeer_PluginSdk_IHsController_UpdateFeatureByRef_System_Int32_System_Collections_Generic_Dictionary_HomeSeer_PluginSdk_Devices_EProperty_System_Object__
