### ISSUE TITLE
Checking view ids and plugin ids for illegal characters in JS

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#178]
When generating HTML and JS for the views - should have checks for illegal characters in view ids and plugin ids.
Otherwise JS is broken if you have illegal characters (i.e. dots ".") - but it's not really obvious why it's not working until you open console in browser.

It's a huge time waster then:

https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-plugin-development/1461632-ondeviceconfigchange-is-not-getting-called

**Comment by spudwebb** [comment]
view id issue is tracked as PSDK-140

plugin id issue is tracked as HS-1150

**Comment by spudwebb** [comment]
Warnings have been added in HS version  4.1.16.0 (Plugin SDK version 1.2.5) see  https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_2_5_0.html
