### ISSUE TITLE
Error displaying device (1): A status graphic with that value set already exists

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#179]
User is getting an error:

Error displaying device (1) Bond Master Bed master bed fan.FanSpeed:A status graphic with that value set already exists Check with the owner of the plugin that created this device.

How can I troubleshoot?  Is it possible to output more info? I.e. value, graphic name, stack trace?

**Comment by spudwebb** [comment]
I guess we could add the status graphic value that is causing the problem in the error message, but the easiest way to troubleshoot this is to look at the Status/Graphics tab, it should be a similar problem as the ones we discussed here: https://github.com/HomeSeer/Plugin-SDK/issues/161#issuecomment-775406423

**Comment by alexbk66** [comment]
Another one:
https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/ak-ikea-alexbk66-aa/1462284-a-status-graphic-with-that-value-set-already-exists#post1462335

**Comment by alexbk66** [comment]
@spudwebb here's another user reporting, but there's no overlapping values https://forums.homeseer.com/forum/hs4-products/hs4-plugins/utilities-plug-ins-aa/aksmartdevice-alexbk66/1462847-status-graphics-issue-in-log

**Comment by alexbk66** [comment]
@spudwebb - it looks like a bug, not a "question"....

**Comment by spudwebb** [comment]
yes there is a known bug for some HS3 devices that have status only control ranges that do not match exactly their status graphics ranges. It is tracked as HS-1122. https://github.com/HomeSeer/Plugin-SDK/issues/161#issuecomment-779397916

**Comment by alexbk66** [comment]
@spudwebb These two are pretty urgent for me - until they are fixed - I can't release my AKSmartDevice (HS4 port)

**Comment by spudwebb** [comment]
Please test HS 4.1.15.0, this bug should be fixed.

**Comment by spudwebb** [comment]
> It looks like HS 4.1.15.0 only added more problem:
> https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/ak-ikea-alexbk66-aa/1462284-a-status-graphic-with-that-value-set-already-exists?p=1466237#post1466237

No, HS 4.1.15.0 did not add more problems. In this example it's a HS4 device that is misconfigured, there is 2 different StatusGraphics for the same value (i.e 100) so the warning is expected as HS4 can't decide which StatusGraphics to  use.

What version 4.1.15.0 fixed is the bug when you had a HS3 device without overlapping values but the warning still appeared, like in this example:
https://forums.homeseer.com/forum/hs4-products/hs4-plugins/utilities-plug-ins-aa/aksmartdevice-alexbk66/1462847-status-graphics-issue-in-log

**Comment by alexbk66** [comment]
Bit the user says that he started getting the errors after HS 4.1.15.0 update?  Or he's wrong and simply didn't notice before?

**Comment by spudwebb** [comment]
either he didn't notice the warnings before, or he wasn't on HS 4.1.14.0 which is the version where the warnings started to show up in the logs because of a change we made.
