### ISSUE TITLE
Request for info: Use HS3 & HS4 triggers/actions

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#18]
Rich asked me to post this here so @jldubz can chime in.

I'm currently working on implementing the code (as per the example) for triggers and actions. Have to admit, not easier compared to HS3 but that's besides the point.

In HS3, I believe the proposed code was to use a class called "trigger" which was inherited HSCollection. In HS4, it is AbstractTriggerType. While I'm wrestling my way through using this new methodology, I can't really see how we would seamlessly migrate from HS3 to HS4 and keep all settings, including event info.

Rich care to weigh in? What really gives me pause is that when I use my HS3 PI under HS4, the functions (and UI) to create events is working really well, so I ask: "why don't I keep that code exactly as is"? Is there a downside?

I need to point out that my events have some complexity to it, depending on which trigger you select, the additional parameters will be different, so there is some coding involved to make it all work properly, which in all fairness is all supported through a bunch of methods. However, it would be great if the documentation can be enhanced with descriptions of the exact purpose of the methods and more importantly the sequence in which they are typically called. I always start a new project with instrumenting call to all methods and so far, I haven't clearly seen the flow of calls to the methods, in fact I see calls to methods like new, at high rates, not sure what that's all about.

Thanks for adding some insight.

Dirk

**Comment by jldubz** [comment]
Apologies for the slim documentation; definitely high on the to-do list all around.

Let's start with an outline of the order of operations that occurs whenever the system interacts with an action or trigger of a type that is defined by your plugin.

### For a trigger:
1. Trigger instance created from empty Data
2. OnNewTrigger is called
3. BuildUI is called to pull the UI from the ConfigPage
4. Trigger instance created from Data
5. IsFullyConfigured is called and returns FALSE
6. User updates something...
7. Trigger instance created from Data
8. OnEditTrigger is called
9. OnConfigItemUpdate is called for each view changed
10. Trigger Saved to HS
11. Trigger instance created from data
12. Repeat from step 3 until IsFullyConfigured is TRUE
13. Trigger instance created from data
14. GetPrettyString is called for the formatted text

At step 3, a new instance is created and run through the initialization process to extract the config page from DataIn.  This is why you are seeing all of the calls to `.New`  This process used to be somewhat manual in HsCollection, but the new structure does, essentially, the same thing.  All of the old methods are still there, implemented in AbstractPlugin - [Trigger methods](https://github.com/HomeSeer/Plugin-SDK/blob/2eb43081b97ed12aea60cf75dc03fbca871361b7/AbstractPlugin.cs#L564) like TriggerBuildUI and TriggerProcessPostUI.  You can trace those calls through the [TriggerTypeCollection](https://github.com/HomeSeer/Plugin-SDK/blob/master/Events/TriggerTypeCollection.cs) to the [AbstractTriggerType](https://github.com/HomeSeer/Plugin-SDK/blob/master/Events/AbstractTriggerType.cs)

I'll work on documenting some of this process a bit more for you.

**Comment by jldubz** [comment]
Have you taken a look at the example in the VB sample plugin? [SampleTriggerType.vb](https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/SampleTriggerType.vb) and [WriteLogSampleActionType.vb](https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/WriteLogSampleActionType.vb)

You're right that `.OnNewAction` should not be being called that many times during the normal workflow configuring an action.  If we look at the code in [AbstractActionType.InflateActionFromData](https://github.com/HomeSeer/Plugin-SDK/blob/master/Events/AbstractActionType.cs#L300) `.OnNewAction()` is called when the incoming data is empty, indicating that the ConfigPage is Nothing and that no configuration has occurred yet.

Once `.OnNewAction()` completes, the `ConfigPage` should be initialized to the starting state for configuration. (which it looks like you are doing) When you select anything in a select list or press the save button in the UI, `.OnConfigItemUpdate()` is called with the delta to process so you can add more fields or do whatever you need to do to move the configuration forward.  Return `True` to make sure that the change is saved to the `ConfigPage`.

A good example of this process can be seen in the [WriteLogSamplePlugin.OnConfigItemUpdate() implementation](https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/WriteLogSampleActionType.vb#L114)

```
 Protected Overrides Function OnConfigItemUpdate(ByVal configViewChange As AbstractView) As Boolean
        If configViewChange.Id <> LogTypeSelectListId Then
            'When the ID being changed is not the log type select list, always save and continue.
            ' No more configuration is needed
            Return True
        End If

        'Log Type selection change
        
        Dim changedLogTypeSl As SelectListView = TryCast(configViewChange, SelectListView)
        'Make sure the change is to a select list view
        If changedLogTypeSl Is Nothing Then
            Return False
        End If

        
        Dim currentLogTypeSl As SelectListView = TryCast(ConfigPage.GetViewById(LogTypeSelectListId), SelectListView)
        'Make sure the target select list view casts correctly
        If currentLogTypeSl Is Nothing Then
            Return False
        End If

        If currentLogTypeSl.Selection = changedLogTypeSl.Selection Then
            'If the selection didn't change then return false because the user may still need to supply a message
            Return False
        End If

        'Initialize the new state of the page so it asks for a message
        Dim newConfPage = InitConfigPageWithInput()
        ConfigPage = newConfPage.Page
        'Save the change to the log type select list
        Return True
    End Function
```

**Comment by dcorsus** [comment]
SampleTriggerType.vb and WriteLogSampleActionType.vb AND the Netcam PI are all my bible!

Late last night I managed to get my action code migrated and (at least) one action is working. 
So extensive testing today.

The big breakthrough was that I removed code that would rebuilt the config page each time OnConfigItemUpdate was called, I seemed to have caused a bunch of strange behavior and plenty of errors doing it this way. However, if you think of my flow as a tree, depending on what selection you take at the root of the tree, the leafs will be quite different, which means that I need to be able to reconstructs the views on the config page. Doing this in the OnConfigItemUpdate, which is called before the view change that triggered it can be tricky. I think for example that you cannot remove the view that caused the trigger as it will cause an error. 
No action needed from you now, I'll either close it or add more specific issues.

**Comment by jldubz** [comment]
Add the lifecycle outline from this issue to https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.Events.AbstractActionType.html?tabs=cs and https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.Events.AbstractTriggerType.html?tabs=cs respectively.
