### ISSUE TITLE
Looks like devices.html works when only one plugin adds a tab [URGENT]

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#181]
I click on second plugin tab - it only shows spinning wheel. 
Then I click on **first** plugin tab - it briefly shows the **second** plugin HTML, then updates with the first one:
![HS4Bug](https://user-images.githubusercontent.com/2533315/111146970-22528780-85de-11eb-9780-b7e5bce72783.gif)

Possibly caused by both sharing same div ID?

![image](https://user-images.githubusercontent.com/2533315/111148835-38614780-85e0-11eb-9d10-cbfd698e95c0.png)

**Comment by spudwebb** [comment]
tracked as HS-1155

**Comment by alexbk66** [comment]
@spudwebb These two are pretty urgent for me - until they are fixed - I can't release my AKSmartDevice (HS4 port)

**Comment by rjhdakota** [comment]
I put in a fix for this. The fix will be in build 4.1.15.0.
