### ISSUE TITLE
How do I add Input view in the Device Configuration Pages?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#182]
All other views (i.e. toggle, select list) use actions to trigger postback, but what do I do for input field?

BTW, I like your documentation on [Device Configuration Pages](https://docs.homeseer.com/display/HSPI/Device+Configuration+Pages) (created Nov 01, 2019)

[EDIT]
I guess I've got the name wrong - it's Feature Page (i.e. HTML)

**Comment by spudwebb** [comment]
According to this forum thread, it looks like you found a solution
https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-plugin-development/1463768-how-to-add-text-input-to-feature-page-html

so I'm closing this issue

**Comment by alexbk66** [comment]
Yes I did find a "solution". But it's a pain. In HS3 we had all these controls implemented.
