### ISSUE TITLE
IHsController equivalent of hs.CAPIGetSingleControlByUse

### ISSUE THREAD

**Issue by tenholde** [HomeSeer/Plugin-SDK#185]
How do I get the StatusControl for ControlUse = _On without scanning all StatuControls for a device?

In HS3 (IHSApplication or hsapplication) you could just use hs.CAPIGetSingleControlByUse(174, HomeSeerAPI.ePairControlUse._On)

**Comment by tenholde** [comment]
bump

**Comment by jldubz** [comment]
Will add:
* HasControlForUse
* GetControlForUse

Tracking internally as PSDK-264 for v1.5

**Comment by tenholde** [comment]
Thank you!
