### ISSUE TITLE
Installing plugin: The type initializer for 'PluginLib.PluginBase' threw an exception

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#186]
When installing AKTraccar I get the following exception:
 
> Error, Creating plugin instance: HSPI_AKTraccar.exe->Exception has been thrown by the target of an invocation.->The type initializer for 'PluginLib.PluginBase' threw an exception. 

Would be nice to have more info about the exception. Just "threw an exception" doesn't help at all.

**Comment by spudwebb** [comment]
When I try to install AKTraccar , I get a "Object reference not set to an instance of an object" exception from the PluginLib.PluginBase constructor

![image](https://user-images.githubusercontent.com/5427056/112882450-feda1300-909a-11eb-89c3-e2e3058a9f07.png)

**Comment by alexbk66** [comment]
I know that, but problem is - the Ctor is empty.  Also, I can start the plugin manually, it bombs out on RegisterPlugin().

![image](https://user-images.githubusercontent.com/2533315/112913854-5c776980-9146-11eb-93d8-c4e29683cf27.png)
![image](https://user-images.githubusercontent.com/2533315/112913900-74e78400-9146-11eb-89c4-c68d052df17b.png)

**Comment by alexbk66** [comment]
The problem only happens on **Linux**, and only during **install**.

The error is "The **type initializer** for 'PluginLib.PluginBase' threw an exception" - not the the "PluginLib.PluginBase" itself.  Which usually is caused by .NET/Mono issues, but I have no idea what?  Especially if the exe can be started manually...

**Comment by alexbk66** [comment]
What are callstacks for the inner and outer exceptions?

**Comment by spudwebb** [comment]
The problem does not only happen on Linux, I can reproduce it on Windows.
The call that triggers the exception is:

`objtemp = objAssembly.CreateInstance("HSPI_AKTraccar.HSPI", False, Reflection.BindingFlags.CreateInstance, Nothing, Nothing, Nothing, Nothing)`

This is after installation when HS tries to create an instance of your HSPI class to get the ID and Name of the plugin

The inner stack trace is:
at PluginLib.PluginBase..ctor()" & vbCrLf & "   at HSPI_AKTraccar.HSPI..ctor()

The outer stack trace is 
at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)" & vbCrLf & "   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)" & vbCrLf & "   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)" & vbCrLf & "   at System.Activator.CreateInstance(Type type, Boolean nonPublic)" & vbCrLf & "   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)" & vbCrLf & "   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)" & vbCrLf & "   at System.Reflection.Assembly.CreateInstance(String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)" & vbCrLf & "   at Scheduler.clsHSPI.Worker.LoadClassByName(String vstrAssemblyName, String vstrClassName, Object[] vArgs, Boolean& IsSerialized)

**Comment by alexbk66** [comment]
Interesting, it happens with all my plugins if I uninstall it first

**Comment by alexbk66** [comment]
Something really weird - when installing other plugins - I get the exception in HSPI_AKSmartDevice?

![image](https://user-images.githubusercontent.com/2533315/113009532-c2ee9d00-91c3-11eb-8edc-6aabe26f94a0.png)

**Comment by spudwebb** [comment]
I noticed that too, I have to investigate more, somehow when you are installing a plugin HS4 re-scan all installed plugins to get their name and ids.

Here is the VB code that causes the exceptions to be thrown.

               Dim objAssembly As Reflection.Assembly
               Dim objtemp As Object
                Dim fs As FileStream
                fs = New FileStream(FixPath(gpath & "\" & vstrAssemblyName), FileMode.Open, FileAccess.Read, FileShare.ReadWrite)    ' setting fileshare allows us to open the file even if its already open
                Dim br As BinaryReader = New BinaryReader(fs)
                Dim bin As Byte() = br.ReadBytes(Convert.ToInt32(fs.Length))
                fs.Close()
                br.Close()

                objAssembly = AppDomain.CurrentDomain.Load(bin)

                objtemp = objAssembly.CreateInstance("HSPI_AKTraccar.HSPI", False, Reflection.BindingFlags.CreateInstance, Nothing, Nothing, Nothing, Nothing)

**Comment by alexbk66** [comment]
I noticed in HS3 too - when you install a plugin - HS rescans all plugins.  The way I noticed - I enabled .NET assembly loader tracer FUSLOGVW.EXE

**Comment by alexbk66** [comment]
This also happens on HS startup

**Comment by alexbk66** [comment]
The exception is thrown from `objAssembly.CreateInstance` - which internally does
`Type loadedType = objAssembly.GetType(type);
obj = Activator.CreateInstance(loadedType);
`
Since it can't find the type - "loadedType" is null - that's what it complains about

The exception thrown should be ReflectionTypeLoadException type and should also contain "LoaderExceptions" list

**Comment by spudwebb** [comment]
can I close this?

**Comment by alexbk66** [comment]
Sure, thank you.

BWT, instead of the code you pasted above you could just use `byte[] ba = File.ReadAllBytes(path);`
And there's AppDomain function to create instance directly
```
string assName = AssemblyName.GetAssemblyName(path).FullName;
ObjectHandle oh = AppDomain.CurrentDomain.CreateInstance(assName, ""HSPI_AKTraccar.HSPI"");
```
