### ISSUE TITLE
can the plugin_function html tag return a list(of someclass)

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#188]
I'm trying to return an array where each element is a groupinfoclass class. see below

i have the following in my html page
        {{list=plugin_function 'Insteon' 'grouplist' [Nothing]}}

my grouplist function is being called, i can see the expected result array but the result isn't being returned to html; the html never renders. the browser just spins

i see the following in the hs log
**Error while executing PluginFunction grouplist with 1 parameters**

**what are the limits of what can be returned by a function to the tag?** 

```
	<Serializable> Public Class groupinfoclass

		Public name As String
		Public number As String
		Public controller As String
		Public numparticipants As String
```

**Comment by rjhdakota** [comment]
The tamplate language does not know what "Nothing" is, so try this:

{{list=plugin_function 'Insteon' 'grouplist' []}}

plugin_function accepts an object as return, so you should be able to return any type.

**Comment by mnsandler** [comment]
@rjhdakota 
the input value of Nothing isn't the problem (it does work), and [ ] doesn't work; you must put something between the braces.

My problem is that the plugin_function call never returns; the browser status bar at the bottom says 'Waiting for server..."

the scriban array variable, **list**, seems to only allow a 1-dimentional array

I need to be about to return an array (of class) so i can build an html table dynamically

**Comment by rjhdakota** [comment]
Can you try it with a return of a string just to see if the return value is the problem? What is the exact error message in the HS log?

**Comment by mnsandler** [comment]
@rjhdakota 
i know a return type of string, and a return type of a string array work; already tested.

here is the error message if i kill the plugin process while the browser is waiting for the response

**Error while executing PluginFunction grouplist2 with 1 parameters - Disconnected before response received.**

in vs debug mode, i can see the function execute correctly and exit

**Comment by rjhdakota** [comment]
Just to make sure your code flow is ok, can you change the grouplist to a simple string or array of strings. I think the problem is with the serialization over the plugin API. Scriban does not know what the groulist class is so the serialization is failing. If a simple string array works, you will need to use standard .net classes in your array.

**Comment by mnsandler** [comment]
thanks @rjhdakota , but i need something more complex than a 1-dimensional string array.

i want to build a collection of values in my plugin to pass to the html but this is a real limitation in scriban.

i am trying the recommended approach of separating code from UI. I want to build an html table of my devices in the UI with the following scriban code (see below). this seems to be the ideal solution

**what are my other options?**

```
            {{for item in list}}
                <tr>
                    <td></td>
                    <td>{{item.name}}</td>
                    <td align="center">{{item.location}}</td>
                    <td>{{item.controller}}</td>
                    <td>{{item.numparticipants}}</td>
                </tr>
            {{end}}
```

**Comment by rjhdakota** [comment]
Could use a collection? Each entry has a key and the key can be the name of the entry. Collections just have a key and an object so that would be portable.

**Comment by spudwebb** [comment]
@mnsandler , it works fine with simple Serializable classes, see for example  GetTriggerOption in the sample plugin:
https://github.com/HomeSeer/Sample-Plugin-CS/blob/7091765fc08dffb2b02ffbbae8fd35a488dfa2fa/HSPI.cs#L447-L454

but I found some caveats with the way Scriban deserialize things. Your class (groupinfoclass) needs to be defined in the main plugin exe it can't defined in a dll in bin/Insteon. Also all the fields need to be serializable, I think I remember even private fields causing problems. Can you post your entire groupinfoclass, and  the grouplist function?

**Comment by mnsandler** [comment]
below is the HTML, and the CODE. the function grouplist is being called.
HTML
```
        {{list=plugin_function 'Insteon' 'grouplist' ['']}}

        <table border="1" cellpadding="3">
            <tr>
                <th>Mark</th>
                <th>Group Name</th>
                <th>Group Number</th>
                <th>Controller</th>
                <th>Participants</th>
            </tr>

            {{for item in list}}
                <tr>
                    <td></td>
                    <td>{{item.name}}</td>
                    <td align="center">{{item.location}}</td>
                    <td>{{item.name}}</td>
                    <td>{{item.name}}</td>
                </tr>
            {{end}}

        </table>
```


CODE - this exists within the HSPI class. i can debu the function and see the successful exit.

I just tried this based on an example i saw in the forum...still no joy

```
    Public Function grouplist(param As Object) As IEnumerable(Of Object)

        Dim GrpIndex As Integer

        Dim tmp As New List(Of testitem)

        For GrpIndex = 1 To gNumGroups
            tmp.Add(New testitem With {.name = gGroup(GrpIndex).name, .location = "test"})
        Next

        Return tmp
    End Function

    <Serializable> Public Class testitem
        Public name As String
        Public location As String
    End Class
```

**Comment by spudwebb** [comment]
IEnumerable(Of Object) won't work, try to return a List of testitem instead, like in the example from the sample plugin

**Comment by mnsandler** [comment]
@spudwebb , i changed the function to the following but still no joy. the browser just spins waiting for HS

`    Public Function grouplist(param As String) As List(Of testitem)`

other ideas?

**Comment by spudwebb** [comment]
When you test do you have the plugin exe in the HomeSeer root dir?

**Comment by mnsandler** [comment]
Well that did it. I put a current copy of my exe in the hs root and got the expected results immediately

![image](https://user-images.githubusercontent.com/67801043/112902073-99dee700-90b3-11eb-960c-ec8356a1deca.png)

**Can you please add this requirement to the following page**

https://docs.homeseer.com/display/HSPI/Feature+Pages

**Comment by mnsandler** [comment]
@spudwebb @rjhdakota if I need a current copy of my plugin exe in the hs root folder, what can i do to have hs release the current exe file so i can overwrite it?

even if the plugin is disabled, hs still has a lock on it so it can't be overwritten. this has been an on going issue

**Comment by spudwebb** [comment]
> @spudwebb @rjhdakota if I need a current copy of my plugin exe in the hs root folder, what can i do to have hs release the current exe file so i can overwrite it?
> 
> even if the plugin is disabled, hs still has a lock on it so it can't be overwritten. this has been an on going issue

you're right hs keeps a lock on the plugin even if you disabled it, it's a known problem for which we didn't find any good solution yet. But note that while developing and testing from visual studio you only have to update your plugin exe in the hs root folder if you made some changes to your serializable class.

**Comment by spudwebb** [comment]
I have added an example with a Serializable class in the documentation: https://docs.homeseer.com/display/HSPI/Feature+Pages
