### ISSUE TITLE
Homeseer 4 GUI Hacks

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#189]
May you consider adding these to HS4, instead of users having to hack your html, please
https://www.domoticaworld.com/scripts/homeseer-4-gui-hacks/
https://www.domoticaworld.com/scripts/homeseer-4-gui-hacks-part-2/

**Comment by spudwebb** [comment]
Please log these kind of requests in the service desk, this github place should be reserved for PluginSdk issues, or at least issues related to plugin development.
