### ISSUE TITLE
Can't delete feature device without parent

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#191]
I have a child without parent, so on HS startup I get warning
![image](https://user-images.githubusercontent.com/2533315/113136535-36011d80-926f-11eb-8fb2-50b9851123d6.png)
But it's impossible to delete the device - because it doesn't show in the list.
Also, list of Locations includes "Shelly" because of that, even if it doesn't show any "Shelly" devices.

**Comment by jldubz** [comment]
@alexbk66,

Can you delete it from the devices.json file? 

How did this feature get orphaned?

**Comment by alexbk66** [comment]
@jldubz I can't dlete it from devices.json because it's been a year since I opened the ticket.  And I have no idea how it happened.

**Comment by jldubz** [comment]
@alexbk66,

Would you like me to try and trace this with you now? Or is it gone and we should close the ticket?

**Comment by alexbk66** [comment]
It's gone, so I close the ticket
