### ISSUE TITLE
Setting Longitude save negated value

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#193]
![image](https://user-images.githubusercontent.com/2533315/115174071-e98d5d00-a10b-11eb-90ac-13c56c3496c3.png)

**Comment by spudwebb** [comment]
There was a bug in HS3 where all longitude values were reversed, this was then fixed bu the longitude value was kept reversed in settings.ini to keep backward compatibility with plugins using it.
So if you read the longitude from settings.ini, you need to negate the value read.

**Comment by alexbk66** [comment]
> So if you read the longitude from settings.ini, you need to negate the value read

Sounds funny :)
