### ISSUE TITLE
Did we remove the params from PluginPropertyGet in version 4.1.0.16/SDK1.2.5??

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#196]
**Environment and System Config**
- OS: [Windows]
- Language: [VB]
- IDE: [VS2019]
- HomeSeer Version: [v4.1.0.16]
- PluginSDK Version: [v1.2.5]

I just upgrade my HS version to V4.1.0.16 and have an error on PlugInProperyGet. I noticed the params() was dropped from it???
Why? Now my PI is broken and I actually use to make sure that the propertyget function gets to the right instance of media objects. First we had a multipleinstancesingeEXE in HS3, then we dropped it so I had to rewrite good chunks of the PI but the fundamental principle that each player is an object stayed and I NEED that parameter. Can you undo what you did????

**Comment by spudwebb** [comment]
params was removed from  IPlugin.PluginPropertyGet  because its actual implementation in  AbstractPlugin was never using this parameter in its body

```c#
        public object PluginPropertyGet(string propName, object[] @params) {
            try {
                var ty = GetType();
                var mi = ty.GetProperty(propName);
                return mi == null ? null : mi.GetValue(this, null);
            }
            catch (Exception exception) {
                if (LogDebug) {
                    Console.WriteLine(exception.Message);
                }
            }

            return null;
        }
```

Don't you use AbstractPlugin as the base class of your HSPI class? Have you reimplemented PluginPropertyGet in your own HSPI class?
I'm not sure to understand  how you are using PluginPropertyGet ? Please explain how and from where you are calling it?

**Comment by dcorsus** [comment]
Have to admit I'm confused. I had this from day one

Public Overloads Function PluginPropertyGet(ByVal proc As String, parms() As Object) As Object Implements HomeSeer.PluginSdk.IPlugin.PluginPropertyGet

and now the PI doesn't start and if I remove the parms() my html pages are broken in about 20 places.

**Comment by spudwebb** [comment]
So if I understand this correctly you were using your own overloaded version of PluginPropertyGet to get some objects of your plugin from html pages like this:

{{ value=plugin_property_get 'MyPluginId' 'MyProperty' [MyParam] }}
?

Yes, it was removed to clean up the code, and we didn't think anyone had overloaded this method.
I think you should use plugin_function instead of plugin_property_get to do what you want and pass parameters. I will bring this up internally for discussion though.

**Comment by alexbk66** [comment]
> it was removed to clean up the code, and we didn't think anyone had overloaded this method

That's the whole problem - you forget that the SDK is for developers - and before removing some interface function I think you could consult the developers.  I hear it too often "we didn't think anyone use it".

**Comment by spudwebb** [comment]
> Well if I use plugin_function, now I have to rewrite the PI significantly turning properties into functions, which for many of these things would make no sense. For example: artist is a property that gets referred to in the PI perhaps in 30~40 places, it makes no sense to turn that into a function for reading and writing.

You could rename you current PluginPropertyGet implementation into your own MyPluginPropertyGet function that does not hide any of the AbstractPlugin method, and then use that with plugin_function to get your properties as before.

 {{ value=plugin_function 'MyPluginId' 'MyPluginPropertyGet' [MyProperty, MyParam] }}

**Comment by dcorsus** [comment]
As I wrote, I can solve it in other ways, the point is, is this affecting more PI authors and a matter of time you undo it, rather then having me spend useless effort for a change that wasn't needed on the first place.
Judging from the response,  it appears there is no plan to undo this, so I am stuck with the effort.

**Comment by dcorsus** [comment]
Well I'm thoroughly confused now. Assuming you guys were not going to undo this cosmetic clean up, I first fixed my PI because it wouldn't run (removing the params), then I started to change the 50 or so place in my html files to error out again.
Whatever is used for scriban for plugin_property_get still seems to expect the 3rd parameter you just removed from the SDK ???
Here's the error;

5/7/2021 7:08:15 PM
HomeSeer
Warning
Problem parsing HTML: (158,68) : error : Invalid number of arguments `2` passed to `plugin_property_get Sonos4 UseDirectNavigation:udn` while expecting `3` arguments

**Comment by jldubz** [comment]
@dcorsus
Our plugin samples never demonstrated the use of `plugin_property_get` or `plugin_property_set` and as such they weren't removed. They never existed to begin with.

> This is being tracked by HS-1235 and is scheduled for 4.1.17.0. It will be deprecated and you will receive a warning when implementing it.

`plugin_property_get` or `plugin_property_set` are being deprecated -  removed, not changed - because we determined there was no need for them moving forward. Their use is handled elsewhere in a more appropriate way. The full assessment of this decision is listed in my previous comment.

Other changes, with more risk of breaking common plugin functionality, are being addressed more slowly. You can see this in the [latest release notes](https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_2_5_0.html) discussing our roadmap on changes to plugin IDs and JUI view IDs.

> The existence of certain special characters in plugin IDs is causing undesired behavior. This includes previously accepted characters like '_' (underscores). **We will be updating the list of restricted characters over time to ensure that all plugins can shift if needed.** We understand that this is not easy to handle if your plugin manages devices or events, and we are working on additional tools for you to use if you do need to make changes to your IDs. This change starts with warnings written to the HS logs if a special character is detected in a plugin ID only while in developer mode. **At a future date, this will change to stop plugins from running if they are using a special character in their ID.**

It sounds like this issue is resolved now. Can I close this ticket?

**Comment by dcorsus** [comment]
Let me be very clear, I didn't sit around and figure out there was something like a plugin_property_get, I was pointed in that direction either by your team or by your html files.
So if you assume that I will spend all the effort and HS none, you can consider this ticket closed. Can I vote somewhere on the satification I got?

**Comment by jldubz** [comment]
I apologize for miscommunication. I empathize with your frustration. It is unnecessary and unproductive to be taking it out on me in this way.

**Comment by jldubz** [comment]
@dcorsus,
You are correct. I do represent HS. I do not want to make it seem like we are not interested in dialog. Thank you for your honesty and your clarification. I would like to keep this dialog going. Can I ask you to email me at jonluke@homeseer.com and give me an idea of what your pain points are?

**Comment by alexbk66** [comment]
I must agree with @dcorsus 100% - HST attitude towards developers is simply unacceptable.

But I must admit that @jldubz and @spudwebb are (only) two guys who actually respond an respectful way and actually try to improve things.

And the rest of HST is totally arrogant and not productive.  May be except also Tyler.

**Comment by dcorsus** [comment]
Agree w Alex, you guys are always on the ball, if it wasn't for you guys, I would have dumped all of this a year or two ago. I suspect you might actually be the only two active developers by now and that is a major concern. I can understand that the business may not support having more developers but a platform like HomeSeer needs more. I had offered in the past, to help out for free but that might not have been realistic either. One way or another, I sense death by 1000 paper-cuts or some radical rethinking of the business is seriously needed.
It was a hope that other developers would pitch in on the SDK but without having access to the underlying HS code, I never really saw an opportunity to contribute, maybe I'm too myopic and there is something that can be done, I just don't see it, but feel free to ask or set me straight.

**Comment by alexbk66** [comment]
> without having access to the underlying HS code

I must admit I did look at Z-Wave plugin code (when working on AKHeatmiser plugin and for three months trying to findout from Rich how to configure the devices so they appear in HSTouch) - it's total mess, so I'm not surprised that in two years they can't port it to HS4

**Comment by dcorsus** [comment]
Maybe not the right place to discuss this, but ironically enough, I offerred to work on HSTouch a few years back to get the MediaAPI functions straightened out. Sure @spudwebb recalls our conversations back then. I get it that it made Rich very uncomfortable but looking back, could things have been worse if perhaps a select group of developers were allowed access to certain parts of the code to pitch in. Just say'in
