### ISSUE TITLE
PageFactory.WithTextArea?

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#197]
**Environment and System Config**
- OS: Windows
- Language: VB
- IDE: VS2019
- HomeSeer Version: v4.1.16.0
- PluginSDK Version: v1.2.5

**Describe the issue you are encountering**
I am unable to create a text area input for an event action (like the "Message" input when creating a "Send an email" action)

**Steps to Reproduce**
I looked at all the available PageFactory.With... functions, but I cannot find anything to create a textarea input. WithInput seems to support just for a single line.

**Expected behavior**
I like to stick to the HS4 layout as much as possible (also for rendering on mobile and other devices) but I can't seem to find a control to define a text area. Since there is standard functionality in the HS4 event actions (Send an email) that does support a text area, I am wondering what I am missing.

-----

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/20107364/116912787-fa2fee00-ac48-11eb-8586-679da6e38a73.png)

**Logs**
None

**Additional info**
None

**Comment by spudwebb** [comment]
I don't think your are missing anything, we don't have a JUI view for a TextArea element (HS4 native triggers and actions do not use JUI views for their configuration).
I created a feature request for a new TextAreaView to be added to the PluginSdk  PSDK-151

**Comment by stefxx** [comment]
Great, thanks! That would really help with my plugin.

**Comment by stefxx** [comment]
Thanks for implementing!

**Comment by spudwebb** [comment]
TextAreaView is available in PluginSdk 1.3.0.0
