### ISSUE TITLE
What is the equivalent for DeleteIODevices

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#2]
I use this function in HS3 to "clean" up all devices that might have been stranded after a user erroneously deleted or made changes to my .ini file settings.
Jon provided this code but was going to check whether it also properly cleans up features and asked to raise an issue here.

var deviceRefs = HomeSeerSystem.GetRefsByInterface(Name);
foreach (var devRef in deviceRefs) {
    if (HomeSeerSystem.IsRefDevice(devRef)) {
        HomeSeerSystem.DeleteDevice(devRef);
        continue;
    }

    HomeSeerSystem.DeleteFeature(devRef);
}

**Comment by jldubz** [comment]
See [commit 44471c8](https://github.com/HomeSeer/Plugin-SDK/commit/44471c844234bd05b783ee984043a3f7b7f46e28) in the dev branch for the upcoming changes.  Please keep in mind that the dev branch will not work with the current HS4 version.  A new installer with these changes will be published Thursday.

**Comment by dcorsus** [comment]
Thanks Jon. I did implement/use the code you provided and I can confirm it works. If you put that behind a single method, even better but for now, I have what I needed.

**Comment by jldubz** [comment]
This is now available as of v1.0.5
