### ISSUE TITLE
PlugExtraData throws error (It shouldn't!! in this case)

### ISSUE THREAD

**Issue by dpmurphy** [HomeSeer/Plugin-SDK#200]
**Environment and System Config**
- OS: [Windows]
- Language: [C#]
- IDE: [VS2019]
- HomeSeer Version: [HS4 Pro Edition 4.1.16.0]
- PluginSDK Version: [v1.2.5]

Storing string "2.3" in PED will result in "2.3" being returned.

HOWEVER storing "2.3.2" in PED will throw exception.

Minimum code to reproduce..... Create an new device (no ped data).....then

Dictionary<string, string> changes = new Dictionary<string, string>();
changes.Add("libver", "2.3");
changes.Add("libver1", "2.3.2");

PlugExtraData ped = dev.PlugExtraData;

foreach (KeyValuePair<string, string> change in changes) {
       ped.AddNamed(change.Key, change.Value);
}

Hs.UpdatePropertyByRef(refId, EProperty.PlugExtraData, ped);

AbstractHsDevice updatedDev = Hs.GetDeviceByRef(refId);
PlugExtraData updatedPed = updatedDev.PlugExtraData;

string libver = updatedPed.GetNamed<string>("libver"); //This works returns "2.3" as expected.
string libver1 = updatedPed.GetNamed<string>("libver1"); // This throws exception previously noted....I'm using strings not numbers....

**Expected behavior**
sdk should return what was stored in HS (ped) and not throw exception.

I believe this may also fail - changes.Add("sketch", "Kitchen Monitor");

**Additional info**
https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-programming/1474083-plugextradata-errors-retreiving-some-data-no-issues-setting-data#post1474203

**Comment by spudwebb** [comment]
This problem is now tracked as PSDK-153.

That being said for strings you should use the direct indexer to set and get the values in ped:
ped[change.Key] = change.Value;

string libver = updatedPed["libver"];

**Comment by dpmurphy** [comment]
thanks.......

**Comment by alexbk66** [comment]
As I explained here https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-programming/1474083-plugextradata-errors-retreiving-some-data-no-issues-setting-data?p=1474203#post1474203 it's caused by GetNamed() stripping qoutes from stored json string.

**Comment by zbourdeau** [comment]
Any movement on this? This is a blatant bug and impacts basic property storage for plugins. Please fix this!
