### ISSUE TITLE
SelectListViews - GetSelectedOptions

### ISSUE THREAD

**Issue by dpmurphy** [HomeSeer/Plugin-SDK#201]
**Environment and System Config**
- OS: [Windows, Linux, Mac, etc]
- Language: [C#]
- IDE: [VS2019]
- HomeSeer Version: [4.1.16.0]
- PluginSDK Version: [v1.2.5]

**Describe the issue**
GetSelectedOption() - is documented as returning the Text of the selected options, in fact it returns the index of the selected option as text. 

**Steps to Reproduce**
			foreach (AbstractView view in deviceConfigPage.Views) {
				if (view.Id == "ConfigSelector") {
					SelectListView v = view as SelectListView;
					if (v != null) {
						string val = v.GetSelectedOption();
						

val is "1" and not "Imperial" as expected.

**Expected behavior**
val is "1" and not "Imperial" as expected.

How do I get the text....

/// <summary>
/// Get the currently selected option text.
// </summary>
/// <returns>The text of the option at the index specified by <see cref="Selection"/>.</returns>
public string GetSelectedOption() {

There are multiple ways to get the index of selected options, I haven't found one that returns the text of the selected option.

**Comment by alexbk66** [comment]
Yeah, that's pretty ugly. To get the selected value you need two views - original and "changed".  Changed view contains as you noticed only the selected index as string, Then you use this index to get the value from "original" view

```
/// <summary>
/// Helper for updaing SelectListView mapping
/// </summary>
/// <param name="currentView"></param>
/// <param name="changedView"></param>
void UpdateSelect(SelectListView currentView, SelectListView changedView)
{
    // changedView contains just numers (as strings)
    // get the string from original view
    // i.e. "3"
    string selected = changedView.Options[changedView.Selection];
    // base
    UpdateSelect(currentView, selected);
}
```

**Comment by dpmurphy** [comment]
Here's hoping they fix the sdk.....we shouldn't need everybody writing helpers independently for functionality that should exist. Are you modifying the sdk or layering a wrapper around sdk?

**Comment by alexbk66** [comment]
I don't modify SDK, I created a library on top, just counted 10,850 lines

**Comment by dpmurphy** [comment]
Go you.....I can't see  me getting the motivation together for that level of commitment .

**Comment by alexbk66** [comment]
Half of this I did for HS3 https://forums.homeseer.com/forum/developer-support/programming-plug-in-development/programming-with-homeseer/1289533-yet-another-hspi-plugin-library

But HS4 required a lot of time investment.  But now I can do a new plugin in a couple of days.

![image](https://user-images.githubusercontent.com/2533315/118304317-dd899500-b529-11eb-8c45-0615f62e9b3b.png)

**Comment by dpmurphy** [comment]
@alexbk66  Thanks  for the tip of linking to the source version of the sdk for debugging.

So the Options in SelectViewList are created properly by the constructor, and the function GetSelectedOption() returns the correct info.....Options[Selection]. Unfortunately it appears the Options are getting stood on by HS, and OptionKeys aren't getting updated either. So both are wrong.

**Comment by jldubz** [comment]
@dpmurphy,
I have addressed this in https://github.com/HomeSeer/Plugin-SDK/issues/124. Let's move this discussion over to that issue. Thanks!

**Comment by alexbk66** [comment]
> 



> @alexbk66 it would be very beneficial for everyone working with HS4 if you would help us enhance this SDK instead of building a wrapper and dividing support/dev efforts. Is there a particular reason why you are opting to build a wrapper? Is this a conversation we can take offline?
@jldubz I guess main reason was historical - I created the wrapper for HS3.  Sure we can discuss offline.
