### ISSUE TITLE
Setting Custom Color from Event doesn't work

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#202]
https://forums.homeseer.com/forum/hs4-products/hs4-plugins/lighting-primary-technology-plug-ins-aa/ak-ikea-alexbk66-aa/1475042-set-the-colour-from-a-vb-net-script

Neither SetIOMulti or HsEvent are called
![image](https://user-images.githubusercontent.com/2533315/118680826-69f5c980-b842-11eb-815d-d076cc409da3.png)

**Comment by spudwebb** [comment]
In your screenshot, the action is disabled....
I have just tested with the LIFX plugin and it works for me, but you have to save the action before it actually starts working.

**Comment by alexbk66** [comment]
Yeah, idn how it happened. Thanks for pointing that.

But the user actually asked about scripting - so from the script how one sets the color?  By setting device string (status) to "#FF0400"?  Using what function?

Can you please may be reply directly in the thread linked and close this.
