### ISSUE TITLE
HS-1110 broke my event

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#203]
My “LG ThinQ” plugin uses a single event action that can’t be used anymore since HS4 4.1.14.0. Probably related to "fix" HS-1110. 
 
No matter what I try, the functions in my event module are not being called anymore. So for instance OnNewAction, IsFullyConfigured and OnConfigItemUpdate don’t work. Setting a breakpoint reveals that they are not being hit.
 
My Plugin name is “LG ThinQ”. My Plugin ID is “LG_ThinQ”. If I change the ID to “LG ThinQ” it works again (but causes other issues off course).
 
Not sure how I can fix this without breaking other stuff. Can you explain why this is happening and how it can be resolved?

Thanks!

**Comment by spudwebb** [comment]
The problem is that your plugin ID contains "_" which is not allowed.

From https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.AbstractPlugin.html#HomeSeer_PluginSdk_AbstractPlugin_Id

> Do NOT use special characters or spaces in your plugin ID
> Remarks
> The ID is used throughout the HomeSeer platform to target this plugin specifically via URL or internal code. It is recommended to use the name of your plugin, removing special characters and spaces, as the ID to make it easy to match them with one-another.

The solution is to change your plugin ID to "LGThinQ" (without any space or special character), which is going to be a pain  if you already have a lot of users for this plugin because they will need new licenses and the devices and events associated to the plugin will need to be recreated.

**Comment by stefxx** [comment]
Oh wow. Really? I never considered an underscore a special character.

And yes, it is an existing plugin with many users, licenses etc. The plugin portal doesn't prohibit you from creating a name with an underscore, and - specific for this issue - before HS-1110 the plugin name was used which contained a space, which often creates more issues than an underscore.

Since this plugin is working fine in every single way for almost a year, and also the events worked fine until 4.1.15.0, isn't there another any way to fix this?

Thanks!

**Comment by spudwebb** [comment]
Do you have any other plugins that use an underscore or any other special characters in their ID ?

**Comment by stefxx** [comment]
Just checked all my HS4 plugins. No, just this one.

**Comment by stefxx** [comment]
I see that I do have a few HS3 plugins that uses spaces in the ID. But all of them have HS4 versions as well.

**Comment by stefxx** [comment]
Hi @spudwebb , any update? Thanks again!

**Comment by spudwebb** [comment]
I made a fix for the event actions/triggers problem with plugin id containing an underscore. Not sure if it is going to be included in the release scheduled for next week (4.1.17.0) though. It is tracked as HS-1245

**Comment by stefxx** [comment]
Thank you. Highly appreciated!

**Comment by stefxx** [comment]
Thank you!!
