### ISSUE TITLE
WithInput and WithTextArea: Unable to save when some special characters are used

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#204]
**Environment and System Config**
- OS: Windows
- Language: VB
- IDE: VS2019
- HomeSeer Version: 4.1.17.0
- PluginSDK Version: v1.3.0

**Describe the issue**
When using some characters in a PageFactory.WithInput or .WithTextArea, it cannot be submitted. The following error pops up:
"Unable to save changes : Error, Exception in Plug-In Action Post UI: Invalid length for a Base-64 char array or string."

**Steps to Reproduce**
1. Create a PageFactory with .WithInput or WithTextArea
2. Run the plugin and enter the following text: <>
3. Try to save

**Expected behavior**
I would expect the .WithInput and .WithTextArea to accept anything that can be entered through the keyboard of the user, and submitted succesfully.

-----

**Screenshots**
![Screenshot 2021-06-17 200248](https://user-images.githubusercontent.com/20107364/122450319-2c05d580-cfa7-11eb-8cef-86f7d9ea73da.png)

**Logs**
N/A

**Additional info**
N/A

**Comment by spudwebb** [comment]
On what type of page are you adding those views?
I tried on both settings and device config page, and it worked for both.

**Comment by stefxx** [comment]
Hi, sorry I should have mentioned that. I am using it for an event action.

**Comment by spudwebb** [comment]
I can reproduce the problem. It is now tracked as HS-1278 and is scheduled to be fixed in the next HS4 release (4.1.18.0)

**Comment by stefxx** [comment]
Great!

**Comment by stefxx** [comment]
FIxed in 4.1.18.0. Thanks!
