### ISSUE TITLE
Invalid StatusGraphics cannot be fixed in plugin

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#206]
**Environment and System Config**
- OS: Windows
- Language: VB
- IDE: VS2019
- HomeSeer Version: v4.1.18.0]
- PluginSDK Version: v1.3.0

**Describe the issue**
Since HS4.1.18.0, a feature of my plugin generates the following error:
Error displaying device (1) <feature name>:Min 1 must be less than Max 0 Check with the owner of the plugin that created this device.
Which is a fair message and obviously a bug in my plugin. However, there is no way to fix this. Because now I cannot access the feature anymore. hs.GetFeatureByRef, hs.GetFeatureByAddress and even hs.GetDeviceWithFeaturesByRef all return nothing or generate an exception. 

**Steps to Reproduce**
Using an older HS4 version, create a feature with an invalid StatusGraphic. In this case, range from 1 to 0. Than upgrade to 4.1.18.0 and try to access the feature with hs.GetDeviceByAddress or similar functions.

**Expected behavior**
I would expect a warning in the log, but to be still able to access the device (and the functions not to return null or generate an exception. If I can access the feature, I can clear the StatusGraphic and fix the problem.

-----

**Screenshots**
n/a

**Logs**
n/a

**Additional info**
n/a

**Comment by stefxx** [comment]
Since this is causing serious issues with one of my plugins I would appreciate some kind of response. Thanks!

**Comment by spudwebb** [comment]
you can use ClearStatusGraphicsByRef to clear the invalid StatusGraphics and then rebuild them correctly.

**Comment by stefxx** [comment]
Thanks Spud. However, I am accessing all my devices/features by device address. I have no way of knowing the device ref without getting the feature first by address. Since all functions I've tried return nothing or generate an exception, how would I know the feature ref needed to call ClearStatusGraphicByRef?

**Comment by spudwebb** [comment]
you can get a list of the devices/features refs  associated with your plugin using GetRefsByInterface. And you can get the address property of each one using GetPropertyByRef.

**Comment by stefxx** [comment]
Seems like you prefer the hard way. Thanks but no thanks. I'll figure something out.

**Comment by alexbk66** [comment]
/// <summary>
/// GetDeviceByAddress or GetFeatureByAddress?
/// </summary>
/// <param name="addr"></param>
/// <returns>AbstractHsDevice</returns>
public AbstractHsDevice GetHSDeviceByAddr(string addr)
{
    HsFeature f = hs.GetFeatureByAddress(addr);
    if (f != null && !hs.IsRefDevice(f.Ref))
        return f;

    HsDevice d = hs.GetDeviceByAddress(addr);

    return f ?? d as AbstractHsDevice;
}
