### ISSUE TITLE
Bug saving "Control Device" event action if the control string is one char long

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#207]
I sent email to support a week ago, no reply!

Looks like a bug saving "Control Device" event action if the control string is one char long.  When I select "Set Control" value - its stays empty. 
https://forums.homeseer.com/forum/hs4-products/hs4-plugins/media-plug-ins-aa/ak-google-cast-alexbk66-aa/1481301-icons-instead-of-text-in-device-labels#post1485248

My control strings are unicode symbols i.e. "&#x1f507;" but even for normal chars i.e. '-' or '+' same problem. If I add space to the string - it starts saving the action.  Sometimes after I remove the space - it still works.  But for '+' even adding space doesn't help.  Weird.

**Comment by spudwebb** [comment]
confirmed and tracked as HS-1335

**Comment by spudwebb** [comment]
For non alphanum ASCII characters like '+' HS4 needs a fix to properly encode them. For  unicode symbols like "🔇" I believe you actually use the html escape code  "&#x1f507;" to create the control in your C# code, but you need to directly use the unicode character "🔇" instead. I tested it and it works in devices and events if you create it that way.

**Comment by alexbk66** [comment]
yeah, seems to work, thank you

**Comment by spudwebb** [comment]
issue with '+' character as a control is fixed in HS 4.2
