### ISSUE TITLE
If device value matches exactly start of graphics pair - the device status isn't set

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#208]
![image](https://user-images.githubusercontent.com/2533315/128357951-7d291f4f-baec-45ac-9466-67a38afcfd3e.png)
![image](https://user-images.githubusercontent.com/2533315/128358088-b3ef793b-8f7f-4339-a20c-e781490a9480.png)
![image](https://user-images.githubusercontent.com/2533315/128358163-6cb56190-6d45-4059-8361-4fa3ee569af9.png)

**Comment by spudwebb** [comment]
With what version of HS4 are you reproducing this issue? 
This should be fixed in HS 4.1.100.0 / PSDK 1.3.1

**Comment by alexbk66** [comment]
4.1.18.0 / 1.3.0.0

I'll try updating SDK

**Comment by alexbk66** [comment]
Ok, 4.1.18.0 / 1.3.1.0 seems to work, thank you,
