### ISSUE TITLE
How to delete a status range??

### ISSUE THREAD

**Issue by dpmurphy** [HomeSeer/Plugin-SDK#210]
**Environment and System Config**
- OS: Windows
- Language: C#
- IDE: VS2019
- HomeSeer Version: v4.0.18
- PluginSDK Version: v1.3.1

**Describe the issue you are encountering**

For a single value the following StatusGraphic code works

```
if (feat.HasGraphicForValue(value)) {
   hs.DeleteStatusGraphicByValue(dev.RefId, value);
}

var statusGraphic = new StatusGraphic(img, value, label);
hs.AddStatusGraphicToFeature(dev.RefId, statusGraphic);
```

So I expected the following code to work but it doesn't, are ranges handled in a "special way" 
DeleteStatusGraphicByRange doesn't exist in the PDK?

```
if (feat.HasGraphicForRange(range)) {
   hs.DeleteStatusGraphicByRange(dev.RefId, range)
}

var statusGraphic = new StatusGraphic(img, range);
hs.AddStatusGraphicToFeature(dev.RefId, statusGraphic);
```

I have similar issue/query with adding/deleting StatusControlsByRange....Any ideas?

**Comment by spudwebb** [comment]
DeleteStatusGraphicByValue should work for both single values and ranges. For ranges you just have to pass the min value of the range.

**Comment by dpmurphy** [comment]
@spudwebb thanks for the response, it does work as you suggest. I would request that a method be added to the sdk, if only to avoid confusion.

`hs.DeleteStatusGraphicByRange(dev.RefId, range)`

Investigating this I ended up with more questions on ValueRanges. In particular how would you delete all StatusGraphics for all ranges in a feature?

I thought GetStatusGraphics.... would return a list or something?

**Comment by spudwebb** [comment]
if you want to delete all StatusGraphics for a feature you can use ClearStatusGraphicsByRef

if you want to get all StatusGraphics for a feature you can use GetStatusGraphicsByRef which returns a List<StatusGraphic>

**Comment by dpmurphy** [comment]
@spudwebb great thank you.
