### ISSUE TITLE
Help with HS3 to HS4 devices

### ISSUE THREAD

**Issue by rmasonjr** [HomeSeer/Plugin-SDK#215]
Do our plugins need to convert our HS3 devices to HS4?

If so, will there be a clearly documented method on how to accomplish this?

For example, I use a parent/child relationship of my plugin's devices in HS3.  Do I need to fully convert them to a HS4 device/feature relationship while preserving the root device's original device reference?

Thanks
Rob

**Comment by spudwebb** [comment]
Duplicates #183
