### ISSUE TITLE
Whitespace after room name

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#221]
HS 4.2.5.0
PluginSdk 1.3.1.0

I can enter room name with trailing space, but the list of rooms (in filter) shows the room names trimmed - so if I select the trimmed room name - no devices are shown. Which is quite confusing.

**Comment by spudwebb** [comment]
Fixed in HS 4.2.8.0 when editing floor/room leading and trailing spaces are trimmed
