### ISSUE TITLE
GetJuiDeviceConfigPage being called twice

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#222]
running hs 4.2.5.0

is it expected that GetJuiDeviceConfigPage will be called twice when i click my custom plugin tab?

am i missing something, or can this be fixed or do i need to account for this behavior

@spudwebb , @rjhdakota

**Comment by alexbk66** [comment]
Yeah, confirming - called twice `GetJuiDeviceConfigPage(int deviceRef)`

**Comment by spudwebb** [comment]
Not sure yet why it's called twice, but it isn't expected. Tracked as HS-1475

**Comment by spudwebb** [comment]
fixed in HS 4.2.7.0
