### ISSUE TITLE
SelectView.optionkeys is nothing in a given view within OnDeviceConfigChange

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#223]
with the following call
` Page.AddView(New SelectListView($"{PageID}_Setting_{Setting.Key}", Setting.Name, Setting.ToList.Keys.ToList, Setting.ToList.Values.ToList, ESelectListType.DropDown, Setting.Selection))`

my optionkeys aren't being passed back to OnDeviceConfigChange

![image](https://user-images.githubusercontent.com/67801043/139879755-e04756fe-d1d3-4483-8578-30ca0d97d93d.png)

i dont need access to the display values, but rather the optionkeys 

**i think something is broken**

@spudwebb, @rjhdakota

**Comment by spudwebb** [comment]
this has been reported as PSDK-101
one possible workaround is to use the Selection property with the original object that you should have in memory to get the selected key.

**Comment by mnsandler** [comment]
the original view object is created in the GetJuiDeviceConfigPage. By the time I get the view back in OnDeviceConfigChange, it doesn't have all the properties. Sounds like this is a know issue.

i have recreated my optionlist in OnDeviceConfigChange to get my optionkey based on Selection

thanks

**Comment by mnsandler** [comment]
What's the timeframe for fixing this issue?

**Comment by alexbk66** [comment]
I don't think this "issue" can be fixed - it will break all existing plugins

**Comment by alexbk66** [comment]
See my reply in forum https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-plugin-development/1506929-how-do-i-refresh-a-liquid-tag-without-refreshing-the-page?p=1506979#post1506979

**Comment by mnsandler** [comment]
I'm not request that the selection property be changed. I just need the OptionKeys to be populated so we can use the selection property on the OptionsKeys list to get the key value.

**Comment by mnsandler** [comment]
@spudwebb is there a link to PSDK-101
looking for a timeframe for this to be resolved

**Comment by mnsandler** [comment]
would this also fixed SelectView.GetSelectedOption() which is blank as well

**Comment by jldubz** [comment]
@mnsandler ,

I answered this here https://github.com/HomeSeer/Plugin-SDK/issues/124

This behavior is by design. Can we move our discussion to this issue? I'll update it to acknowledge that it is relevant to Settings and Events. Thanks.
