### ISSUE TITLE
hs4 APIVersion still returns 4

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#224]
has this property been updated for hs4? it should return a different value than the hs3 api

**Comment by spudwebb** [comment]
I believe this property has been updated for HS4.
If you run HS4, IHsController.APIVersion returns 4
and if you run HS3, IHSApplication.APIVersion returns 3
isn't it what you see ?

**Comment by mnsandler** [comment]
is working correctly
