### ISSUE TITLE
Error on InitIO: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by mads-b** [HomeSeer/Plugin-SDK#228]
**Environment and System Config**
- Language: C#
- IDE: VS2019
- HomeSeer Version: [v4.0.0.30]
- PluginSDK Version: [v1.2.5]

**Describe the issue you are encountering**
Some of my users are encountering something that resembles a Nullpointer exception. I have no idea how to approach debugging this, as HS does not necessarily spit out that much in terms of logs.

My plugin crashes for a small minority, right after install. See error logs here:
 https://forums.homeseer.com/forum/hs4-products/hs4-plugins/user-interface-plug-ins-aa/simmap-svamp/1500204-error-upon-installation?p=1507158#post1507158

So, to address this:
How to approach debugging such a thing? Where do logs end up that are written? I do write nearly everything that might go wrong into HomeSeerSystem.WriteLog(logType, message, Name), but I have yet to find where these logs end up.

Also: Can anyone with a better understanding of the SDK give any hints regarding where in the initalization process this failed so I can dig further into the source of where the initialization process fails for some?

**Comment by alexbk66** [comment]
As the error says - exception is in InitIO, which calls virtual Initialise()

![image](https://user-images.githubusercontent.com/2533315/142732005-4b08eeab-c179-43e7-94fa-1c6e7499c039.png)

Do you override Initialise()?  Do you have exception handling?

Also, nice feature of .NET is "UnhandledException" handler:

![image](https://user-images.githubusercontent.com/2533315/142732155-6afa5861-ecd3-4f57-bf01-6298166590ac.png)

**Comment by mads-b** [comment]
Thanks for the tips. I'll dig further on my own regarding where it happens. I do override initialize

Any hints on those log locations? :)

**Comment by alexbk66** [comment]
![image](https://user-images.githubusercontent.com/2533315/142732864-253b8f11-183c-4cab-ac22-df3146f1e0c9.png)
