### ISSUE TITLE
HsEvent not called on name changes

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#23]
I am trying to catch the name change of a device, but it does not work for me for some reason.
I am doing this more or less similar to my HS3 plugin using this RegisterEvenCB line:

`hs.RegisterEventCB(HomeSeer.PluginSdk.Constants.HSEvent.CONFIG_CHANGE, IFACE_NAME)`

Using this routine to override AbstractPlugin.HsEvent:

```
Public Overrides Sub HsEvent(eventType As HomeSeer.PluginSdk.Constants.HSEvent, parms() As Object)
       Dim NewThread As Threading.Thread
        Select Case eventType
            Case HomeSeer.PluginSdk.Constants.HSEvent.CONFIG_CHANGE
                Try
                    If parms(1) = 0 Then
                        If parms(3) = 0 Then Exit Sub '- we do not have any reference to our devices, could be multidevice action or other stuff
                        If hs.IsRefDevice(parms(3)) Then
                            Dim HsDevice As Devices.HsDevice = hs.GetDeviceByRef(parms(3))
                            If HsDevice.Interface = IFACE_NAME Then
                                If parms(4) = DAC.CHANGED OrElse parms(4) = DAC.DELETED Then
                                    NewThread = New Threading.Thread(Sub() UpdateConfigDevices(HsDevice, parms(4)))
                                    NewThread.Start()
                                End If
                            End If
                        Else 'feature

                        End If
                    End If
                Catch ex As Exception
                    Log(GetExceptionInfo(ex), LogLevel.Verbose)
                    Log("Error running config change:" & ex.Message, LogLevel._Error)
                    Log("Extra info: " & parms(1) & "-" & parms(2) & "-" & parms(3) & "-" & parms(4))
                End Try
            Case Else
                Log($"Unexpected change found on ref {parms(3)} 1: {parms(1)} 2: {parms(2)} 3: {parms(3)}  4: {parms(4)}")
        End Select

    End Sub
```

But whatever I try, the callback is never taking place? What am I missing? Or is this not yet active in the Alpha version?

**Comment by jldubz** [comment]
Can you please check the HomeSeer logs to see if there is an entry that lists something along the lines of
> Calling event CONFIG_CHANGE callback for plug-in IFACE_NAME

This tells us that the callback was registered correctly and the event is firing but that it is not reaching the plugin correctly. There may be some additional error messages in the log in this case. If there is, please paste them here so we can analyze them.

If this message is not in the logs then it sounds like the register did not take place, and there should be something else in the logs that indicates that there was a problem with this process.  Let me know if you cannot find anything along these lines in your logs.

**Comment by wvuyk** [comment]
Lon-Luke,

I have rechecked the log here but cannot find the log entries you mentioned, nor seeing other errors in that area.

The statement `hs.RegisterEventCB(HomeSeer.PluginSdk.Constants.HSEvent.CONFIG_CHANGE, IFACE_NAME)` is called during HSPI.Inittialise along with other steps, and I am pretty sure it is being called?

Do I need to set a different level of tracing for HS4 maybe?

**Comment by jldubz** [comment]
@wvuyk 

No you do not need to adjust logging.  It looks like the registration of HS4 plugins as callback listeners is happening but there are no events being sent out.  I have added in some additional logging around the `HSEvent` and `RegisterEventCB` methods so a debug entry is logged whenever they are called and am working on tracing through this.

I'll let you know as we learn more.

Thanks.

**Comment by wvuyk** [comment]
What is the current status of this?

**Comment by wvuyk** [comment]
Any update after 8 months?

**Comment by rjhdakota** [comment]
There was a lot of work done with the events recently. Have you tried it with the latest beta? Is it still an issue?

**Comment by rjhdakota** [comment]
I tested and this was fixed in 4.0.8.0, so the latest build has the fix. Note that device changes go into a queue and are reported on an interval. So your HSEvent could be called 1 minute after the change. Note that HS3 was the same put the max delay was less.

**Comment by wvuyk** [comment]
Rich,

Indeed it is resolved, was relying on my earlier tests, but that was April. Should have tested again. Will close this issue.

Thanks,

Wim

**Comment by wvuyk** [comment]
Closed

**Comment by wvuyk** [comment]
@rjhdakota This issue has resurfaced again for 4.1.8.0.
did not check for some time, but a rename of a device is no triggering the HSEvent anymore.

**Comment by wvuyk** [comment]
It is working after all, but only after more then one minute? There is a very large delay in the update.  Why is this?

**Comment by rjhdakota** [comment]
If the delay is a problem, let me know. HS3 also had a delay, but it was less. There are times when these pile up so we only send the notification when we save the device/event data, which is every 30 or 60 seconds. The assumption is that this information is not needed in real time.

**Comment by wvuyk** [comment]
I use the HSEvent for user changes in the name of a device. I catch this change and rename the features based on this change. A impatient user (like me :-)) does not see the change after a refresh of the device page. I will warn on this in the user guide, so I guess it is ok this way.

**Comment by rjhdakota** [comment]
I will see if I can move the check to some other task that runs more often.


> I use the HSEvent for user changes in the name of a device. I catch this change and rename the features based on this change. A impatient user (like me :-)) does not see the change after a refresh of the device page. I will warn on this in the user guide, so I guess it is ok this way.
