### ISSUE TITLE
RegisterEventCB() is legacy?

### ISSUE THREAD

**Issue by cibyr** [HomeSeer/Plugin-SDK#230]
`IHsController.RegisterEventCB()` is noted as being "ported directly from the legacy HS3 API" and "Please use with caution", but there doesn't appear to be any other way for a plugin to get notified of device state changes. Please either remove this warning from the documentation, or update it to point developers to the preferred mechanism to register for callbacks.

**Comment by spudwebb** [comment]
I'm closing this as a duplicate of issue #301, as we need a new version of RegisterEventCB that takes a Systems.EHsSytemsEvent as parameter

**Comment by alexbk66** [comment]
Not sure why this is closed?  

RegisterEventCB still takes enum HSEvent, not EHsSytemsEvent, but HSEvent is deprecated.  So what do we do?  Do you have a replacement for RegisterEventCB(enum HSEvent) which takes EHsSytemsEvent instead?

Or we just ignore the Obsolete warnings?

**Comment by spudwebb** [comment]
This is closed because it's a duplicate of #301, as mentioned above
