### ISSUE TITLE
HsEvent() params are not documented

### ISSUE THREAD

**Issue by cibyr** [HomeSeer/Plugin-SDK#231]
The `params` argument to `IPlugin.HsEvent()` is only documented as being "The data associated with the event", with no hint as to what the types might be or what the values could mean. The best I could find is [this forum post](https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-programming/1342369-hsevent?p=1458418#post1458418) by a third party developer, which only covers the params for two event types.

FWIW, a type-safe callback method per event type would be a much nicer API - easier to understand, and harder to misuse.

**Comment by alexbk66** [comment]
Yep, a lot of things with HS take a lot of time to be able to comprehend and use

**Comment by spudwebb** [comment]
This is documented in the HS3 SDK docs:  https://help.homeseer.com/help/HS3SDK/static/default.htm#.hsevent__registereventcb_

**Comment by wvuyk** [comment]
HSEvent does only accept  HomeSeer.PluginSdk.Constants.HSEvent as parameter. You then get a obsolete message about constants.hsevents being obsolete. And guess what? the advise then is to use Types.EHsSystemEvent. Go figure....

When will HSEvent accept both enum types for real?

**Comment by alexbk66** [comment]
Not sure why this is closed?  

RegisterEventCB still takes enum HSEvent, not EHsSytemsEvent, but HSEvent is deprecated.  So what do we do?  Do you have a replacement for RegisterEventCB(enum HSEvent) which takes EHsSytemsEvent instead?

Or we just ignore the Obsolete warning?
