### ISSUE TITLE
settings pages in hs stnd vs hs pro

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#233]
I have two JUI settings pages registered (on called Basic, and a second called Advancec)

Both show in hs4 Pro, but only the second page shows in hs4 Standard

Is this a bug?

**Comment by spudwebb** [comment]
I would be surprised if this problem is caused by PRO vs STD licence. Are you testing with the same exact version of HS4 and the same exact version of your plugin in both systems?

**Comment by mnsandler** [comment]
@spudwebb , i guess we can close this. i tested on hs standard along with another user and all is well.
Not sure what is going on with the first user that reported the issue.. I've requested the html source to examine it.
