### ISSUE TITLE
French characters lost with WithInput and WithTextArea in events

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#236]
**Environment and System Config**
- OS: Windows 11
- Language: VB
- IDE: VS2019
- HomeSeer Version: 4.2.7.0
- PluginSDK Version: v1.3.1.0

**Describe the issue**
WithInput or WithTextArea in an event, doesn't catch special characters like é, è, ê, ï and ç (often used in French languages). Same for German characters like Ü and ẞ. The resulting configViewChange in OnConfigItemUpdate translates those characters into a ?.

**Steps to Reproduce**
Dim confPage = PageFactory.CreateEventActionPage(PageId, ActionName)
confPage.WithInput($"{PageId}-title", "Title")
confPage.WithTextArea($"{PageId}-message", "Message", 5)

**Expected behavior**
I like to use those characters as entered into my event actions.

-----

**Screenshots**
![Screenshot 2021-12-08 092501](https://user-images.githubusercontent.com/20107364/145174186-61078db5-c7de-413b-add8-f90b6faa4a9f.png)
![Untitled](https://user-images.githubusercontent.com/20107364/145174191-19b4d590-4cb6-404c-b899-655de4010f34.png)

**Logs**
n/a

**Additional info**
n/a

**Comment by stefxx** [comment]
Also note that using a German eszatt (ẞ) the OnConfigItemUpdate isn't even called anymore.

**Comment by spudwebb** [comment]
tracked as HS-1502

**Comment by spudwebb** [comment]
Fixed in HS 4.2.8.0

**Comment by stefxx** [comment]
Thanks!
