### ISSUE TITLE
Can we make DeviceFactory and FeatureFactory more consistent?

### ISSUE THREAD

**Issue by dpmurphy** [HomeSeer/Plugin-SDK#238]
**Environment and System Config**
- OS: [Windows]
- Language: [C#]
- IDE: [VS2019]
- HomeSeer Version: [v4.2.6.0]
- PluginSDK Version: [v1.3.1]

**Describe what you would like to see added or changed**
Add .WithAddress to featureFactory

Code below.....

		/// <summary>
		/// Add an <see cref="AbstractHsDevice.Address"/> to the feature
		/// </summary>
		/// <param name="address">The string to set the address to</param>
		/// <returns>The <see cref="FeatureFactory"/> with the updated address value</returns>
		public FeatureFactory WithAddress(string address)
		{
			_feature.Address = address;
			return this;
		}

**Priority**
How important is this to you on a scale of 1-5?
3. Medium
 But easy to fix.......

**Comment by spudwebb** [comment]
tracked as PSDK-216

**Comment by jldubz** [comment]
`FeatureFactory.WithAddress()` was added in [v1.4.0.0](https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_4_0_0.html)
