### ISSUE TITLE
SelectListView "Select an option" text

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#239]
Can you please add to SelectListView an argument/field to replace default "Select an option" text for empty list.

**Comment by spudwebb** [comment]
what do you mean exactly by "for empty list" ?

**Comment by alexbk66** [comment]
Sorry, was late night...

I mean when nothing is selected in the list - it shows "Select an option".  I would like to be able to display more specific prompt, i.e. "Select Station", etc.

**Comment by spudwebb** [comment]
got it, tracked as PSDK-217

**Comment by jldubz** [comment]
This was added in [v1.4.0.0](https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_4_0_0.html)
