### ISSUE TITLE
Issue using setting location info on controls (button)

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#24]
I'm on v.27
When I create a feature and add control buttons, if any one of the buttons include location information (HomeSeer.PluginSdk.Devices.Controls.ControlLocation) then none of the buttons shows up in the UI, not on the tile view not on the list view. Only one single button named "controls" shows up and clicking that button doesn't do anything.

Is this incomplete function and "controls" is supposed to open some child window or is this a bug?

I do want to remind @rjhdakota that my HS3 PI, which uses the "dv.MISC_Set(hs, Enums.dvMISC.CONTROL_POPUP)" function has a similar problem that it only shows a "controls" button but I cannot get to the underlying buttons. I believe you confirmed on the private forum that this was missing functionality and you suspected I might be the only one using it. Any guidance here appreciated.

**Comment by spudwebb** [comment]
something like the following seems to work for me:

```
                //buttons
                statusControl = new StatusControl(EControlType.Button);
                statusControl.Label = "Stop";
                statusControl.TargetValue = STATE_CTRL_STOP;
                statusControl.ControlUse = EControlUse.Stop;
                statusControl.Location = new ControlLocation(1, 1, 1);
                _hs.AddStatusControlToFeature(_mediaStatusFeat.Ref, statusControl);

                statusControl = new StatusControl(EControlType.Button);
                statusControl.Label = "Play";
                statusControl.TargetValue = STATE_CTRL_PLAY;
                statusControl.ControlUse = EControlUse.Play;
                statusControl.Location = new ControlLocation(1, 2, 1);
                _hs.AddStatusControlToFeature(_mediaStatusFeat.Ref, statusControl);

                statusControl = new StatusControl(EControlType.Button);
                statusControl.Label = "Pause";
                statusControl.TargetValue = STATE_CTRL_PAUSE;
                statusControl.ControlUse = EControlUse.Pause;
                statusControl.Location = new ControlLocation(1, 3, 1);
                _hs.AddStatusControlToFeature(_mediaStatusFeat.Ref, statusControl);
```

Could you provide some code

**Comment by dcorsus** [comment]
Interesting. I tried all kind of combinations with rows starting from 0 or 1 or unique, always the same issue. The only difference I see is that all controlUse for all buttons is the same (0) because they don't map to any of the pre-defined enums. I'm going to try to give them unique controluses and see if that makes a difference.

**Comment by dcorsus** [comment]
This code does not work

          

'
     Dim ff As HomeSeer.PluginSdk.Devices.FeatureFactory = FeatureFactory.CreateFeature(IFACE_NAME)

            ff.WithName("Control")
            ff.AsType(Identification.EFeatureType.Generic, 0)
            ff.WithMiscFlags(EMiscFlag.ShowValues)
            Dim loc1 As HomeSeer.PluginSdk.Devices.Controls.ControlLocation = New HomeSeer.PluginSdk.Devices.Controls.ControlLocation(1, 1, 1)
            ff.AddButton(msPlayAll, "All Zones Play", loc1, Controls.EControlUse.NotSpecified)
            Dim loc2 As HomeSeer.PluginSdk.Devices.Controls.ControlLocation = New HomeSeer.PluginSdk.Devices.Controls.ControlLocation(1, 2, 1)
            ff.AddButton(msPauseAll, "All Zones Pause", loc2, Controls.EControlUse.NotSpecified)
            Dim loc3 As HomeSeer.PluginSdk.Devices.Controls.ControlLocation = New HomeSeer.PluginSdk.Devices.Controls.ControlLocation(1, 3, 1)
            ff.AddButton(msMuteAll, "All Zones Mute On", loc3, Controls.EControlUse.NotSpecified)
            Dim loc4 As HomeSeer.PluginSdk.Devices.Controls.ControlLocation = New HomeSeer.PluginSdk.Devices.Controls.ControlLocation(1, 4, 1)
            ff.AddButton(msUnmuteAll, "All Zones Mute Off", loc4, Controls.EControlUse.NotSpecified)
            Dim loc5 As HomeSeer.PluginSdk.Devices.Controls.ControlLocation = New HomeSeer.PluginSdk.Devices.Controls.ControlLocation(1, 5, 1)
            ff.AddButton(msBuildDB, "BuildDB", loc5, Controls.EControlUse.NotSpecified)
            ff.AddGraphicForValue(ImagesPath & "NOKBtn.png", msDisconnected)
            ff.AddGraphicForValue(ImagesPath & "PartialOKBtn.png", msBuildingDB)
            ff.AddGraphicForValue(ImagesPath & "OKBtn.png", msConnected)


            Dim nfd As NewFeatureData
            nfd = ff.PrepareForHsDevice(DeviceRef)
            Dim NewFeatureRef As Integer = myHomeSeerSystem.CreateFeatureForDevice(nfd)'


This code does work (note I removed passing along the location info)

`            Dim ff As HomeSeer.PluginSdk.Devices.FeatureFactory = FeatureFactory.CreateFeature(IFACE_NAME)

            ff.WithName("Control")
            ff.AsType(Identification.EFeatureType.Generic, 0)
            ff.WithMiscFlags(EMiscFlag.ShowValues)
            ff.AddButton(msPlayAll, "All Zones Play", , Controls.EControlUse.NotSpecified)
            ff.AddButton(msPauseAll, "All Zones Pause", , Controls.EControlUse.NotSpecified)
            ff.AddButton(msMuteAll, "All Zones Mute On", , Controls.EControlUse.NotSpecified)
            ff.AddButton(msUnmuteAll, "All Zones Mute Off", , Controls.EControlUse.NotSpecified)

**Comment by dcorsus** [comment]
Quick tidbit while I'm still experimenting. If I only add FOUR buttons, it still works. Adding the FIFTH button (in my case) breaks it. Next step is to play with the parameters of the 5th button, see if I can figure something out but recommend to inspect HS implementation code whether 5 over 4 triggers different behavior (when location info is present, remember w/o location info all is fine).

**Comment by dcorsus** [comment]
Going to stop my experimenting here and let HS team figure out what is going on or what the logic is and therefore what we as authors are supposed to do.

What works so far is if I set location of buttons to:
Adding 4 buttons to row 1 works. Adding button 5 to row 1 doesn't work
Adding 4 buttons to row 1 and the 5th button to row 2 (column 1) seem to work as well.
Adding 4 buttons to row 1, 5th button to row 2, and 2 more buttons to row 3, doesn't work.

**Comment by jldubz** [comment]
@dcorsus 

We are continuing to work on cleaning up this behavior.  In the meantime, can you please try to stick to a maximum 3x4 control grid as documented here: https://docs.homeseer.com/display/HSPI/Control+Grids

Thanks!

**Comment by jldubz** [comment]
@dcorsus we will be revising all of the Plugin SDK documentation over the next couple months.  Currently the control grid is limited to what is defined in the above documentation.  This may change in the future.  If there is something that you need to do that you are unable to with this 3x4 maximum, please let me know and I will bring it up with the team.

Thanks!

JL
