### ISSUE TITLE
hs.CreateCategory() returns empty ID for "Digital/Analog I/O"

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#241]
Really strange, but for some reason hs.CreateCategory() returns empty ID for **"Digital/Analog I/O"** when trying to create new category

**Comment by spudwebb** [comment]
I have just tested this, the first time I try to create the "Digital/Analog I/O" category,  hs.CreateCategory() returns a new ID as expected. But if I try to create it again when it already exists, hs.CreateCategory() returns an empty ID.
So this is probably what you experienced as well. When the category name already exist, you can get its ID using hs.GetAllCategories()
