### ISSUE TITLE
Function UpdateStatusNow not being called in 4.2.7.0

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#244]
@spudwebb , @rjhdakota 
i dont see this being called when i click the Poll Devices button on the hs Devices page.

**Comment by Sgt-Shultz** [comment]
Tracked as HS-1511.

**Comment by spudwebb** [comment]
it was also tracked by HS-1504 and should be fixed in the next HS4 release (4.2.8.0)

**Comment by spudwebb** [comment]
Fixed in HS 4.2.8.0
