### ISSUE TITLE
Order of feature pages different in two places in HS 4.2.7.0

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#245]
Settings is put in two different places on these HS controlled menus. Can this be made consistent. My preference is to have Settings last.

this is from the HS4 Plugins menu
![plugin menu](https://user-images.githubusercontent.com/67801043/147409765-85e5a591-2f32-48ce-b426-1786c765832b.png)

this is from the plugins.html page when I click the More button
![plugin more menu](https://user-images.githubusercontent.com/67801043/147409776-74771f5e-283b-4fa1-8858-2b407b67c2da.png)

**Comment by Sgt-Shultz** [comment]
Tracked as HS-1512.

**Comment by spudwebb** [comment]
Fixed in HS 4.2.14.0
