### ISSUE TITLE
hs4.TriggerMatches issue

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#246]
@spudwebb 

TriggerMatches does not return the correct subset of triggers

if I call hs.TriggerMatches(plugin.id, 1, 15), it returns triggers with a SelectedSubTriggerIndex  = 14

I'm expecting the return set to match my query inputs 1,15

ps. using hs4.2.7.0

**Comment by alexbk66** [comment]
For consistency with HS3 (SubTANumber is one based), but SelectedSubTriggerIndex is zero based.  Usual mess.

`SelectedSubTriggerIndex = trigInfo.SubTANumber-1;`

**Comment by mnsandler** [comment]
Alex
In my hs4 migration code, I renumbered my trigInfo.SubTANumber to be zero based so it would line up with SelectedSubTriggerIndex.

here is what i don't get or someone can confirm, when I store my SubTANumber value in a trigger, why is it being changed by the API?

**Comment by alexbk66** [comment]
I don't think you can re-number SubTANumber - it's binary serialised in TrigActInfo
If you look at PluginSdk code - it's always assumed SubTANumber is one based - internally it's still old HS3 code (TrigActInfo)
![image](https://user-images.githubusercontent.com/2533315/147491293-84732b04-0612-4150-84b2-7099a4d95559.png)

![image](https://user-images.githubusercontent.com/2533315/147491050-8b868a64-9522-455b-b659-9825ad400b75.png)

![image](https://user-images.githubusercontent.com/2533315/147491285-1f1b8aca-d19c-4fdd-98aa-1c285acfc9eb.png)

**Comment by mnsandler** [comment]
Alex,
maybe this doesn't work the way I thought but in my hs4 plugin, I wrote migration code for my old hs3 triggers to upgrade them to the new hs4 class. i\In the code, i changed the subTANumber from a 1-based to 0-based index.

Its too annoying to have to remember when to -1 in the code.

i think @spudwebb should add a better gettriggerlist method that operates correctly, if he can't change the existing routines at this point.

**Comment by alexbk66** [comment]
But I don't get why you need to use subTANumber - when you can just use SelectedSubTriggerIndex ( = trigInfo.SubTANumber - 1)

**Comment by mnsandler** [comment]
i created an enum to hold the values of each subtrigger (SubTANumber). these values match the index position of the SubTriggerTypeNames.

```
    Friend Enum INSTEON_TRIGGER_TYPES As Integer
        STARTRAMPDOWN = 0
        STARTRAMPUP = 1
        RAMPDOWN1 = 2
        RAMPUP1 = 3
...
    End Enum
```

so my trigger methods all start with something like the following
```
                Select Case SelectedSubTriggerIndex

                    Case INSTEON_TRIGGER_TYPES.STARTRAMPDOWN
```

I suppose I could have kept the old enum values and used the (SelectedSubTriggerIndex - 1). I was just trying to keep the the values/logic consistent.  But maybe I don't know what I'm doing.

I also use this Enum when I'm testing triggers to fire.

**Comment by alexbk66** [comment]
PluginLib code assumes both TAN and SubTAN are one based, so you can't really change  it

Also, I always prefer my enums to start from 1, and 0 = Unknown, because when you have unititialised object - in your example the enum value will be STARTRAMPDOWN, which is mis-leading.

**Comment by mnsandler** [comment]
i have taken your advise and started my enums at 1. 

last question, can we change the list of sub triggers provided in SubTriggerTypeNames?

as an example, if i provide a list of devices in a view, i save the dv.ref.  So if the list of devices changes, i can always find the correct device based on dv.ref.

if the triggers saves the SelectedSubTriggerIndex then we can never change the list provided in SubTriggerTypeNames, otherwise the wrong subtrigger will be provided.

**I guess i dont understand what hs is saving internally when a user selects a given trigger?**

**Comment by alexbk66** [comment]
HS stores the "views" collection used to configure the triggers.  
I suggest (that's what I had to do to get the insights) - include PluginSdk source in your solution - so you can debug the internals and get the idea what's happening.
Look at TriggerTypeCollection.cs and AbstractTriggerType.cs
I created a little helper wrapper AbstractTrigger (attached) to make it easier because internal HS implementation is still based on old HS3 TrigActInfo, so to fire the trigger I do:

![image](https://user-images.githubusercontent.com/2533315/147618612-959b2c5c-94c6-4a54-9ae7-ed4c595a43ea.png)


[AbstractTrigger.zip](https://github.com/HomeSeer/Plugin-SDK/files/7786921/AbstractTrigger.zip)

**Comment by alexbk66** [comment]
And I store the SelectedSubTriggerIndex in the hidden Label view to verify that the trigger info actually matches the SubTAN

![image](https://user-images.githubusercontent.com/2533315/147618738-564d00b2-9431-4f8d-bdf1-e7fa6e0c2a19.png)
![image](https://user-images.githubusercontent.com/2533315/147618779-8b4de45d-34dc-4fa5-af31-70a529bca1e1.png)
![image](https://user-images.githubusercontent.com/2533315/147618825-e9c59469-57d4-46a9-a2bd-3ee2ad1ecb5e.png)

**Comment by mnsandler** [comment]
so why do you store the SelectedSubTriggerIndex as opposed to your trigger enum value? that way if your trigger list changes, you still have the correct enum value.
I'm asking because I initially wanted to have a dynamic list of triggers but it doesn't seem possible.

**Comment by alexbk66** [comment]
This is generic code (base class).  And in the derived class I have 

![image](https://user-images.githubusercontent.com/2533315/147627477-9575a862-ced1-4699-82ed-9444edbd454f.png)

It's total mess :{

**Comment by mnsandler** [comment]
For my Actions, I created the below key/value list. I save the enum value to an Action view. Then when I edit/change/run an action, I just get the Action view value (which is a enum value) and continue from there. I know exactly which action I'm dealing with.

I guess I should have done something similar with Triggers; its not too late for me as I haven't released this plugin. But it would be a bit more work.

![actionlist](https://user-images.githubusercontent.com/67801043/147664472-bcb22151-c2d3-4a62-be4b-d8e18afcc1c3.png)
