### ISSUE TITLE
does UpdateViewById work?

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#247]
I have a need to be able to update the option list used in a SelectListView. For example, if the user registers a new device with my plugin, I should be add it do the Options of an existing View by using the UpdateViewById 

can anyone confirm UpdateViewById works in the way I described?

if it doesn't work this way, what is the alternative: RemoveViewById, and then AddView?

**Comment by mnsandler** [comment]
@spudwebb , thanks for the reply.

i guess i thought i could rebuild the view without having to delete it first and then readding it.

it would be helpful if your above comments were in the sdk docs

https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.Jui.Views.ViewGroup.html#HomeSeer_Jui_Views_ViewGroup_UpdateViewById_HomeSeer_Jui_Views_AbstractView_

**Comment by jldubz** [comment]
@mnsandler it looks like there was an issue generating the documentation. It should have been carried over from [`ViewCollectionHelper`](https://github.com/HomeSeer/Plugin-SDK/blob/master/Jui/Views/ViewCollectionHelper.cs). You can see the documentation for `UpdateViewById()` here: https://github.com/HomeSeer/Plugin-SDK/blob/master/Jui/Views/ViewCollectionHelper.cs#L259 . I'll work on addressing this. I did not realize the documentation wasn't inheriting correctly.

Thanks for bringing this to our attention.
