### ISSUE TITLE
Two settings pages aren't showing for one user

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#249]
hs 4.2.7.0
I initialize two settings pages

            Dim SettingsPage = PageFactory.CreateSettingsPage(TABNAMES.BASIC_TAB_ID, "Basic")

            Dim AdvancedPage = PageFactory.CreateSettingsPage(TABNAMES.ADVANCED_TAB_ID, "Advanced")

I have a user testing, and only setting page is being rendered (the second one)

there is no html related to the first at all

I need to get to the bottom of this before I release

**Comment by alexbk66** [comment]
What's TABNAMES.BASIC_TAB_ID?

**Comment by mnsandler** [comment]
```
    Structure TABNAMES
        Const BASIC_TAB_ID As String = "insteon-basic"
        Const ADVANCED_TAB_ID As String = "insteon-advanced"
    End Structure
```

**Comment by alexbk66** [comment]
Then I don't know.  Bootstrap has issues with ids starting from numbers.

How do you return settings pages? I.e. `public virtual SettingsCollection GetSettingsPages()`
I have a sorted dictionary class to hold the settings pages (which again, should've been part of PluginSDK)
![image](https://user-images.githubusercontent.com/2533315/147878093-6d6828cc-ad1e-426f-a55a-8d625a4e0d05.png)

![image](https://user-images.githubusercontent.com/2533315/147878141-a14b44da-2f03-4aab-8c14-8400b817079b.png)

**Comment by mnsandler** [comment]
Alex
there is a SettingsCollection in the SDK from what i can tell. 

![image](https://user-images.githubusercontent.com/67801043/147878338-5104f6a2-e77a-48c7-a612-a218404bb370.png)

I use the following to add a new page

`            Settings.Add(SettingsPage.Page)`

there might be a problem in the ToHtml method of the collection, but i will leave that to HST

**Comment by alexbk66** [comment]
I didn't like the their "ordering" control - I have explicit order index as member of the Page class, so it's much easier to manipulate

**Comment by jldubz** [comment]
@mnsandler 

The sample plugin demonstrates the use of Settings - https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/HSPI.vb#L98

It looks like you are doing it correctly based on what I can see. Are you getting any errors in the console when the user navigates to Settings?

**Comment by jldubz** [comment]
@alexbk66 ,

> I have a sorted dictionary class to hold the settings pages (which again, should've been part of PluginSDK)

The SDK is open source and pull requests are welcome. Looking forward to seeing it.

**Comment by alexbk66** [comment]
> @alexbk66 ,
> 
> > I have a sorted dictionary class to hold the settings pages (which again, should've been part of PluginSDK)
> 
> The SDK is open source and pull requests are welcome. Looking forward to seeing it.

I'll try, thanks for suggestion :)

**Comment by mnsandler** [comment]
> @mnsandler
> 
> The sample plugin demonstrates the use of Settings - https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/HSPI.vb#L98
> 
> It looks like you are doing it correctly based on what I can see. Are you getting any errors in the console when the user navigates to Settings?

no errors that i can see, it looks like only the second settingspage is being rendered. no evidence of the first in the html source from the browser.

but this doesn't happen 100% of the time. there is one user that this happens for. 

is there any additional error logging i can turn on?

**Comment by mnsandler** [comment]
I'm going to close this. i may have just been an unhandled exception cause the Basic page not to render correctly.
