### ISSUE TITLE
Updating PluginExtraData cannot be done

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#25]
I noticed that updating the PluginExtraData object does not work like it was in HS3.
In HS3 the added object would simply be updated when it already exists. In the Plugin-SDK it will stick at the old value

So executing the following statements:

 ```
PED.AddNamed("id", "none")
PED.AddNamed("id", "1")
```
Would result in `PED.Named("id") ` holding "none" where earlier id would return "1"
To update the id you need to add `PED.RemoveNamed("id")` to be able to 'update' the value.

Can this be updated in the Plugin-SDK, so that if a Named entry already exists, it will be updated instead of ignored?

Wim

**Comment by spudwebb** [comment]
you can use:

`PED["id"] = "1";`

it will add or update the value
PlugExtraData works exactly like a standard dictionary except that if the key already exist AddNamed will return false instead of throwing an exception.

**Comment by wvuyk** [comment]
Got that... was playing to nice with the addnamed. Should have thought of that 👍

**Comment by wvuyk** [comment]
I'll close this one as it is not an issue anymore
