### ISSUE TITLE
How are the dv.misc settings set on a device vs feature uses in HS4 

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#252]
clearly the hide settings hides the entire device/feature set on the device page

![image](https://user-images.githubusercontent.com/67801043/149534221-39a1af59-5dfd-4189-b7dc-0dfad4957e94.png)

but what about the other settings?

does the root device setting override the feature setting, or what?

**Comment by rjhelmke** [comment]
They all apply only to the feature or root except for the 2 hide options.
