### ISSUE TITLE
Not all devices are showing

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#256]
Please have a look at the user issue.  Only three child devices are shown, but there's many more devices created by the plugin, which for some reason are not displayed:

https://forums.homeseer.com/forum/hs4-products/hs4-plugins/weather-plug-ins-aa/akweather-alexbk66/1525508-not-all-values-showing#post1525796

**Comment by alexbk66** [comment]
![image_109644](https://user-images.githubusercontent.com/2533315/152789630-a2dcbdfb-5934-49ea-b3b9-2a38e1fcad6e.png)
![image_109643](https://user-images.githubusercontent.com/2533315/152789663-9e33a18d-006f-4a94-ab4b-ab5cee1f5410.png)

**Comment by alexbk66** [comment]
![image_109644](https://user-images.githubusercontent.com/2533315/152789749-3a346a59-a27c-4432-9a1b-b5fbb5e4e743.png)

**Comment by rjhdakota** [comment]
I asked the user to send me their devices.json file so I can recreate the issue.

**Comment by rjhelmke** [comment]
User had changes to the location of some of the features and did not realize it.
