### ISSUE TITLE
Device controls and status dont work consistently

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#257]
@spudwebb,

@rjhdakota asked me to start this thread here:

i have the following setup for my dimmer lights (see pic below)

I want the slider to go from Off (0) to On (100) and anywhere in between. So I set the On & Off controls to different values and handle this in my setmultiIO routine.

this all works just fine from the HS UI

However I'm getting user reports that it doesn't work from Alexa (any dim value is converted to an Off)

I haven't confirmed the behavior from HS Touch

I would expect alexa, hs touch, and the hs UI to all work the same based on my settings

![image](https://user-images.githubusercontent.com/67801043/152847555-b8fd8778-9ed7-4322-8949-62d3fde4f494.png)

**Comment by spudwebb** [comment]
sounds like a problem specific to the Alexa integration, can you post the logs that the user gets when the tries to speak the command, and what exact command is it?

**Comment by mnsandler** [comment]
@spudwebb 

here is what the user sees in the hs log when the dim range starts with 0. Apparently the same thing happens with z-wave if you change the dim start to 0.

`2/7/2022 4:56:31 PM HomeSeer Device Control Device: Home Office Light to (value) (0) by/from: CAPI Control Handler`

**Comment by jldubz** [comment]
Tracking this internally as ALEXA-25. The team that handles the Alexa integration is looking into this and will be in touch. Thank you for the report.

**Comment by mnsandler** [comment]
Any movement or timeframe for a resolution

**Comment by mnsandler** [comment]
i believe this is resolved in 4.2.12.0
