### ISSUE TITLE
Control device via JSON request "setdevicestatus" - is there any way to be notified in the plugin?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#262]
If I have a status only device and want to control it via JSON request "setdevicestatus" - is there any way to be notified in the plugin?  
I.e. HsEvent works for "controldevicebyvalue", but since my devices don't have controls - I can't use it.

`/JSON?request=setdevicestatus&ref=1817&value=2`

BTW, https://docs.homeseer.com/display/HSPI/setdevicestatus missing "&ref=" parameter

**Comment by rjhdakota** [comment]
When you set the status of a device, that should change the string value also, so check the STRING_CHANGE HSEvent, that might do what you want.

**Comment by rjhelmke** [comment]
Are you ok with my suggestion or do you need us to add something?

**Comment by alexbk66** [comment]
I still need to test, thank you

**Comment by spudwebb** [comment]
Please reopen is the suggested solution is not ok.

**Comment by alexbk66** [comment]
BTW, https://docs.homeseer.com/display/HSPI/setdevicestatus is still missing "&ref=" parameter
