### ISSUE TITLE
Setting suffix for value range in code

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#263]
I posted in the forum, please help.

https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-plugin-development/1529922-setting-suffix-for-value-range-in-code

I can copy here as well if necessary

**Comment by jldubz** [comment]
@alexbk66, I'll take a look today/tomorrow. New PSDK version incoming.

**Comment by spudwebb** [comment]
I responded to @alexbk66 in the forum, unless he has further questions, I think this issue can be closed

**Comment by alexbk66** [comment]
Yeah, thanks @spudwebb
