### ISSUE TITLE
How can I support users who didn't upgrade HS from 4.2.8?

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#266]
I appreciate that you need to change HS code, but now I'm confused as to how can I support users who didn't upgrade HS from 4.2.8?

To explain the problem - you removed EProperty.Status, so in my plugins I change EProperty.DisplayedStatus, but HS 4.2.8 (PSDK 1.3) doesn't have it.

So it looks like there are two options - either force users to always upgrade to latest HS (BETA), or somehow build different plugin versions for different HS version?

Similar issue here https://forums.homeseer.com/forum/hs4-products/hs4-plugins/weather-plug-ins-aa/akweather-alexbk66/1470270-akweather-features-requests?p=1531669#post1531669

**Comment by alexbk66** [comment]
Usual practice is to #define the version, so in my code I cam use preprocessor directive "#if defined" to check the version.

**Comment by mnsandler** [comment]
I just require users to upgrade the hs version if I need it to be compatible with my plugin version. You can put this requirement check in your install.txt filed.
there is no sense is managing different hs versions within your plugin code.

**Comment by alexbk66** [comment]
I understand.  But it also means that if I upgrade one plugin - I have to upgrade (and test) them all (13)

**Comment by mnsandler** [comment]
that still seems more straight forward than adding a bunch of #define statements to manage different versions of HS within your code; that will eventually get annoying.

**Comment by spudwebb** [comment]
As @mnsandler  pointed out the recommended solution is to use the [CHECKVERSION] command in your install.txt
