### ISSUE TITLE
Thermostat device in grid view

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#267]
I'm trying to find out how to properly setup thermostat child devices so they show nicely in the grid view.

I already worked out how to display current temperature, temperature set points, and heat and fan modes controls.

But I don't know how to show current heat and fan mode icons - I think they should be left to "AUTO" buttons?

Also, can you lease provide may be some doco on what can be displayed on the thermostat grid view and how?  

I think I asked before (more than once)

![image](https://user-images.githubusercontent.com/2533315/159390741-fd9bc309-efab-487f-8383-c3e0807ce4e5.png)

![image](https://user-images.githubusercontent.com/2533315/159391528-66dbf36e-7b58-439b-bba1-d989d3c8701d.png)

**Comment by spudwebb** [comment]
see #269
