### ISSUE TITLE
Request - Code example for building a HS4 thermostat

### ISSUE THREAD

**Issue by rmasonjr** [HomeSeer/Plugin-SDK#269]
The sample plugins are very sparse when it comes to examples on how to build root/feature devices.
Would you guys give us an example of building a simple thermostat device?
This would be a good example since it shows:

- Root/Feature creation
- Status features
- Control features 
- Ranges with images
- Alexa/Google Voice Control

As it stands now, I'm flying blind on creating a true HS4 thermostat and relying on using my old HS3 code to build a thermostat.

Thanks
Rob

**Comment by alexbk66** [comment]
I just asked this
https://github.com/HomeSeer/Plugin-SDK/issues/267
https://github.com/HomeSeer/Plugin-SDK/issues/268

**Comment by alexbk66** [comment]
And I did work out how to build a thermostat (kind of) https://forums.homeseer.com/forum/hs4-products/hs4-plugins/thermostat-hvac-plug-ins-aa/ak-heatmiserneo-alexbk66-aa/1453963-akheatmiserneo-plugin-for-heatmiser-uk-neohub

But it's a pain, I agree.

![image](https://user-images.githubusercontent.com/2533315/160131844-16a53737-631f-4d10-bbba-ac5609b0043d.png)

**Comment by spudwebb** [comment]
We will add a thermostat example to the sample plugins.
Tracked as PSDK-266

**Comment by rmasonjr** [comment]
Please be sure to include how to convert the following from HS3 to HS4:

        DT = New DeviceTypeInfo
        DT.Device_API = DeviceTypeInfo.eDeviceAPI.Thermostat
        DT.Device_Type = DeviceTypeInfo.eDeviceType_Thermostat.Setpoint
        DT.Device_SubType = DeviceTypeInfo.eDeviceSubType_Setpoint.Cooling_1
        dv.DeviceType_Set(hs) = DT

thanks!

**Comment by alexbk66** [comment]
> Please be sure to include how to convert the following from HS3 to HS4:
> 
> ```
>     DT = New DeviceTypeInfo
>     DT.Device_API = DeviceTypeInfo.eDeviceAPI.Thermostat
>     DT.Device_Type = DeviceTypeInfo.eDeviceType_Thermostat.Setpoint
>     DT.Device_SubType = DeviceTypeInfo.eDeviceSubType_Setpoint.Cooling_1
>     dv.DeviceType_Set(hs) = DT
> ```

That's what I do in HS4
![image](https://user-images.githubusercontent.com/2533315/160220120-3bc98eb3-7d36-4ab5-b972-d457716d92c6.png)

Where for root device:
Device_Type = EDeviceType.Thermostat
Device_SubType = 0;

And for Current temperature feature:
Device_Type = (int)EFeatureType.ThermostatStatus
Device_SubType = (int)EThermostatStatusFeatureSubType.Temperature


And for Set temperature feature:
Device_Type = (int)EFeatureType.ThermostatControl
Device_SubType = (int)EThermostatControlFeatureSubType.HeatingSetPoint

**Comment by rmasonjr** [comment]
Bumping for an ETA on this?

**Comment by spudwebb** [comment]
Plugins SDK version 1.4.1, which contains C# and VB .NET plugin samples with a thermostat example, is almost ready to be released.
So  ETA = next week.

**Comment by rmasonjr** [comment]
Bumping for new ETA?

**Comment by jldubz** [comment]
@rmasonjr 
> Bumping for new ETA?

Check the latest release and the tag above.

https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_4_1_0.html

**Comment by rmasonjr** [comment]
Thanks. It really would be a great example on how to tackle the things we are running into. Maybe it will get more visibility m

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 25, 2022 at 8:37 AM, Alex ***@***.***> wrote:   


I just asked this
#267
#268
