### ISSUE TITLE
Displaying multiple features values in Grid View

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#270]
If my device has 2-4 temperature readings (features) - can I show them in the Grid View?

**Comment by rjhelmke** [comment]
I assume this is for a thermostat device? Thermostat device types use different HTML to generate the grid view and it uses the device types as set in the feature. I think right now we only have one device type for the temperature. The 2 options are I see are to add more device types for more temps or a better option might be to allow the developer to specify their own HTML for the grid view.

**Comment by rjhelmke** [comment]
Can you put each temp in it's own feature? The grid can display up to 5 features (status). You can assign these as important so they all display by default in the grid.

**Comment by alexbk66** [comment]
They obviously are in it's own feature.  How do I assign these as important?

**Comment by alexbk66** [comment]
Ok, worked it out, thank you

![image](https://user-images.githubusercontent.com/2533315/160602531-bde6e6ed-44c5-4a1d-8f46-ac10f465ebce.png)

**Comment by alexbk66** [comment]
One question though, how do I control the display order?  Setting "EProperty.FeatureDisplayPriority" doesn't seem to work.

HsDevice.FeatureDisplayPriority comment says "This should typically be left to the user to configure" - that's great, but how/where can user configure the FeatureDisplayPriority?

![image](https://user-images.githubusercontent.com/2533315/160608084-4a059bac-a591-4c4e-b4d6-fdf18f27ed77.png)

**Comment by spudwebb** [comment]
Edit the root device, then go to the features tab, from there you can change the display type and the priority order using the arrows or drag and dropping.
Note that you are supposed to be able to set the priority from the SDK too.
![image](https://user-images.githubusercontent.com/5427056/160612347-8e3316f2-26b8-49fb-89cb-1f3c9dde9534.png)

**Comment by alexbk66** [comment]
Thank you @spudwebb, I didn't see this.

As I said, setting the priority from code didn't seem to work, I use hs.UpdatePropertyByRef(EProperty.FeatureDisplayPriority) - do I need to call some other Update function after that?

**Comment by spudwebb** [comment]
What parameter are you passing to UpdatePropertyByRef ? Does it throws an exception?

I just tested with the following code line and it worked:
`HomeSeerSystem.UpdatePropertyByRef(999, EProperty.FeatureDisplayPriority, new List<int>() { 1000, 1001 });`

where 999 is the ref of the parent device, and 1000 and 1001 are the ref of the 2 child features.

**Comment by alexbk66** [comment]
Ah, no, I just pass priority int - it's unclear what to pass, especially because the name is singular.
Hmm, so if I want to set the feature priority - I can't do it inside the feature class itself.  I need to do it in the root (parent)...
And I need to know the complete list of children and the priority of each child.  Really inconvenient...

**Comment by alexbk66** [comment]
Really inconvenient.  Because if I add another child later - I need to re-arrange the whole list ;(
