### ISSUE TITLE
running hs 4.2.11.2..new startup error

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#275]
@rjhelmke 

I also noticed on restarting the plugin this message: "File does not exist: C:\Program Files (x86)\HomeSeer HS4\html\Insteon\bootstrap\css\addons-pro\steppers.min.css". The CSS is found under "\HomeSeer HS4\html\bootstrap\css\addons-pro".

**Comment by spudwebb** [comment]
Do you still have this problem?
If so, make sure your plugin feature pages do not have a bad href to this css file, it should be:
`<link href="../bootstrap/css/addons-pro/steppers.min.css" rel="stylesheet">`
and not
`<link href="bootstrap/css/addons-pro/steppers.min.css" rel="stylesheet">`

**Comment by mnsandler** [comment]
i dont see this anymore.
