### ISSUE TITLE
will hs.pluginfunction work between an hs3 plugin and hs4 plugin

### ISSUE THREAD

**Issue by mnsandler** [HomeSeer/Plugin-SDK#276]
i want to use the subject call from an hs3 plugin to make a call to an hs4.plugin

should this work when both plugins are running on HS4?

@johnwilley2

**Comment by mnsandler** [comment]
got it working. the hs.pluginfunction uses the destination plugin name not the plugin id.

**Comment by jldubz** [comment]
@mnsandler you asked this same question about 6 months ago https://github.com/HomeSeer/Plugin-SDK/issues/235

> Sorry for any confusion here. HS3 plugins do not know about any HS4 features. The reason why is because the HS3 plugin calls are routed through legacy code which has no knowledge of HS4 plugins. This is because the HS3 Plugin API is being discontinued. No more enhancements will be made to it, which includes handling routing to and communication with HS4 plugins. The HS3 Plugin API will only receive patches to critical/blocking issues for the time being.
> These HS3 plugins that are communicating with your HS4 plugin can continue to use the HS3 plugin version, but they will need to be migrated to HS4 to integrate with your HS4 plugin.

This functionality is not actively supported and may misbehave. We have no plans to support it and you should know that it will be disabled as the HS3 API is shut down. I highly recommend that you focus your efforts on HS4 plugin development.
