### ISSUE TITLE
ButtonView

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#278]
[ButtonView.cs.txt](https://github.com/HomeSeer/Plugin-SDK/files/8694643/ButtonView.cs.txt)
Stupid question, I have ButtonView.cs (attached) in my Plugin-SDK\Jui\Views folder, but it's not part of PluginSdk project. Any idea where it's from?

**Comment by spudwebb** [comment]
The ButtonView.cs file was in SDK, but was never compiled. Since version 1.4.0.0 it has been replaced by NavigateButtonView.cs which you can use:
https://github.com/HomeSeer/Plugin-SDK/commit/94a18bb7a9b7905628d8dfe388a03e3eddec4487
