### ISSUE TITLE
Exception "A view with that ID already exists in the collection"

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#279]
Just a small enhancement request - can you please add the ID to the this exception (and others too) - otherwise diagnostics of the issue is a pain.

Thank you.

**Comment by spudwebb** [comment]
sure, tracked as PSDK-278

**Comment by jldubz** [comment]
Change has been submitted in #299 for release in v1.4.2.0 alongside v4.2.14.0 of HomeSeer. Add comments to the pull request if there are any issues with the change.
