### ISSUE TITLE
HS-1266	 Add status bar for media player card in grid view

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#280]
I saw this new feature in the 4.2.13.0 release notes.  How do I use it from the plugin?

**Comment by spudwebb** [comment]
You have nothing to do. What is called the status bar here is the list of features at the top of the card. Before this version this wasn't showing for media cards.

![image](https://user-images.githubusercontent.com/5427056/173358537-2a07d9e1-6037-4e71-be87-3a48fb807a0c.png)
