### ISSUE TITLE
Due to a lack of ValueRange.Divisor control cannot be created at this time

### ISSUE THREAD

**Issue by rmasonjr** [HomeSeer/Plugin-SDK#281]
#### OS
[Windows, Linux, etc]
#### HS Version
[v4.2.9.0]
#### PSDK Version
[v1.4.0.0]
#### Language
[VB or C#]
#### IDE
[VS2017, VS2019, JetBrains Rider, etc]
#### Dev OS
[Windows, Linux, Mac]
### Plugin
What plugin is this issue for?

### Description
Describe the issue you are encountering. What happened?

### Expected Behavior
What did you expect to happen?

### Steps to Reproduce
Provide steps so the HomeSeer team can reproduce the reported problem:

### Logs
If applicable, include log output from the plugin console and/or the HomeSeer logs. *If the logs take up more than a few lines, consider attaching a file.*

**Comment by rmasonjr** [comment]
I'm using the new thermostat example plugin, and I'm getting this message:

 Dim range = New ValueRange(0, 100) With {
                .DecimalPlaces = 1,
                .Suffix = " %"
            }
        ff.AddValueDropDown(range, New ControlLocation(1, 1), EControlUse.NotSpecified)

Public Overloads Function AddValueDropDown(targetRange As ValueRange, [location As ControlLocation = Nothing], [controlUse As EControlUse = NotSpecified]) As FeatureFactory' is obsolete: 'Due to a lack of ValueRange.Divisor property this control type cannot be properly created at this time.'.

Thanks
Rob

**Comment by spudwebb** [comment]
A Divisor property or something similar is planned to be added soon, but the message you see is just a compilation warning, for a range of 0-100 your code should just work fine as is.

**Comment by rmasonjr** [comment]
So, how do we make a dropdown list with celsius values?
In the code above, I tell it 1 decimal place, but the dropdown list has whole integers (with .0)
A celsius dropdown list should have 25.0, 25.5, 26.0, 26.5, etc.

**Comment by spudwebb** [comment]
To display half degrees in the list we need to implement the divisor property. Tracked as PSDK-112

**Comment by sjhill01** [comment]
My thermostat customers using Celsius are also held up by the lack of this property. +1 begging for it.

**Comment by sjhill01** [comment]
This is going to require more than just PSDK code I assume, since at a minimum the html will need to be updated for the feature status control options dialog. I can submit a pull with the divisor property and the value range GetStringForValue method, plus the associated test cases with a non-1 divisor, but I don't see that method being called when generating the dropdown list so I'm not sure how helpful that is at this point.

**Comment by rjhelmke** [comment]
I have a build you can test, please report if this is working ok for you. You can set the Divisor on the range object like:
`
                ValueRange range = new ValueRange(1, 100);
                range.DecimalPlaces = 1;
                range.Divisor = 10;
                ff.AddValueDropDown(range);
`

Here is the test build for Windows:
https://homeseer.com/updates4/SetupHS4_4_2_18_10.msi

Many thanks to sjhill01 for the pull request.

**Comment by rmasonjr** [comment]
Thanks Rich - the PluginSDK.dll in that install works fine:

![image](https://github.com/HomeSeer/Plugin-SDK/assets/11462627/21aacc27-7621-427e-9a4b-3cdae72b6263)

![image](https://github.com/HomeSeer/Plugin-SDK/assets/11462627/db1a141a-32e8-487d-98f9-b36661a1f541)

**Comment by spudwebb** [comment]
@rmasonjr why does the current value is displayed as 74.0 ? Shouldn't it be 37 with a " C" suffix?

**Comment by rmasonjr** [comment]
@spudwebb  oh wow - good catch.

I'm looking at the html code that was built for the dropdown and it contains the F values - maybe @rjhelmke can confirm?

Here's the html code that the PluginSDK generated:

![image](https://github.com/HomeSeer/Plugin-SDK/assets/11462627/56e61e66-336b-4d82-9332-36799df853d1)

![image](https://github.com/HomeSeer/Plugin-SDK/assets/11462627/e05b1168-9188-4ecd-91ab-b2adf9990bc8)

**Comment by rjhelmke** [comment]
@rmasonjr @spudwebb  You actually set the value on the device from your plugin so I would say that you should take the value submitted and then divide it by your divisor and set the value. We could do this in HS but I am not sure of the ramifications. I checked this in the HS3 UI and it works the same.

**Comment by spudwebb** [comment]
@rmasonjr you have to define your StatusGraphic range with the same range options than the control range. You can't do that using AddGraphicForRange, so use AddGraphic() instead

```csharp
                var sg = new StatusGraphic(IMAGES_STATUS_DIR + "Thermometer-00.png", -200, 200);
                sg.TargetRange.DecimalPlaces = useCelsius ? 1 : 0;
                sg.TargetRange.Suffix = useCelsius ? " °C" : " °F";
                sg.TargetRange.Divisor = useCelsius ? 2 : 1;
                ff.AddGraphic(sg);
```
Also if you're not using the divisor (F case) it needs to be set to 1, not 0

Remember that the divisor will be used to display any value of this feature in the UI. So for example if you set the value of this temp feature to 50 using UpdateFeatureValueByRef(), the real value of the feature will be set to 50, but the displayed value will be set to "25  °C"

we are going to update the sample plugin thermostats to show how to use that new Divisor property:

![image](https://github.com/HomeSeer/Plugin-SDK/assets/5427056/c9ac49b7-2a1f-483b-88d9-b953451d4b9a)

**Comment by spudwebb** [comment]
> @rmasonjr @spudwebb You actually set the value on the device from your plugin so I would say that you should take the value submitted and then divide it by your divisor and set the value. We could do this in HS but I am not sure of the ramifications. I checked this in the HS3 UI and it works the same.

The value submitted is actually the non-divided value, i.e if you select 37 from the dropdown list, the value received in SetIOMulti is 74, and the plugin should set this same value 74 using UpdateFeatureValueByRef to get 37 as the current value, (assuming the status graphic range uses the same divisor as explained in my previous post)

**Comment by rmasonjr** [comment]
Holy cow - this is really confusing.  I dont remember having to manually divide a value by a divisor in the HS3 plugin.

When a thermostat setpoint is set at the unit, my plugin would receive 23.5 C, I would set the value to 23.5 and the status text would be 23.5 °C

When a thermostat setpoint is set in the HS device page, the user would select 24.0 from the dropdown, I would send the value 24.0 to the OMNI, then the status text would be 24 °C

In your example, why wouldnt the 37 from the dropdown send 74?  Why not just send 37?

All I am trying to do is get .5 precision in the dropdown.

**Comment by rmasonjr** [comment]
@spudwebb @rjhelmke - any ideas on getting .5 precision for the dropdown?

**Comment by rmasonjr** [comment]
I'm not understanding why I need to divide - never had to do that with an HS3 thermostat setpoint.

Maybe Divisor is not what I'm looking for.

I need a dropdown with celsius values in .5 precision for both the selection and the value in the HTML.
So, when the user selects 37.5, from the dropdown, I send 37.5 to the thermostat.
I dont want to take 74 and divide it by a divisor and send it.
A dropdown should just send the real value of the selection.

Am I not using the ValueRange object correctly?  Here's my code:

```
 Dim vr = New ValueRange(-39, 122) With {
                .DecimalPlaces = IIf(useCelsius, 1, 0),
                .Suffix = IIf(useCelsius, " °C", " °F"),
                .Divisor = IIf(useCelsius, 2, 1)
 }

```

**Comment by rmasonjr** [comment]
Please make a step property.  As it stands now, ValueRange is not useful for a celsius control/value.
Even the sample plugin is wrong - BuildSetpointFeature is just building a dropdown with whole numbers.  The increment/decrement controls do allow you to change it, but the dropdown does not contain those .5 values.

I'm going to make it a textbox for now instead of a dropdown.  I hate doing that, but there's not a better way.  Dividing by the divisor just seems crazy to me.

Thanks
Rob
