### ISSUE TITLE
HSTouch: Cannot control the thermostat. There is a problem with the set point control configuration

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#296]
User has an issue with thermostat control https://forums.homeseer.com/forum/hs4-products/hs4-plugins/thermostat-hvac-plug-ins-aa/ak-heatmiserneo-alexbk66-aa/1555206-heatmiser-and-hs-mobile

Please advise.

![image](https://user-images.githubusercontent.com/2533315/177132362-d367aba8-3b27-410d-990f-20b5cc8bf617.png)

**Comment by alexbk66** [comment]
System info:

Date/time=4/07/2022 10:17:10 PM AUS Eastern Standard Time
Version=HS4 Standard Edition 4.2.13.0 (Windows)
License=Registered
Confguration File=C:\Program Files (x86)\HomeSeer HS3\Data\HomeSeerData.json
In Virtual Machine=No MFG: asrock
Antivirus=AVG Antivirus
OS=Microsoft Windows 7 Home Premium - Work Station
OS Version=6.1.7601
Uptime=2 Days 6 Hours 54 Minutes 54 Seconds
Lan IP=192.168.20.35 (JP-PC)
Device Count=430
Event Count=46
Processor:=Intel64 Family 6 Model 58 Stepping 9 at 3.17 GHz
Modules/Threads=136 Modules, 86 Threads
Available Threads=1023
System Load=156 Processes, 7% Load
Free/Total Memory=2.00 GBytes / 7.70 GBytes (26% free)
Free/Total Virtual Memory=12.62 GBytes / 22.78 GBytes (55% free)
HomeSeer Memory Used=136 Mbytes
Plugin Memory Used=10 EXE Plug-Ins using 403 Mbytes
Plugins Installed=AK HeatmiserNeo 4.0.0.12,BLOccupied 2.0.28.0,BLSecurity 2.0.48.0,HSBuddy 3.28.1222.5,IntesisWMP 4.0.0.9,LIFX 4.0.7.0,Pushover 3P 0.0.0.52,rnbWeather 4.4.0.0,Z-Wave 3.0.10.0,Z-Wave UI 1.0.0.0

**Comment by alexbk66** [comment]
I found this old HS3 thread, I'll if it helps.

https://forums.homeseer.com/forum/developer-support/programming-plug-in-development/hs3-plugin-development-private/1343694-device-layout-to-display-properly-in-hs-mobile

**Comment by jldubz** [comment]
@alexbk66 ,

This is not HSTouch. That looks like HomeSeer Mobile for Android. Please submit a ticket through the support portal https://dev.homeseer.com/servicedesk/customer/portal/8
