### ISSUE TITLE
You must specify a valid control type Parameter name: type Actual value was StatusOnly

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#297]
Did you finally decided to introduce the exception for StatusOnly?
It was there for years - was wrong to have it in the first place - but now my plugins (16) are broken - and I don't have time to fix and test them!
![image](https://user-images.githubusercontent.com/2533315/177328063-130fc089-1c9f-4778-823d-e79228e3eebf.png)

**Comment by spudwebb** [comment]
@alexbk66 if you look at the code for the constructor of StatusControl, the exception when type=StatusOnly  has been there since 2019, so not sure why you see this only now? What does your calling code look like?

**Comment by alexbk66** [comment]
@spudwebb , yeah, I checked your version tree, I agree it couldn't work.

But my code also didn't change since I ported from HS3. I'm trying to dig deeper to see what's changed.  

![image](https://user-images.githubusercontent.com/2533315/182266506-313dcb62-c82f-42b7-a7b8-723406e2c4c1.png)
