### ISSUE TITLE
IsValueValidForType does not allow empty strings

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#30]
In my actions a user can decide to fill a field with a number and at another moment decide to erase the field and use another field.

I have defined the view as follows

` New InputView(IDInputBri, "Bri (0-255)", EInputType.Number)`

If the view is changed I check the value with  `view.GetStringValue`. If the user has erased the field I get an empty string as result.

This will result in an error "The new value is invalid for the input type" by the chcks done by InputView.cs.

Could you please change this behaviour so a empty value is accepted, so a user can erase a field when needed?

**Comment by jldubz** [comment]
Changing [InputView.cs Line 113]() to `return float.TryParse(string.IsNullOrWhiteSpace(value) ? "0" : value, out _);` to handle possible blank/null strings

This will be added into the next release

**Comment by jldubz** [comment]
Thank you for following up with this
