### ISSUE TITLE
TrigActInfo.ConvertLegacyData is being called a lot

### ISSUE THREAD

**Issue by rmasonjr** [HomeSeer/Plugin-SDK#306]
#### OS
[Windows]
#### HS Version
[v4.2.14.0]
#### PSDK Version
[v1.4.2.0]
#### Language
[VB]
#### IDE
[VS2017]
#### Dev OS
[Windows]
### Page
Events
### Plugin
OMNI

## Problem
When I launch the Events page in HS, my plugin code is being called a lot, specifically, ConvertLegacyData.

Also, ConvertLegacyData never deserializes my legacy trigger info.  I always get Nothing (no exceptions thrown).

### Description
Describe the issue you are encountering. What happened?

#### Screenshots
Attached screenshot showing breakpoint
![screenshot1](https://user-images.githubusercontent.com/11462627/180269957-025f8597-0a06-4e1d-9a35-faddf01b58f0.png)

### Steps to Reproduce
Provide steps so the HomeSeer team can reproduce the reported problem and see the same thing:

### Logs
If applicable, include log output from the plugin console and/or the HomeSeer logs. *If the logs take up more than a few lines, consider attaching a file.*

**Comment by jldubz** [comment]
@rmasonjr can you provide clear steps to reproduce and attach logs showing a trace of what you are experiencing?

**Comment by rmasonjr** [comment]
In the screenshot, if you override the ConvertLegacyData function, add a breakpoint as shown, then launch the Events page.  The function is called 4 times and no legacy trigger data is ever pulled in.

**Comment by rmasonjr** [comment]
Cancel this issue.  It looks like it is being called once per trigger, which I think is the intended behavior.
