### ISSUE TITLE
Speaker host attempted to connect: Object variable or With block variable not set.

### ISSUE THREAD

**Issue by alexbk66** [HomeSeer/Plugin-SDK#309]
In AKGoogleCast plugin I'm getting the error in log for only one Chromecast, all other devices connect ok.
And even the Chromecast which gives the error still connects and works fine.

Just wondering what can be causing the error and how I can troubleshoot it?  Is it possible to add more info to the error?

![image](https://user-images.githubusercontent.com/2533315/183880043-d4be81ff-1fab-421f-8a97-66c827037298.png)
![image](https://user-images.githubusercontent.com/2533315/183880275-6dbcf50c-1fb1-429c-8279-46a11ae8f9e9.png)

**Comment by rjhelmke** [comment]
Does this happen all the time or is it random? It looks like a bunch of speaker clients were connecting. There is an array that stores the list of hosts, maybe there is an issue accessing that from multiple threads. I will add a lock to see if that helps. If you just have that one client connect, does it then connect ok? Is it always that client that gets the error?

**Comment by rjhelmke** [comment]
Logged as HS-1702

**Comment by alexbk66** [comment]
It always happens to the same device on start-up.  I disabled all other devices - still happens.  BTW, I do have lock in my plugin when adding speakers.  So must be some different issue. Interesting that it's still connecting ok.

![image](https://user-images.githubusercontent.com/2533315/184051426-d4483312-9ded-4c37-b425-da7080dc7efb.png)

**Comment by rjhelmke** [comment]
Can you try HS4 build 4.2.14.4 and post any new error messages you see.
https://homeseer.com/updates4/SetupHS4_4_2_14_4.msi

**Comment by alexbk66** [comment]
Thank you Rich, 4.2.14.4 seems to fix the issue.

Just in case I verified before installing the update, the exception was there. Now there's no errors:

![image](https://user-images.githubusercontent.com/2533315/184788746-de3d7973-d890-489c-85dd-0d69bb528123.png)

**Comment by rjhelmke** [comment]
Ok, good. I will close this issue for now.
