### ISSUE TITLE
Better feedback for install.txt [CHECKVERSION]

### ISSUE THREAD

**Issue by BernoldNL** [HomeSeer/Plugin-SDK#311]
#### OS
Windows
#### HS Version
4.2.14.0, 4.2.13.0
#### PSDK Version
N/A
#### Language
N/A
#### IDE
N/A
#### Dev OS
N/A
### Page
What page did you encounter this on?
shop.html
### Description
When you set a required minimum version in install.txt with the [CHECKVERSION] command and the HS4 version is lower, you will get a general failure message: **Installation of package <pluginname> failed. Try disabling the plugin first, then re-try the update.** You will get this message even if the plugin is not enabled or even installed yet. This is not user friendly. A user may try disabling an installed older version of the plugin and still can't install the newer version.

#### Screenshots
Attach screenshots showing what you are seeing.
N/A

### Expected Behavior
What did you expect to see?
A message like this: **This plugin requires version <parameter 3 of [CHECKVERSION]> of HomeSeer.** 

### Steps to Reproduce
Provide steps so the HomeSeer team can reproduce the reported problem and see the same thing:
See above.

### Logs
If applicable, include log output from the plugin console and/or the HomeSeer logs. *If the logs take up more than a few lines, consider attaching a file.*
N/A

**Comment by spudwebb** [comment]
Tracked as HS-1707

**Comment by spudwebb** [comment]
This has been implemented in HS4 version 4.2.16.7
