### ISSUE TITLE
Error while saving value on action config page

### ISSUE THREAD

**Issue by jldubz** [HomeSeer/Plugin-SDK#33]
Per @wvuyk in https://github.com/HomeSeer/Plugin-SDK/issues/28

> If a user fills a field with a value and then after saving the action erases it, the PluginSDK will throw an error when this is saved:
> 
> ```
> HomeSeer.Jui.Views.InvalidValueForTypeException: The new value is invalid for the input type
>    bij HomeSeer.Jui.Views.InputView.Update(AbstractView newViewState)
>    bij HomeSeer.Jui.Views.ViewCollectionHelper.UpdateViewById(AbstractView view, List`1& viewList, Dictionary`2& viewIds)
>    bij HomeSeer.Jui.Views.Page.UpdateViewById(AbstractView view)
>    bij HomeSeer.PluginSdk.Events.AbstractActionType.OnEditAction(Page viewChanges)
>    bij HomeSeer.PluginSdk.Events.AbstractActionType.ProcessPostData(Dictionary`2 changes)
>    bij HomeSeer.PluginSdk.Events.ActionTypeCollection.OnUpdateActionConfig(Dictionary`2 postData, TrigActInfo actInfo)
> ```
> 
> This is not caused by something the plugin initiated, I think this is during internal processing of the views during the save of the action. Maybe the pluginsdk is not expecting a field to be emptied by a user?

Further investigation is needed to determine the root cause of this issue.

**Comment by wvuyk** [comment]
After rethinking this issue I think this might be related to #30

**Comment by jldubz** [comment]
@wvuyk 

You are correct. It looks like this issue, #30, and #34 are caused by the same thing - a failure to do an empty string check at the head of the IsValueValidForType method.  I've added a fix that will be included in the next build.

**Comment by wvuyk** [comment]
@jldubz Jon-Luke,

#34 does not belong to this list as the code for Decimal seems to missing completely missing for the EInputType.Decimal in the underlying routine. I am not really good at inputting the right code here in C#, but still miss the `case EInputType.Decimal` I guess here? This is a different issue... And please accept the decimal points in all locations?
 
```
		/// <summary>
		/// Check if the value is valid for the type set on the input view
		/// </summary>
		/// <param name="value">The value to check</param>
		/// <returns>TRUE if the value is valid for the type or FALSE if it is not</returns>
		public bool IsValueValidForType(string value) {

			switch (InputType) {
				case EInputType.Text:
					//Anything is valid for text
					return true;
				case EInputType.Number:
					return float.TryParse(value, out _);
				case EInputType.Email:
					try {
						var address = new System.Net.Mail.MailAddress(value);
						return address.Address == value;
					}
					catch (Exception) {
						return false;
					}
				case EInputType.Url:
					return Uri.TryCreate(value, UriKind.Absolute, out _);
				case EInputType.Password:
					//Password types merely restrict the visibility of characters not the input
					return true;
				default:
					return false;
			}
		}
		
```

**Comment by wvuyk** [comment]
@jldubz Jon-Luke

#34 does not belong to the same issue as this is referring to EInputType.Decimal. When I look at the routine in the pluginSDK, catching the different InputTypes, it misses to check (on decimals) on EInputType.Decimal completely:

```
public bool IsValueValidForType(string value) {

			switch (InputType) {
				case EInputType.Text:
					//Anything is valid for text
					return true;
				case EInputType.Number:
					return float.TryParse(value, out _);
				case EInputType.Email:
					try {
						var address = new System.Net.Mail.MailAddress(value);
						return address.Address == value;
					}
					catch (Exception) {
						return false;
					}
				case EInputType.Url:
					return Uri.TryCreate(value, UriKind.Absolute, out _);
				case EInputType.Password:
					//Password types merely restrict the visibility of characters not the input
					return true;
				default:
					return false;
			}
		}
```

I guess this should be added to the code, of course making sure international decimal points will be accepted as well. Not confident to add this code myself (as vb plugin editor) so I hope you can complete this part?

Wim

**Comment by wvuyk** [comment]
apart from #34 this seems to be solved....

**Comment by jldubz** [comment]
Thank you @wvuyk
