### ISSUE TITLE
EInputType.Decimal does not work as expected with triggers/actions

### ISSUE THREAD

**Issue by jldubz** [HomeSeer/Plugin-SDK#34]
Per @wvuyk in https://github.com/HomeSeer/Plugin-SDK/issues/28

> The second issue is for InputViews created with `EInputType.Decimal` :
> 
> `New InputView(IDInputY, "Y (between 0 and 1, 4 behind decimal point)", EInputType.Decimal)`
> 
> It does not matter what I try to do here, inputting 0.1 or 0,2 or 1 (or even 'abc' is accepted here.)....
> When this gets saved a popup comes telling the "new value is invalid for the input type"
> It seems this needs some attention?

Further investigation is needed to determine the root cause of this issue.

**Comment by wvuyk** [comment]
Ther has been mention of the EInputType.Decimal issue being solve. Tested it, but it is still not correct as it is accepting any characters?

**Comment by jldubz** [comment]
@wvuyk 

EInputType.Decimal uses the following HTML for the input
`<input type="text" pattern="[0-9.]*" id="{Id}" class="form-control jui-input" value="">`

It looks like the pattern attribute is not respected unless it is submitted in a `<form>` tag.  Switching to the step attribute with a number type fixes this.

I will include this in the next release.

**Comment by jldubz** [comment]
@wvuyk 

This should be included in v1.0.8.0 of the PluginSDK. See commit https://github.com/HomeSeer/Plugin-SDK/commit/450fe1e7a1faf97f511fe04230d21bea08031df3

switched from
`typeString = "text\" pattern=\"[0-9.]*\" ";`
to
`typeString = "number\" step=\"0.001\" ";`

Let me know if you need the ability to adjust the precision; there are other pressing development efforts unless someone expresses an urgent need for this.

Have a great weekend.

**Comment by wvuyk** [comment]
@jldubz Jon

I have checked the EInputType.Decimal here with the V1.0.8.0 version, but it will still accept any input, including alphabetic chars. So I do not think this works still?

**Comment by jldubz** [comment]
@wvuyk I super apologize for the delay.

Every time I try to type a letter into an InputView marked as EInputType.Decimal or EInputType.Number I cannot type anything.  I can only type numbers and they seem to work as expected.

Can you send me an example of the code you are using to generate the InputView and then maybe a screenshot of the resulting element with letters in it?

**Comment by jldubz** [comment]
Referenced by PSDK-47

**Comment by jldubz** [comment]
@wvuyk I have not heard back from you on this.  Let me know if this is still an issue for you.  If it is we can reopen this ticket.
