### ISSUE TITLE
LabelView not displaying on action config page as expected

### ISSUE THREAD

**Issue by jldubz** [HomeSeer/Plugin-SDK#35]
Per @wvuyk in https://github.com/HomeSeer/Plugin-SDK/issues/28

> I have copied the error routine from NetCam-Plugin.vb and tried to use it unchanged. In this routine a labelview is used. The labelview is, although added, not shown to the users, but can be found in the ConfigPage.views.
>    I really would like to show this line of information, same as I did in the HS3 plugin. It can be helpfull to the users here.
> 
> A copy of the routine:
> 
> ```
>   Public Sub GenerateError(msg As String)
>         'this will add a label view to the top of the page canvas with an error message
>         Dim lblError As LabelView = New LabelView(ErrorId, "Error", msg)
>         Dim Views As New List(Of AbstractView)
>         'start the new list with the error message
>         If Not ConfigPage.ViewIds.Contains(ErrorId) Then Views.Add(lblError)
>         'Add in the rest of the views (if there are any)
>         For Each view As AbstractView In ConfigPage.Views
>             If view.Id <> ErrorId Then Views.Add(view)
>         Next
>         'reset the views
>         ConfigPage.SetViews(Views)
>     End Sub
> ```

Further investigation is needed to determine the root cause of this issue.

**Comment by jldubz** [comment]
@wvuyk

Would you be able to screenshot this for me and walk me through your workflow?  I am unable to reproduce this internally.

**Comment by wvuyk** [comment]
Jon-Luke,

I have been changing the events since I have reported it and noticed that the ConfigPage.views do get updated sevral times, probably due to the fact that with each save action the ActionType.New and  ActionType.New(ByVal id As Integer, ByVal eventRef As Integer, ByVal dataIn As Byte(), oListener As ActionTypeCollection.IActionTypeListener, Optional logDebug As Boolean = False) is getting called several times. This seems to remove the LabelView before getting shown to the user. Why so many "New" calls are needed is something I do not undertsand yet here.

I have now moved the message to a routine that rebuilds the expected views and include the labelview here. This seems to work fine now...

**Comment by jldubz** [comment]
@wvuyk 

Please refer to this workflow for an understanding of the object life-cycle: https://github.com/HomeSeer/Plugin-SDK/issues/18#issuecomment-539708192

-------------

If you are doing ANYTHING in the `New` definitions with the `ConfigPage` you should remove them and move them to the `OnNewAction` method.  The class's `New` definitions are not synonymous with the "new action" event occurring in HomeSeer.  If you take a look at the samples, none of them include any logic in the `New` definitions.

`OnNewAction` should always conclude with the `ConfigPage` initialized to the state that is expected when a new action has been added to an event.

For example, in the sample plugin in [WriteLogSampleActionType.vb](https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/WriteLogSampleActionType.vb#L90):

```
    Protected Overrides Sub OnNewAction()
        Dim confPage = InitNewConfigPage()
        ConfigPage = confPage.Page
    End Sub
```

You can see that the only thing occurring is the initialization of the `ConfigPage` to its starting state

---------------

Updates to the configuration are all processed in `OnConfigItemUpdate` to modify/update the `ConfigPage` to the new state as necessary. (eg add the next view to configure)

For example, in the sample plugin in [WriteLogSampleActionType.vb](https://github.com/HomeSeer/Sample-Plugin-VB/blob/master/WriteLogSampleActionType.vb#L114):

```
    Protected Overrides Function OnConfigItemUpdate(ByVal configViewChange As AbstractView) As Boolean
        ...
        'Initialize the new state of the page so it asks for a message
        Dim newConfPage = InitConfigPageWithInput()
        ConfigPage = newConfPage.Page
        'Save the change to the log type select list
        Return True
    End Function
```

At the end of the method, you can see that the `ConfigPage` is updated with a new InputView to continue the configuration process of the action.

**Comment by wvuyk** [comment]
Jon-Luke,
I am not doing anything in the new definitions here, other then loggin to know it is being called.
Essentially, at this point I think I have similar methods of building the ConfigPage with OnNewAction and in OnConfigItemUpdate.

Guess I am learning slowly here 👍

**Comment by jldubz** [comment]
@wvuyk how is everything going with this? Do you have any questions I can address on this subject?

**Comment by jldubz** [comment]
Referenced by PSDK-12

**Comment by jldubz** [comment]
@wvuyk let me know if you need any more help on this subject and we can reopen the issue.
