### ISSUE TITLE
HsDevice.Features returns nothing

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#36]
I may be doing something wrong but should the following not delete all the features for the device then delete the device

`            Dim Dev As HomeSeer.PluginSdk.Devices.HsDevice

            Dev = hs4.GetDeviceByRef(GetRefByAddress("Arduino, Board:" & PassedboardNo))
            Console.WriteLine("Main device no:" & Dev.Ref)

            Dim FeatList As List(Of HsFeature) = Dev.Features()

            Console.WriteLine("No of features = " & FeatList.Count)

            Dim Feat As HsFeature
            For Each Feat In FeatList
                Console.WriteLine("Deleting device " & Feat.Name)
                hs4.DeleteDevice(Feat.Ref)
            Next

            Console.WriteLine("Deleting device " & Dev.Name)
            hs4.DeleteDevice(Dev.Ref)`

The output I get is:
Main device no:2076
No of features = 0
Deleting device New HS4 Device

Device 2076 has 10 children but they are not returned so the main device is deleted and the database then all gets messed up as the children then become main devices which is strange.
Should there be a call to delete a Device and all features attached to it?

**Comment by spudwebb** [comment]
try  GetDeviceWithFeaturesByRef  instead of GetDeviceByRef

**Comment by Enigmatheatre** [comment]
I changed as you said

`            Dim Dev As HomeSeer.PluginSdk.Devices.HsDevice

            Dev = hs4.GetDeviceWithFeaturesByRef(GetRefByAddress("Arduino, Board:" & PassedboardNo))

            Console.WriteLine("Main device no:" & Dev.Ref)`

now I get Object reference not set to an instance of an object. from Dev.Ref

**Comment by spudwebb** [comment]
Is that a device created by a HS3 or HS4 plugin?
Could you post the code used to create the device?

> Should there be a call to delete a Device and all features attached to it?

I think DeleteDevice is supposed to delete the device and all its features, but as it seems that in your case it fails to load the features, it may also fail to delete them.  
@jldubz  could you confirm?

**Comment by jldubz** [comment]
@Enigmatheatre 

@spudwebb is correct, `GetDeviceByRef` does not return features associated with the device.  `GetDeviceWithFeaturesByRef` does return the device and all associated features.

Side note: it looks like you are making 2 calls to get the device by address by calling to get the ref by address first.  Have you looked at using `GetDeviceByAddress`?

> and the database then all gets messed up as the children then become main devices which is strange.

I do not understand this statement.  Orphaned features are tagged with the relationship of "Feature" and should not roll up to fill the device spot if there is no device.  This is just not the way the logic is coded using the new relationship enums; so it sounds like you are working with a device created using HS3 here?

---------------------

As for the delete method: this call has never deleted the target device in addition to all of the associated devices, and this behavior has not been changed.  This is a good method to add; so I will create a new issue to track the addition of this method. https://github.com/HomeSeer/Plugin-SDK/issues/37

---------------------

Can you please post the JSON for this device and its features and/or try and call GetFeatureByRef against all of the features to see if one of them is not returning correctly.  I have added some additional logging calls into this process for the next release.

**Comment by Enigmatheatre** [comment]
OK, After restarting HS it appears to have removed the error and using GetDeviceWithFeaturesByRef is yielding the results I require and the problem I was seeing with orphaned features is no longer there.
If I can replicate this again I will report it here.

**Comment by Enigmatheatre** [comment]
OK, I think I have found the bug and can reproduce the problem. If I load my HS3 hsd file from the HS4 web interface and try and delete a device I get the error Object reference not set to an instance of an object and this also causes the problem I saw before where all features are set to standalone not only for this device but others in my plugin too!
Restarting HS after loading the new config before deleting the device seems to fix the problem.

**Comment by jldubz** [comment]
@Enigmatheatre 

Can you walk me through your procedure step by step please?  What is the timing like for starting the system, loading the HSD file with HS3 data, and the plugin running this operation?  Is the plugin running this operation on startup or through some sort of call to kick off the method?

I am happy to share a little plugin a whipped together to help run test methods through a feature page if it will help you.

**Comment by Enigmatheatre** [comment]
@jldubz 
Yes please do send through your plugin and I will load it when I get home from work tonight and do some testing for you.
I am calling the delete function from a button on my config page so it is not running on startup.

**Comment by jldubz** [comment]
@Enigmatheatre I apologize for never getting back to you with this sample.  Here are a couple of samples of code for deleting a device and its features:

This is a sample of code that will get a device with features all at once and then delete them all individually
```
'Get the Ref by Address
Dim devRef As Integer = GetRefByAddress($"Arduino, Board:{PassedboardNo}")
Console.WriteLine($"Getting Main device no: {devRef}")
'Get the Device by Ref with features
Dim Dev As HomeSeer.PluginSdk.Devices.HsDevice = hs4.GetDeviceWithFeaturesByRef(devRef)
If Dev Is Nothing
	Console.WriteLine("Error while getting device with features")
	Return
End If
'Proceed with deleting everything
Console.WriteLine($"Main device no:{Dev.Ref}")
Dim FeatList As List(Of HsFeature) = Dev.Features()
If FeatList Is Not Nothing
	Console.WriteLine($"No of features = {FeatList.Count}")
	'This is technically unneccessary because DeleteDevice will take care of every associated feature
	Dim Feat As HsFeature
	For Each Feat In FeatList
		Console.WriteLine($"Deleting device {Feat.Name}")
		hs4.DeleteFeature(Feat.Ref)
	Next
Else
	Console.WriteLine("Feature List is NOTHING")
End If
'You should only need to call this
Try
	Console.WriteLine($"Deleting device {Dev.Name}")
	hs4.DeleteDevice(Dev.Ref)
Catch except As Exception
	Console.WriteLine($"Error while deleting device with ref {devRef} - {except.Message}")
End Try
```

This is a sample of code that will get a device and then all of its features individually and delete them all
```
'Get the Ref by Address
Dim devRef As Integer = GetRefByAddress($"Arduino, Board:{PassedboardNo}")
Console.WriteLine($"Getting Main device no: {devRef}")
'Get the Device by Ref with features
Dim Dev As HomeSeer.PluginSdk.Devices.HsDevice = hs4.GetDeviceByRef(devRef)
If Dev Is Nothing
	Console.WriteLine("Error while getting device")
	Return
End If
Console.WriteLine("Main device no:" & Dev.Ref)
Dim FeatList As List(Of HsFeature) = New List(Of HsFeature)()
For Each associatedFeatRef In Dev.AssociatedDevices
	Try
		Console.WriteLine($"Deleting feature {hs4.GetNameByRef(associatedFeatRef)}")
		hs4.DeleteFeature(associatedFeatRef)
	Catch except As Exception
		Console.WriteLine($"Error while deleting feature with ref {associatedFeatRef} - {except.Message}")
		'Continue or Return?
	End Try
Next
Try
	Console.WriteLine($"Deleting device {Dev.Name}")
	hs4.DeleteDevice(Dev.Ref)
Catch except As Exception
	Console.WriteLine($"Error while deleting device with ref {devRef} - {except.Message}")
End Try
```

-----

There does seem to be an issue with the GetDeviceWithFeaturesByRef() method implementation on the HS Core side which we are investigating.  There is also a lack of exception logging for calls to DeleteDevice where it currently doesn't care if you submit a Feature Ref.  We will expand on this logging as soon as we are able. **I highly recommend you make sure you are calling DeleteFeature for features and DeleteDevice for devices as a call to DeleteDevice using a feature has the current unintended effect of also deleting the owning device and other features.**

This issue is referenced by PSDK-13

**Comment by jldubz** [comment]
Tracked by HS-782 and HS-783
