### ISSUE TITLE
Need method to delete device and all associated features

### ISSUE THREAD

**Issue by jldubz** [HomeSeer/Plugin-SDK#37]
Per @Enigmatheatre on https://github.com/HomeSeer/Plugin-SDK/issues/36

The method DeleteDevice does not delete all associated features.  We need a method to accomplish this with one call.

**Comment by wvuyk** [comment]
1.0.7 is out for some time now, but I do not think this has been implemented, or am I missing something?

**Comment by jldubz** [comment]
The DeleteDevice method accomplishes this.  It was updated on November 6th and was included in PluginSDK v1.0.7 and HS4 v4.0.0.31
