### ISSUE TITLE
Remotely start PIs and HS3's multiinstanceSingleExe PI cannot be stopped

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#38]
The Plugins->Manage functions have a couple of issues"

1/ If you enable a HS3 legacy PI, a MultipleInstanceSingleEXE type, clicking on the PI name takes you to the old HS3 style webpage HOWEVER there is no disconnect button, it just shows "Loaded Remotely" and no "remote loaded plugins" sections as it used to in HS3 to stop the PI. Only way to stop the PI is to stop HS4 and delete the PI's exe.

2/ If I use my development environment (Visual Studio) to start and do on-line debugging, the PI status shows "Loaded Remotely" and again no way to stop the HS4 PI. However in this case I can use a little trick by pulling up the OLD legacy PI Management webpage (http://192.168.1.81/interfaces) and here it shows under the section remote plugins a "disconnect" button. What is ironic is that legacy HS3 PI DON'T show under the "remote plugins" section as they used to but HS4 PIs show up there BUT the same HS4 PIs don't show at all under the new HS4 PI management screens when started remotely. Perhaps supporting remote debugging is not an important feature, running PIs remotely should.

**Comment by rjhdakota** [comment]
This should be fixed in build 4.0.1.6 of HS4.
