### ISSUE TITLE
New ColorPicker controls default to 0-16777215 incorrectly and cannot be changed

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#39]
When adding the color picker in HS3 I could set a value so that I could move it out the range of other controls but in HS4 it appears to take the value of 0 so I can not use this as I get an error telling me the value is in use. I also used to trigger code on this value change. The below image is what I use in HS3.

<img width="733" alt="ColorPicker" src="https://user-images.githubusercontent.com/7591183/68077277-db813a80-fdb8-11e9-96b0-6eb901f5831d.PNG">

**Comment by jvmahon** [comment]
On a related note, is it possible to add to the color picking ability by having a HSV color picker in addition to the RGB. That is, even for RGB devices, the HS4 interface would also include a HSV color picker which HS4 would internally map to the RGB values.

**Comment by rjhdakota** [comment]
Does the HS3 device with the color picker work ok in HS4? I am a little confused as to what you are trying to do.

**Comment by Enigmatheatre** [comment]
Yes, it works fine in HS3. I have a device with the color picker and a dimmer slider with on and off. This device then sets the RGB values on 3 other devices and is used as a master dimmer on the devices to. If If I remember correctly I can take the value of 0 > 100 as the dim value then if the value is set to 101 or more then the color has been set and I can act on that.

**Comment by jldubz** [comment]
@Enigmatheatre 

I would recommend moving the color control to a separate feature and then keep the on/off/dim controls on a separate feature, both associated with the same device.  This is what we are doing with the ZWave color control devices.  This way, no values step on each-other the way you are saying.

You technically should still be able to accomplish this in the same way you did in HS3 by using the [ValueRange.Offset](https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/ValueRange.cs#L78) property.

**Comment by Enigmatheatre** [comment]
Yes, I could make it a different device but just wanted to not make any changes to the plugin from HS3 as the end-user will have to have either the same type of device with two different ways to control it or if I update the HS3 devices this will break events.
Can you 

> You technically should still be able to accomplish this in the same way you did in HS3 by using the ValueRange.Offset property.

Can you explain more as I do not see how this will help? Is this not just changing the displayed value.

**Comment by jldubz** [comment]
Apologies.  I misunderstood your initial request and missed that you were looking for an HSV configuration option too.  Let's create a new issue for that and track it separately.

In HS4 the current default color picker is created using a range of 0-16777215 per https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/FeatureFactory.cs#L381

You are looking to define a color picker control that only operates against 2 values, is that correct? 101 and 102?

**Comment by Enigmatheatre** [comment]
This is the problem as in HS3 you could specify a value you want but in HS4 it is hardcoded and overrides the values I want to set.

> You are looking to define a color picker control that only operates against 2 values, is that correct? 101 and 102?

Yes or even 1 value would do as if I remember correctly when the colour was picked in HS3 the device string was set to the Hex colour and then the value was triggered so I knew it was changed so I could take the string and do what I wanted to with it.

**Comment by jvmahon** [comment]
> Apologies. I misunderstood your initial request and missed that you were looking for an HSV configuration option too. Let's create a new issue for that and track it separately.
> 
> In HS4 the current default color picker is created using a range of 0-16777215 per https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/FeatureFactory.cs#L381
> 
> You are looking to define a color picker control that only operates against 2 values, is that correct? 101 and 102?

Actually, I added-on to the original request to say I'd like to see a HSV option. When you said "let's create a new issue" - should I do that, or were you taking the lead on creating that? Thanks.

**Comment by jldubz** [comment]
> Actually, I added-on to the original request to say I'd like to see a HSV option. When you said "let's create a new issue" - should I do that, or were you taking the lead on creating that? Thanks.

@jvmahon My bad. I saw the similar avatar colors and didn't stop to read the usernames.  Thank you for clarifying.  If you can create it, that would be great; otherwise, I'll get to it today or tomorrow.

**Comment by jldubz** [comment]
> Yes or even 1 value would do as if I remember correctly when the colour was picked in HS3 the device string was set to the Hex colour and then the value was triggered so I knew it was changed so I could take the string and do what I wanted to with it.

Can do.  I'll schedule this change for the next release.

**Comment by Enigmatheatre** [comment]
@jldubz 
Perfect. Thank you for your time.
