### ISSUE TITLE
Can you add GetIPAddress to the SDK?

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#4]
I have a need to know on which interface HS4 is active, because my PIs use the embedded web-server to server TTS files to players so we can serve announcements.

**Comment by jldubz** [comment]
See [commit 399b171](https://github.com/HomeSeer/Plugin-SDK/commit/399b171ddf90ded30eca27e7f768d3a64a302f94) in the dev branch for the upcoming changes.  Please keep in mind that the dev branch will not work with the current HS4 version.  A new installer with these changes will be published Thursday.

**Comment by dcorsus** [comment]
Jon before you close out this issue, there is a fix that was made late in the HS3 dev cycle to respond to the getipaddress call AFTER the web-server was started, else you get an error. This issue is preventing my HS3 PI to start under HS4. To add injury to insult, the manage PI function doesn't seem to work for (my) HS3 PI (multipleInstanceSingleExe) so I cannot disable my PI and start the PI AFTER the webserver was created. So I'm pretty much dead in the water on my HS3-PI testing.
Thanks, Dirk

**Comment by jldubz** [comment]
This is now available as of v1.0.5

> So I'm pretty much dead in the water on my HS3-PI testing.

Backward compatibility support for HS3 plugins is a separate bucket of issues for HS4.  If you haven't already, please post about that in the HS4 bugs sub forum.  I'll be able to follow up with these kinds of things more once we get some of the more important HS4 plugin documentation components and fixes out.

Thanks!
