### ISSUE TITLE
AbstractTriggerType.ProcessData for converting legacy triggers?

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#41]
I have a question on using the ProcessData functions for AbstractTriggerType and AbstractActionType.

What I understand is that this function could be used to convert the HS3 event to the HS4 event? Is it possible to show me a sample on how to this? I have several triggers and actions in the plugin, which I would like to convert to the native HS4 formats, but do not know where to start. First off all, I wonder how to get the old information in the new triggertype? 
I already created the new triggers and actions here. Do I just call the ProcessData directly from the plugin with the triginfo data here, or how can I start conversion? I suppose this routine should only be called during conversion as from then on, the tiggers and actions are in the new format?

Any help would be appreciated.

**Comment by jldubz** [comment]
I fully documented this process for you here: https://docs.homeseer.com/display/HSPI/Reading+Legacy+Event+Data

I am going to close this issue, but I will keep responding to any further questions on this.
