### ISSUE TITLE
IPluginInterface Methods not documented in SDK

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#42]
Methods are used in the sample plugins, but are not documented in the IPluginInterface of the SDK.  These include OnSettingsChange, Initialize, BeforeReturnStatus.

**Comment by jldubz** [comment]
That is because those methods are members of the AbstractPlugin class https://docs.homeseer.com/display/HSPI/AbstractPlugin+Methods
