### ISSUE TITLE
Cannot create StatusOnly StatusControl

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#43]
**Environment and System Config**
- OS: [Windows]
- Language: [VB]
- IDE: [VS2019]
- HomeSeer Version: [v4.0.1.2]
- PluginSDK Version: [v1.0.8.0]

I cannot create a StatusOnly StatusControl on a feature. It always give me the following error:
_You must specify a valid control type
Parameter name: type
Actual value was StatusOnly._

Here is the code to reproduce:
```
StatusControl = New StatusControl(EControlType.StatusOnly)
StatusControl.TargetValue = 1
StatusControl.Label = "On"
hs.AddStatusControlToFeature(dvf.Ref, StatusControl)
```

The woraround I am using now is this:
```
StatusControl = New StatusControl(EControlType.Values)
StatusControl.ControlType = EControlType.StatusOnly
StatusControl.TargetValue = 1
StatusControl.Label = "On"
hs.AddStatusControlToFeature(dvf.Ref, StatusControl)
```

In the List View, that seem to work just fine. But in Grid View, it causes a "Control" button to be created on the feature, without anything to control.

Thanks!

**Comment by jldubz** [comment]
StatusOnly StatusControls have been deprecated and should not be created.  The existence of that Enum type is for backwards compatibility only.

You must create a StatusGraphic for StatusOnly displays.  This is documented directly in the code on both the StatusControl and StatusGraphic classes: https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/Controls/StatusControl.cs#L19

**Comment by stefxx** [comment]
Yes, that makes sense. Thanks!
