### ISSUE TITLE
UpdateFeatureByRef always fails 

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#44]
**Environment and System Config**
- OS: [Windows]
- Language: [VB]
- IDE: [VS2019]
- HomeSeer Version: [v4.0.1.2]
- PluginSDK Version: [v1.0.8.0]

I can't get UpdateFeatureByRef to work. UpdateDeviceByRef works just fine. What is the difference? For UpdateFeatureByRef I always get this error:
_Invalid type for property
Service Version: NO_VERSION_

Here is the code I am using.
```
' Create device
Dim ddf As DeviceFactory = DeviceFactory.CreateDevice(PI_Id)
ddf.WithName("Name")
ddf.AsType(Identification.EDeviceType.Generic, 0)
Dim dndd As NewDeviceData = ddf.PrepareForHs()
Dim ddv As HsDevice = hs.GetDeviceByRef(hs.CreateDevice(dndd))
hs.UpdateDeviceByRef(ddv.Ref, ddv.Changes)

' Create feature
Dim dff As FeatureFactory = FeatureFactory.CreateFeature(PI_Id)
dff.WithName("Feature1")
dff.AsType(Identification.EFeatureType.Generic, 0)
Dim nfd As NewFeatureData = dff.PrepareForHsDevice(ddv.Ref)
Dim ddvf As HsFeature = hs.GetFeatureByRef(hs.CreateFeatureForDevice(nfd))
hs.UpdateFeatureByRef(ddvf.Ref, ddvf.Changes)
```

Everything goes well until the last line.

Thanks!

**Comment by jldubz** [comment]
@stefxx 

This is because you are trying to update a feature that does not exist yet.  Try creating the feature first with hs.CreateFeatureForDevice()

**Comment by stefxx** [comment]
@jldubz 
I am creating the feature with hs.CreateFeatureForDevice() in the second-last line:
Dim ddvf As HsFeature = hs.GetFeatureByRef(hs.CreateFeatureForDevice(nfd))
