### ISSUE TITLE
How to get/set categories on a device?

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#47]
I can't find any function to get or set a category on a devices. Do I miss something obvious or is this not yet implemented?

Thanks!

**Comment by jldubz** [comment]
This is on our plate to implement.  Please stay tuned.

**Comment by stefxx** [comment]
I am still tuned ;)

Categories is one of the more prominent features of HS4. This should really get some priority.

**Comment by wvuyk** [comment]
I am also tuned on this. I already have prepared a proces where users can set a default category for creating their sensors, so it would be nice if we actually can use this.

**Comment by jldubz** [comment]
We are working on adding this for HS4 v4.0.8.0

**Comment by jldubz** [comment]
Tracked by PSDK-17 and PSDK-89

**Comment by wvuyk** [comment]
To bad, 4.0.8.0 is already out, guess we missed that window now....

**Comment by rjhdakota** [comment]
Added to build 4.0.10.0. Docs will be updated soon, but the functions should be easy to understand.

**Comment by jldubz** [comment]
Should be available for you now:

https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_2_0_0.html
