### ISSUE TITLE
Can you add writeHTMLImage and deleteHTMLImage back?

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#5]
I use this to execute the PI remote when art work retrieved from a player need to make it to the HS directories to properly show up on the UI.

**Comment by jldubz** [comment]
You should be able to accomplish the same thing directly using a [WebClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient?view=netframework-4.6.2) and then saving the data to a file in `<HOMESEER_INSTALL_DIR>\html\images\`

For example:

```cs
var    url        = "http://homeseer.com/images/HS4/hs4-64.png";
var    webClient  = new WebClient();
var    imagesPath = $"{Directory.GetCurrentDirectory()}\\html\\images\\PLUGINID";
Directory.CreateDirectory(imagesPath);
string fileName   = Path.GetFileName(url);
webClient.DownloadFile(url, $"{imagesPath}\\{fileName}");
```

Or are you interested in having HomeSeer manage that interaction for you?

**Comment by jldubz** [comment]
Noticing that I missed the reference to "remote" plugins.  Apologies. I'll look further into this.

**Comment by jldubz** [comment]
See [commit a0538ee](https://github.com/HomeSeer/Plugin-SDK/commit/a0538ee5b0ff3859cf7d7e26fb2db484cbce5292) in the dev branch for the upcoming changes.  Please keep in mind that the dev branch will not work with the current HS4 version.  A new installer with these changes will be published Thursday.

**Comment by jldubz** [comment]
So I'm pretty much dead in the water on my HS3-PI testing.

**Comment by jldubz** [comment]
This is now available as of v1.0.5

**Comment by dcorsus** [comment]
Just downloaded v1.05 but can't find writeHTMLImage nor deleteHTMLImage?

**Comment by spudwebb** [comment]
They have been replaced by SaveImageFile and DeleteImageFile

**Comment by dcorsus** [comment]
Ah that works.
Not sure this is the right place but many years ago when I asked for a writeHTMLImage function, I also asked for a "getHTMLDirectory" returning the files in that (remote) directory. Why I hear you ask, because I store album art in there so tools like HSTouch or webpages can retrieve them. However always overwriting the image with same name wasn't working so ended up giving them unique names and I would also delete stale images. However, when the PI is running remote, I cannot do a Directory.GetFiles .net call and do subsequent DeleteImageFile to clean all up, I would need a "getHTMLDirectory(filequerystring) returning string()" function.
Thoughts?
Dirk
