### ISSUE TITLE
Unable to build device using WithLocation2 as empty string

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#52]
https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-bugs/1342899-unable-to-build-device-using-withlocation2-as-empty-string

**Comment by jldubz** [comment]
This will not be changed.  You should not be setting a location to an empty string.  Despite there being the ability to only use one location in previous versions of the HomeSeer platform you should still be setting both locations to something usable by the user.
