### ISSUE TITLE
HomeSeer.PluginSdk.Events.EventUpdateReturnData in SDK, but not in HS4 release

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#54]
https://forums.homeseer.com/forum/developer-support/hs4-development-private/hs4-bugs/1340454-homeseer-pluginsdk-events-eventupdatereturndata-does-not-exits-in-homeseer-pluginsdk

**Comment by jldubz** [comment]
EventUpdateReturnData is deprecated.

The inline documentation is usually the most up to date and should be referenced when in doubt.  Also, the event lifecycle is now handled automatically and those methods should not be overriden.
