### ISSUE TITLE
Cannot change trigger type from one plugin to another plugin's trigger type

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#56]
version 4.0.1.5 Windows

Scenario
1. Select a plugin trigger type on event
2. Select a different plugin trigger type and the trigger type feedback does not change
3. Select a time trigger and the trigger type feedback shows time trigger
4. Select again the different plugin's trigger type and feedback shows it

Step 3 should not be needed

**Comment by spudwebb** [comment]
I remembered I had the same problem, but I cannot replicate it anymore with 4.0.1.38, so it looks like it is fixed

**Comment by mcsSolutions** [comment]
Confirm the problem no longer exists with current HS4 version.
