### ISSUE TITLE
InputView does not return data entered in textbox

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#57]
View created at EInputType.Text, when data viewed in the IsFullyConfigured() function always have a value of "" even after text is entered.  Sample plugins SelectListView and the ToggleView in the below code does return value when user entry is completed.    Attempts at text data in InputView included a Carriage Return and a mouse out of focus.  It looks as if the input view does not recognize that the text box entry has been completed.

    Private Function InitializeMQTTReceivePage() As PageFactory
        Dim cpf As PageFactory = PageFactory.CreateEventTriggerPage(PageId, TriggerName)
        cpf.WithInput("TriggerTopic", "MQTT Topic to match", "", HomeSeer.Jui.Types.EInputType.Text)
        cpf.WithInput("TriggerPayload", "Payload to match", "", HomeSeer.Jui.Types.EInputType.Text)
        cpf.WithToggle("TriggerDone", "Done", False)
        Return cpf
    End Function

Public Overrides Function IsFullyConfigured() As Boolean
        For Each view As AbstractView In ConfigPage.Views
            Dim id As String = view.Id 'TriggerTopic
            If id = "TriggerTopic" Then
                Dim inputView As InputView
                inputView = TryCast(view, InputView)
                Dim value As String = InputView?.GetStringValue
                If value <> "" Then
                    Return True
                End If
            ElseIf id = "TriggerDone" Then
                Dim toggleView As ToggleView
                toggleView = TryCast(view, ToggleView)
                Dim value As String = toggleView.GetStringValue
                If value <> "False" Then
                    Return True
                End If
            End If
        Next

        Return False

    End Function

**Comment by jldubz** [comment]
Input field updates are only processed and recorded when the Save button is pressed on the event action or trigger unlike other view types.

I recommend you adjust the order of the configuration options and how they are displayed to the user to make it so input fields are filled last and the intuitive action is to click SAVE.

**Comment by mcsSolutions** [comment]
Feature pages typically do not have Save buttons.  This was the significant change that occurred with HS3 use of Jquery/Ajax vs. HS2.

The input field should behave like other controls on feature pages with the plugin having the ability to know that a user has made a change to an input box.

**Comment by mcsSolutions** [comment]
Do not agree

**Comment by stefxx** [comment]
This is crazy. A complex event action cannot be created without a callback to OnConfigItemUpdate for inputView. Suggestion to put all input fields last and hoping the user doesn't click something else before clicking save does not make any sense!
