### ISSUE TITLE
OnNewTrigger invoked before Sub New() completes

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#58]
The following execution sequence was trapped for a Trigger class that shows the class was instantiated twice, but the first Sub New() execution was not completed before the OnNewTrigger method was invoked,  The result is the initialization expected before OnNewTrigger is ready to execute did not complete in the Sub New() procedure.

Receive New1 False
Receive OnNewTrigger False
Receive New2 True

    Public Sub New()
        MyBase.New
        Debug.Print("Receive New1 " & (_MyTrigger1MqttReceive IsNot Nothing).ToString)
        If _MyTrigger1MqttReceive Is Nothing Then
            _MyTrigger1MqttReceive = New MyTrigger1MqttReceive
        End If
    End Sub

    Public Sub New(ByVal id As Integer, ByVal eventRef As Integer, ByVal selectedSubTriggerIndex As Integer, ByVal dataIn As Byte(), ByVal inListener As TriggerTypeCollection.ITriggerTypeListener, Optional ByVal debugLog As Boolean = False)

        MyBase.New(id, eventRef, selectedSubTriggerIndex, dataIn, inListener, debugLog)
        Debug.Print("Receive New2 " & (_MyTrigger1MqttReceive IsNot Nothing).ToString)
        If _MyTrigger1MqttReceive Is Nothing Then
            _MyTrigger1MqttReceive = New MyTrigger1MqttReceive
        End If
        MyTrigger1MqttReceive.EvRef = eventRef
        MyTrigger1MqttReceive.TriggerUID = id
        IsFullyConfigured() 'get then topic and payload from the view controls
    End Sub

    Protected Overrides Sub OnNewTrigger()
        Debug.Print("Receive OnNewTrigger " & (_MyTrigger1MqttReceive IsNot Nothing).ToString)
        If _MyTrigger1MqttReceive Is Nothing Then
            _MyTrigger1MqttReceive = New MyTrigger1MqttReceive
        End If
        ConfigPage = InitializeMQTTReceivePage().Page
    End Sub

**Comment by jldubz** [comment]
That is expected.  Please take a look at the event lifecycle outlined in issue https://github.com/HomeSeer/Plugin-SDK/issues/18

**Comment by mcsSolutions** [comment]
In your issue #18 reference you do not include the creation of the object supporting the trigger.
The object that is supporting the OnNewTrigger method should be created before the OnNewTrigger method is invoked.  How can the software be ready to do anything with the OnNewTrigger call if it does not have time to initialize its state during object creation in the New() method?

**Comment by mcsSolutions** [comment]
Don’t agree.
