### ISSUE TITLE
Is the connection reattempt working?

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#6]
I'm on HS4 v20 and SDK v4.
When I start my PI and HS4 is not running I get the following output and nothing ever happens and the PI hangs ..... until I start HS4 then it terminates. 
I would have expected some reattempts and a graceful exit after x failed attempts.
I suspect the exception captured below sends the logic in a tailspin.

InitializeSettingsPages Called - Done
Connecting to HomeSeer...
System.Exception: The host failed to connect. Timeout occured. 15000
   at HSCF.Communication.Scs.Client.Tcp.TcpHelper.ConnectToServer(EndPoint endPoint, Int32 timeoutMs)
   at HSCF.Communication.Scs.Client.Tcp.ScsTcpClient.CreateCommunicationChannel()
   at HSCF.Communication.Scs.Client.ScsClientBase.Connect()
   at HSCF.Communication.ScsServices.Client.ScsServiceClient`1.Connect()
   at HomeSeer.PluginSdk.AbstractPlugin.Connect(Int32 attempts)
Cannot connect attempt 1
Waiting for initialization...
System.NullReferenceException: Object reference not set to an instance of an object.
   at HomeSeer.PluginSdk.AbstractPlugin.Connect(Int32 attempts)

**Comment by jldubz** [comment]
@dcorsus 
The plugin connect code should be attempting a connection 5 times.  It looks like something is bailing after the first attempt according to your log output.

See [line 188](https://github.com/HomeSeer/Plugin-SDK/blob/2eb43081b97ed12aea60cf75dc03fbca871361b7/AbstractPlugin.cs#L188) for the connection code.  It looks like this is likely an issue in the way the method recursion is done; we might be disposing of the `_client` object before the next iteration actually occurs at [line 213](https://github.com/HomeSeer/Plugin-SDK/blob/2eb43081b97ed12aea60cf75dc03fbca871361b7/AbstractPlugin.cs#L213)

**Comment by jldubz** [comment]
At [line 211](https://github.com/HomeSeer/Plugin-SDK/blob/2eb43081b97ed12aea60cf75dc03fbca871361b7/AbstractPlugin.cs#L211) this code
```
if (exception.Message.ToLower().Contains("timeout occurred.") && attempts < 6) {
    Connect(attempts + 1);
    if (_client != null) {
        _client.Dispose();
        _client = null;
    }
    return;
}
```

should probably be changed to this
```
if (exception.Message.ToLower().Contains("timeout occurred.") && attempts < 6) {
    Connect(attempts + 1);
    return;
}
else {
    if (_client != null) {
        _client.Dispose();
        _client = null;
    }
}
```

**Comment by spudwebb** [comment]
this is not the only problem because the message in the exception thrown in case of timeout is:

exception.Message = "The host failed to connect. Timeout occured. 15000"

with one 'r' in occured so the if is never true and the connection reattempt never occurs

**Comment by spudwebb** [comment]
Also, I think the return statement should be moved after the if/else block

I created a PR with all these fixes

**Comment by jldubz** [comment]
Fixed in [commit ec12c0](https://github.com/HomeSeer/Plugin-SDK/commit/ec12c0bc2655edc5c4b71858a15165eba091435d)
