### ISSUE TITLE
Important Links reference is not being maintained

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#61]
HS4 Developer forum https://forums.homeseer.com/forum/developer-support/hs4-development-private/1325501-important-links-plugin-sdk-on-github shows the current HS release to be 4.0.1.1 while later version has been released.

**Comment by jldubz** [comment]
@mcsSolutions you are correct. We have been working to figure out the best method to communicate everything to the Plugin Dev community.  All of the Plugin SDK documentation and information is available now through the [Plugin SDK Docs|https://docs.homeseer.com/display/HSPI] and [Release Notes|https://homeseer.github.io/Plugin-SDK-Docs/release_notes/index.html]

Information about the latest HS4 beta release will continue to be published to the forum.  We should probably delete the "Important Links Reference" if it is not being used for HS4 information then.

Thoughts?

**Comment by jldubz** [comment]
Referenced by PSDK-24

**Comment by mcsSolutions** [comment]
My process to get info was to navigate to the important links post.  I understand it may not now be the best way.  What I suggest is to remove information from the post that has been superseded.  If everything has been replaced then remove the topic from the Message Board.

**Comment by jldubz** [comment]
We removed it per your recommendation.  Thank you.  We are working on revising the documentation at this time; so please let me know if there is anything in particular that you think will help make it easy to use.
