### ISSUE TITLE
Handling legacy data is not contained in Sample Plugins

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#62]
Handling of legacy TrigActionInfo and PED is described on the developers forum, but as times moves on this will not be a normal reference point for new developers.  This information should be illustrated in the SamplePlugin source.

**Comment by jldubz** [comment]
This is documented here https://docs.homeseer.com/display/HSPI/Reading+Legacy+Event+Data
and here https://docs.homeseer.com/display/HSPI/Reading+Legacy+PlugExtraData
