### ISSUE TITLE
Tab menu from Devices for plugin button produces error message

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#64]
After viewing a plugin device from the Device tile and clicking on the name of device to bring up Setting / Features / Status Graphic / <plugin> tab buttons, then clicking on the <plugin> (e.g. mcsMQTT) button an error feedback of the following is generated:
"Error with device config page JSON: Object reference not set to an instance of an object." 

This <plugin> button was not available on HS3 so I am not certain of what to expect when it is clicked, but it should not be an error message.

**Comment by rjhdakota** [comment]
I assume you are referring to your HS3 plugin? There should be a button there that takes you to the HS device config tab. I cannot try it with your plugin as I don't have any MQTT devices here. It seems to be ok with some other plugins I tried. Can you try it again with HS4 build 4.0.13 when its posted as the page in question has been changed.

**Comment by mcsSolutions** [comment]
4.0.1.18  I no longer see the button of the plugin that owned the device on the settings-features-status/graphics page.  This can be closed.
