### ISSUE TITLE
Deleted devices restored upon restart

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#66]
4.0.1.5

No plugins activated.
Bulk action on Devices.  Check all devices, Delete.
View Devices page and no devices appear.
Use HS4 form upper right X to shutdown HS
Start HS4 from desktop shortcut
Opens in Devices page and all previously deleted devices appear again.

**Comment by jldubz** [comment]
Referenced by PSDK-26

**Comment by jldubz** [comment]
Cannot reproduce as of v4.1.0.0 of HS Core.
