### ISSUE TITLE
"updater_override.json" does not work on Linux

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#67]
Instructions followed at https://docs.homeseer.com/display/HSPI/Testing+Installation to test a HS4 plugin updater package submittal.  On Windows the install went fine.  On Linux a message was received that the package could not be found in ...\Update4\Zips location.  Another copy of the zip was placed there, but again the same message appears.  Note that the message used Windows slash and not Linux slash notation.

**Comment by rjhdakota** [comment]
Looks like I messed up the path for Linux, I will get a fix put in for the next build.

**Comment by jldubz** [comment]
Referenced by HS-660

**Comment by rjhdakota** [comment]
Fixed in build 4.0.5.0.
