### ISSUE TITLE
The "auto update" check button in the log screen doesn't seem to work properly

### ISSUE THREAD

**Issue by dcorsus** [HomeSeer/Plugin-SDK#7]
If I start HS4 and the auto-update is not set, it works as it should ie no new log entries show up.
If I enable the auto-update, that also works.
If I now turn off auto-update, that doesn't seem to work and updates are still showing in the log file
I'm on v20

**Comment by jldubz** [comment]
Thank you for reporting this issue.  Unfortunately, this is not something that pertains to the Plugin SDK and, thus, cannot be fixed through any modifications to the code in this repository.  This sounds like a UX bug that should be reported in the HS4 Bugs sub forum.  Can you please do so there? 
 Apologies for any miscommunications.

Thank you for understanding.

**Comment by dcorsus** [comment]
I understand. I would however encourage HS to give us ONE place to submit bugs and you guys route them properly. I can't judge whether the issue reported here is an SDK, UI or some other code issue. My confidence level to make sure none of the reported issues through the forum won't be lost  isn't very high but I do believe you are doing all you can do and I want to thank you for that. My suggestion is a process improvement to make all our effort more efficient and effective.
