### ISSUE TITLE
Mouse-over of primary feature is not enabled on Device Tile

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#70]
A Device tile contains the primary feature in the middle left of the tile and the secondary features are listed at the top of the tile.  Since all icons are the same gear it is not possible to know what the feature is unless one mouse-overs it to bring up a tool tip to identify it.

The tool tip appears for the top secondary features, but does not provide any feedback for the name of the primary feature.

**Comment by rjhdakota** [comment]
Not sure I follow. The primary feature displays it's icon as status, the name is just above it, and the status is next to it. So the primary displays the same info as the hover on the features.

**Comment by mcsSolutions** [comment]
As an example the following is a device tile with eight features

 



 

 

If I mouse-over any of those on the top it provides tool tip display of the name of the feature.

If I mouse-over the larger button in the middle of the tile that shows status” on” I will not get any feedback to know which of the eight features has this status.  In this case the on status is for the relay feature, but I have no way of knowing that without clicking on the device name and then going to the feature tab and then looking at the list of features and finding the 8th one that is not in the top set of seven.  It is nice to have the status showing, but status without knowledge of what feature has this status kind of useless.

**Comment by jldubz** [comment]
Referenced by PSDK-29

**Comment by jldubz** [comment]
@mcsSolutions can we move this over to the Service Desk as a feature request? https://dev.homeseer.com/servicedesk/customer/portal/2/create/13

We are looking into ways to upgrade the devices page.  Can you please create an issue and let me know the issue key? I have also added what you have written as a note for our discussions.

Thank you very much.
