### ISSUE TITLE
Radio Button on Settings page: value is not saved to <plugin>.ini

### ISSUE THREAD

**Issue by mrdork-git** [HomeSeer/Plugin-SDK#73]
Selecting a radio button option then 'save' on the settings page does not save the selected option's value to the plugin's .ini. If the value is manually changed in the .ini (from the default of -1) the value is properly loaded and the Radio Button displays the corresponding value.

**Comment by jldubz** [comment]
This has been fixed and will available in v1.1.0.0 which is being uploaded to NuGet today
