### ISSUE TITLE
SubTANumber  not reflected by SelectedSubActionIndex

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#75]
Please check issue #69 for this. I cannot reopen this by myself but there are still issues converting ald actions.

Check my last post on this issue. The remark was that the field SelectedSubActionIndex would be filled with the information from the original ActInfo.SubTANumber . What ever I tried, that is not working. All action items are presented correctly in the plugin, but not this ActInfo.SubTANumber which is needed to do the conversion 100%.
At this point I am guestimating the subaction used, but that cannot be right as several actions use the same item.

How can I get the ActInfo.SubTANumber presented in HS4? The data is there....

Wim

**Comment by wvuyk** [comment]
Any chance to get at least an answer to this issue?

**Comment by rjhdakota** [comment]
I will have someone get an answer for you.

**Comment by spudwebb** [comment]
@wvuyk  have you implemented the constructor  with the subTypeNumber parameter in your action class?

`protected AbstractActionType(int id, int subTypeNumber, int eventRef, byte[] dataIn, ActionTypeCollection.IActionTypeListener listener)`

**Comment by wvuyk** [comment]
I had to implement three constructors, missing one throws errors (in VB)
```
Public Sub New()
        MyBase.New
        '  Log("new called without params")
 End Sub

Public Sub New(ByVal id As Integer, ByVal eventRef As Integer, ByVal dataIn As Byte(), oListener As ActionTypeCollection.IActionTypeListener, Optional logDebug As Boolean = False)
        MyBase.New(id, eventRef, dataIn, oListener, logDebug)
End Sub

Public Sub New(ByVal id As Integer, ByVal SelectedSubActionIndex As Integer, ByVal eventRef As Integer, ByVal dataIn As Byte(), oListener As ActionTypeCollection.IActionTypeListener, Optional logDebug As Boolean = False)
        MyBase.New(id, SelectedSubActionIndex, eventRef, dataIn, oListener)

End Sub
```

I have tried to check when which constructor is called, but it is called very often during execution or edit of actions. It seems quite random on which constructor is called, not something I really understand what and why this is needed.

**Comment by wvuyk** [comment]
Maybe another point I noticed here, if an (HS3) action is entering the ProcessData routine, SelectedSubActionIndex  is aways 0, never -1 or other values, like the documentation states. Don't know if that is giving clues in this area.....

**Comment by wvuyk** [comment]
Jon-Luke,

Sorry for the delay here. Was distracted by other issues in life, which seem to settle now here.

Finally was able to test today and it looks like it is working now. I expected the logdebug parameter would be valid for all constructors, so added it, not realizing this was the cause behind this issue.

Thanks for the explanation. Will be back on the other issues soon.

Wim

**Comment by jldubz** [comment]
@wvuyk let me know if you have any more questions on this issue. It sounds like you've got it.
