### ISSUE TITLE
Plugin status reported as "Loaded Remotely" rather than OK

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#77]
HS4 4.0.1.18
Installed Hubitat Elevation plugin from HS4 updater.
Load successful and plugin starts but status reported as remote rather than OK
Plugin page, disable plugin slider button for Hubitat cannot be set to disable position
HS log indicates "Plug-In  has characters in its name that cannot be used"
mcsHubitat plugin source contains
    public override string Id { get; } = "mcsHubitat";
    public override string Name { get; } = "mcsHubitat";

In the initial install of Hubitat Elevation the plugin status reported OK.  Immediately after installing Tuya plugin, HS disconnected mcsHubitat, restarted it, and then status on plugin page have never again returned to OK but shows as Loaded Remotely.  This is even if Tuya is deleted and HS4 restarted.  The capture of the log during this process is at post #18 of https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/hubitat-elevation-simplex-technology/1359181-hs4-install/page2

**Comment by rjhdakota** [comment]
I will load your plugin tomorrow and check it in the debugger. It sounds like HS might be throwing an error during the init and maybe I can determine why.

**Comment by mcsSolutions** [comment]
I believe I have run down the source of the error.  The .json file deposited by the Updater into the HS4 folder contains the product name of Hubitat Elevation rather than mcsHubitat.  When I do a manual updater_override.json file with the correct name then the issue no longer exists.  I submitted this analysis to Tyler.

**Comment by rjhdakota** [comment]
Ok, good, I will check with Tyler on this.

**Comment by mcsSolutions** [comment]
I submitted a later version of the plugin with submission notes of the problem with how the updater control file was using the store name "Hubitat Elevation" rather than the plugin name "mcsHubitat" as the product.  Either the control file needs to change or HS4 should not be using this field from the updater control file.

When the newly submitted version was published no change was made to the control file so users that download it have issues of plugin restarting continuously and the status reported as remote.

**Comment by rjhdakota** [comment]
Fixed in HS version 4.0.3.9. Issue HS-654

**Comment by hem-bhagat-tark** [comment]
@mcsSolutions In my case even using manual override.json with the correct name causes this issue. I am dealing with the following scenario,

I have my plugin installed with the old name. After that, I update the PluginName property of the AbstractPlugin and build the exe. In the manual updater-override.json, I specify the new name in the PackageName field. When I update the plugin, the plugin name does not change and the plugin status is Loaded Remotely instead of Ok.
