### ISSUE TITLE
Device Features count does not match AssociatedDevices count

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#78]
HS4 Version 4.0.1.28

When observing a Device with debugger that has three features the Features count = 0.  The AssociatedDevices count does contain 3 as expected.  The SDK implies that Features property of device should have a list of pointers to the Device's Feature objects.

?dv
{HomeSeer.PluginSdk.Devices.HsDevice}
    Address: ""
    AssociatedDevices: Count = 3
    Changes: Count = 9
    FeaturePriority: Count = 0
    Features: Count = 0
    Image: ""

**Comment by spudwebb** [comment]
@mcsSolutions  how do you load the device?
If you use 
dev = hs.GetDeviceByRef(dvRef);
then the features are not loaded so yes in this case dev.Features.Count would be 0, but dev.AssociatedDevices.Count would still show the correct number of features.

if you want to load the device and the features you need to use:
dev = hs.GetDeviceWithFeaturesByRef(dvRef);

**Comment by mcsSolutions** [comment]
I was using hs.GetDeviceByRef(dvRef).  I was unaware of the implications between the two methods.  This can be closed.
