### ISSUE TITLE
No means to access the plugin object to support scripting

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#79]
SDK as of 2/14/2020 does not provide a mechanism to get access to plugin (Iplugin) objects from IHSController.  The following is from the HS3 scripting help file

name = hs.PluginPropertyGet("Z-Wave", "", "Name", nothing)

An equivalent or alternate method is needed in HS4.  

Some Plug-ins provide a scripting interface so a user needs a means to get access to the plugin programatically.  The same applies for plug-in to plug-in communication such as determining if another plugin is running.

**Comment by dcorsus** [comment]
Isn't this the same or at least, that's what I use

 Public Overloads Function PluginFunction(ByVal proc As String, ByVal parms() As Object) As Object Implements HomeSeer.PluginSdk.IPlugin.PluginFunction

   Public Overloads Function PluginPropertyGet(ByVal proc As String, parms() As Object) As Object Implements HomeSeer.PluginSdk.IPlugin.PluginPropertyGet

 Public Overloads Sub PluginPropertySet(ByVal proc As String, value As Object) Implements HomeSeer.PluginSdk.IPlugin.PluginPropertySet

**Comment by mcsSolutions** [comment]
PluginFunction may be called once a handle exists on the plugin object. The problem is getting access to the plugin object that was spawned by HS4. HS4 needs to provide a mechanism where a script or other plugin can get access to the plugin object that is active.

**Comment by dcorsus** [comment]
Had to admit I'm not following. I implemented the above functions in my PI so that any outsider, be it script or scriban code in HTML has access to any public defined property or method in my PI. 
It works (for me) 100% the same as in HS3 because I just kept the code. I guess there is perhaps something else you use or need that I don't know about.
I did notice that propertyget cannot return object though, is that what I'm missing?

**Comment by wvuyk** [comment]
PropertyGet is propbably the issue here. It was already mentioned in September on the foums that it was missing, but did not hear back. I have worked around it by creating a function for it.

**Comment by dcorsus** [comment]
propertyget is there (assuming you coded it up in your PI, I don't think it is in the sample), I use it.
I couldn't return a list of objects though and I did same as you, I created a function for it but I use all three (pluginfunction, propertyget, propertyset).

**Comment by spudwebb** [comment]
I think what @mcsSolutions  wants is these methods in IHSController that are marked as TODO, and that will allow you to access PropertyGet / PropertySet in other plugins

https://github.com/HomeSeer/Plugin-SDK/blob/a975e3627c680dc872f9efda7f5b4eadecb01e32/IHsController.cs#L752-L755

**Comment by dcorsus** [comment]
Through the dense fog in my head, I start to understand what I was missing.
Thanks for enduring my remarks.

**Comment by jldubz** [comment]
This won't be difficult to re-implement, but we will have to leave this issue for implementation into 1.1.0 so we can properly pair it with changes to Scheduler.dll (which is what implements IHsController on the HomeSeer side) and provide proper backward compatibility for any plugin still using <1.1.0 (1.0.0-1.0.9) if possible given the underlying architecture.

Logged as PSDK-36 and scheduled for 1.1.0

**Comment by spudwebb** [comment]
these methods are now available in PluginSDK 1.2.5, see https://homeseer.github.io/Plugin-SDK-Docs/release_notes/pluginsdk_releasenotes_1_2_5_0.html
