### ISSUE TITLE
logscreen open with autoupdate enabled will raise CPU to 100%

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#8]
When I open the logscreen and enable autoupdate the CPU will gradually raise to 100% (shared between browser process and HS4)

Switching over to device will drop the usage again.

Also, is it possible to enable autupdate by default? Users checking the log file will mostly want to see progress in the log and expect the log to automatically proceed if new lines are added.

**Comment by jldubz** [comment]
Hi,

Thank you for reporting this issue.  Can you please post this in the HS4 bugs forum; as it pertains to the HS4 UI and not to the plugin SDK.  We will be happy to help you with this issue there.

Thanks again.
