### ISSUE TITLE
SelectListView doesn't work for Dropdown (but does for RadioList)

### ISSUE THREAD

**Issue by stefxx** [HomeSeer/Plugin-SDK#81]
**Environment and System Config**
- OS: Windows 10
- Language: VB
- IDE: VS2019
- HomeSeer Version: v4.0.0.37
- PluginSDK Version: v1.0.8.0

**Describe the bug**
SelectListView doesn't work with ESelectListType.DropDown. It does work with ESelectListType.RadioList

**Steps to Reproduce**
I have this function in my Plugin to configure my device:
```
Public Overrides Function GetJuiDeviceConfigPage(deviceRef As Integer) As String
    Dim PageID = "DeviceConfig"
    Dim JUIPage As Page = PageFactory.CreateDeviceConfigPage(PageID, "Plugin Config").Page
    JUIPage.AddView(New SelectListView(PageID & "-Label", "Label",
        New List(Of String)({"Option 1", "Option 2", "Option 3"}),
        New List(Of String)({"1", "2", "3"}),
        ESelectListType.DropDown))
    Return JUIPage.ToJsonString
End Function
```

The result is just the Label, nothing else:
![image](https://user-images.githubusercontent.com/20107364/75192995-a9278e80-5755-11ea-9aab-9b9208725bad.png)

It works when I use exactly the same code, but change Dropdown to RadioList:
```
Public Overrides Function GetJuiDeviceConfigPage(deviceRef As Integer) As String
    Dim PageID = "DeviceConfig"
    Dim JUIPage As Page = PageFactory.CreateDeviceConfigPage(PageID, "Plugin Config").Page
    JUIPage.AddView(New SelectListView(PageID & "-Label", "Label",
        New List(Of String)({"Option 1", "Option 2", "Option 3"}),
        New List(Of String)({"1", "2", "3"}),
        ESelectListType.RadioList))
    Return JUIPage.ToJsonString
End Function
```
![image](https://user-images.githubusercontent.com/20107364/75193027-b8a6d780-5755-11ea-87f9-a59188d58ec6.png)

What do I need to do to get the Dropdown? I guess this is a bug? Thanks!

**Comment by spudwebb** [comment]
I can replicate this bug, and I logged it as HS-548

**Comment by stefxx** [comment]
Thanks!

**Comment by jldubz** [comment]
Referenced by PSDK-38 and PSDK-39

**Comment by rjhdakota** [comment]
Fixed in HS build 4.0.3.5. The next public release that contains this fix will be 4.0.4.0. If you need this fix sooner let me know and I can post a test build.

**Comment by stefxx** [comment]
Hi,

I wouldn’t mind a beta to test and finalize my plugin, but only if it isn’t too much trouble.

Thanks!

Regards, Stefan.

**Comment by rjhdakota** [comment]
Here is build 4.0.3.5 that has the fix:
http://homeseer.com/updates4/SetupHS4_4_0_3_5.msi

**Comment by stefxx** [comment]
Thanks!
