### ISSUE TITLE
Select List not rendered on CreateDeviceConfigPage

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#83]
4.0.1.37 Windows

Following call to GetJuiDeviceConfigPage the following was provided.  The expected rendering on the Device Config tab of the device is a selector with options of A and B under the name of "Test Selector".  What was shown is only the name "Test Selector".  Mouse over to try to find the selector did not find one.

Public Overrides Function GetJuiDeviceConfigPage(ByVal dvRef As Integer) As String
            Dim testFactory As HomeSeer.Jui.Views.PageFactory = HomeSeer.Jui.Views.PageFactory.CreateDeviceConfigPage(pageID, "Device Settings")
            testFactory.WithDropDownSelectList("Test", "Test Selector ", New List(Of String) From {"A", "B"}, New List(Of String) From {"0", "1"}, 0)
            Return testFactory.Page.ToJsonString
End Function

**Comment by spudwebb** [comment]
it's a known problem, already reported here: #81
