### ISSUE TITLE
Incorrect plugin selected for update download

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#84]
Version 4.0.3.10

Plugin menu item, Installed.  A list of installed plugins shows.  Tile with mcsMQTT contains a cloud icon with down arrow to indicate a new version is available.  Click the icon and mcsShelly panel appears with buttons to Update etc.

mcsMQTT is a HS3 Legacy plugin.  The mcsShelly panel is for the HS4 plugin of mcsShelly.

If mcsMQTT is selected from the Plugin menu Add button then it correctly identifies mcsMQTT as the pluign for update.

Visual screenshot is on post #5 of [https://forums.homeseer.com/forum/lighting-primary-technology-plug-ins/lighting-primary-technology-discussion/mcsmqtt-michael-mcsharry/1372599-hs4-mcsmqtt-shows-update-available-but-update-is-for-mcsshelly](url)

**Comment by rjhdakota** [comment]
Fix will be in HS build 4.0.5.0. HS-668
