### ISSUE TITLE
Regression - GetJuiDeviceConfigPage no longer called

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#85]
Version 4.0.3.10
In version 4.0.3.0 GetJuiDeviceConfigPage was called from Devices page when the pluign's tab was clicked.  With version 4.0.3.10 the call is no longer made.  Clicking the plugin's tab appears to redraw the features tab.

This was confirmed by placing breakpoint at GetJuiDeviceConfigPage.  It was reached with 4.0.3.0, but not reached with 4.0.3.10

Steps
1. Device page, click on a feature
2. Click on right-most tab which contains the name of the plugin

**Comment by rjhdakota** [comment]
Fixed in HS4 4.0.4.0 issue HS-657
