### ISSUE TITLE
GetJuiDeviceConfigPage does not pass feature ref

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#86]
Version 4.0.4.0

GetJuiDeviceConfigPage call always contain the reference of the device even when the feature is what is being requested.  Different features may have different configuration possibilities and by only knowing the device and not the feature ref the plugin is not able to customize the setup needed.  The only option that exists is to put up templates for every feature that the device has and let the user scroll through the page looking for the feature of interest.

Steps to reproduce
1. Start with device page in list view
2. Click on a feature
3. Click on tab with plugin name to invoke GetJuiDeviceConfigPage
4. Observe input dvRef parameter as being the Device and not the Feature reference number

**Comment by Enigmatheatre** [comment]
I also see this as a step back and have had to change the way my plugin functions as there is no way for the user to get to the plugin config page of a feature.

**Comment by rjhdakota** [comment]
We don't have a good way to handle this at the moment. My suggestion is to just add a droplist on your config page so the user can select the feature they want to manage. This also has the advantage in that you can leave out features that you don't want the user to have access to.

**Comment by alexbk66** [comment]
> My suggestion is to just add a droplist on your config page so the user can select the feature they want to manage.

Parent (root) GetJuiDeviceConfigPage could take the selected feature RefId argument

**Comment by dpmurphy** [comment]
I had to stumble across this feature, debug it endlessly convinced it was me and eventually find this with a Google search when all else fails.

I just don't get the poor documentation / examples everybody has to stumble through the process. It's really kind of ridiculous

**Comment by alexbk66** [comment]
> We don't have a good way to handle this at the moment. My suggestion is to just add a droplist on your config page so the user can select the feature they want to manage. 

Yeah, that's what I did - so to get to the feature page the user has to click on the device first, then I display the list (below), then they have to click on same device again.  Kind of ridiculous.

![image](https://user-images.githubusercontent.com/2533315/111575731-23b0c980-8803-11eb-808b-94bfd12cbfa2.png)

**Comment by spudwebb** [comment]
We are going to implement this by adding a new SupportsConfigFeature property to IPlugin. If you set this property to True in your plugin, then the ref passed to GetJuiDeviceConfigPage will be the ref of the feature rather than the ref the parent device. 

Tracked as PSDK-152

**Comment by alexbk66** [comment]
Can you simply pass both?  The page URL has both parent and child:

http://192.168.1.83/devices.html?ref=1765&subpage=devprop&feature=1767

**Comment by spudwebb** [comment]
> Can you simply pass both? 

No, because if we add a parameter to GetJuiDeviceConfigPage it would break all the existing plugins that  use  it.

**Comment by alexbk66** [comment]
Normal practice in interface development is to add another function, i.e. GetJuiDeviceConfigPage1

**Comment by spudwebb** [comment]
In PluginSdk 1.3.0.0 / HS 4.1.17.0, there is a new AbstractPlugin.SupportsConfigFeature property. By default this property is false, and everything behave as before i.e. the ref of the root device is always passed to GetJuiDeviceConfigPage even if the page is requested on a feature. If you override this property to true, the ref being passed is now either the feature ref or the device ref depending if user tries to open the page while being on the device settings or the feature settings.

https://homeseer.github.io/Plugin-SDK-Docs/api/HomeSeer.PluginSdk.AbstractPlugin.html#HomeSeer_PluginSdk_AbstractPlugin_SupportsConfigFeature
