### ISSUE TITLE
StatusControl class missing statusonly settings

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#9]
My plugin holds a lot of sensors, which only set status, but cannot be controlled, like motion sensors, temperature sensors etc.. Also switches set a status as "pressed" or similar, but cannot be controlled.

With the new statuscontrol class it is no longer to set a status-only attribute. 

According [to this page](https://docs.homeseer.com/display/HSPI/StatusControl+Class) in the plugin SDK documentation this is removed deliberatly?

> Remarks
>Legacy VSPairs used to be able to be defined as either status-only, control-only, or both, but >this is no longer allowed. All StatusControls are considered both, and a StatusGraphic will >override the Status on the feature if it is configured for the feature's current Value.
>If you are looking to add a status-only control to a feature, create a StatusGraphic instead.

Why is this done? And more important, how to use the status then? Users tend to act on the sensors with events.

`IF My Motion sensor changes to Motion
THEN Set MyLight to On`

Becomes
 
`IF My Motion sensor changes to 100 <=== we hope....
THEN Set MyLight to On`

Which is not really a user friendly solution. A workaround could be to use  the statuscontrol anyway and just do nothing when the user presses the button? Which is not user friendly again... and a lot of work for the plugin to exclude the buttons......

How can we resolve this missing part?

**Comment by spudwebb** [comment]
You can set a Label to a StatusGraphic  which will be displayed as the status:

```
                statusGraphic = new StatusGraphic(ImagesStatusDir + "fan-state-off.png", 0);
                statusGraphic.Label = "Off";
                HS.AddStatusGraphicToFeature(featRef, statusGraphic);
```

I don't think it works yet for events, but this is the idea.

**Comment by wvuyk** [comment]
Ok, missed the label field on the statusgraphic. But that indeed does not help the users to choose a 'logical' status description in their events. So i hope there will be a solutioncreated  for that?

**Comment by spudwebb** [comment]
I think the event engine has not been adapted yet for this new label, but you're right users should be able to select logical status description in their events. I will make sure this problem doesn't slip through the cracks.

**Comment by jldubz** [comment]
> Ok, missed the label field on the statusgraphic. But that indeed does not help the users to choose a 'logical' status description in their events. So i hope there will be a solution created for that?

Correct. This is a bug in the current implementation of the trigger type.  We are working on addressing this issue so the StatusControls and StatusGraphics are queried correctly to display the expected list of options to the user.

**Comment by wvuyk** [comment]
I am trying to get to use the statusgraphic as a fake status only object, but I cannot set decimalplaces to the object as well as suffix and/of prefixes. It is of no good use yet as replacement for statusonly replacements.

Also, using the label does not add this label visually in the device list. So how can I proceed on this as my plugin is using a lot of sensors, and thus uses the 'statusonly' states a lot. There is no way I can test this now?

Also in Controls.EControlType there is still a statusonly (1) value present. 
But when used it throws an error, guess this has to be removed still?
Although I do think that using this statusonly control would make coding with the prefix/suffix and decimalplace the logical place?

**Comment by wvuyk** [comment]
How come this became out of scope? It is missing functionality thet is needed for events?

**Comment by spudwebb** [comment]
> How come this became out of scope? It is missing functionality that is needed for events?
It just means the problem is not in the PluginSDK but in HS4 itself. I have created a bug in our internal bug tracker for this issue.

**Comment by jldubz** [comment]
A "status only" control (as used in HS3) can be defined using a `StatusGraphic`.

You can set the prefix, suffix, decimal places, and offset through the [StatusGraphic.TargetRange](https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/StatusGraphic.cs#L117) property.  This is a [ValueRange](https://github.com/HomeSeer/Plugin-SDK/blob/master/Devices/ValueRange.cs) type.  If the `StatusGraphic` only targets a single value, set the `Label` to the desired status as a static state instead of relying on a prefix, suffix, etc to dynamically generate the status.

For example, in the Z-Wave plugin a motion sensor uses the following `StatusGraphic` for a static state:
```
statusGraphic = New StatusGraphic("/images/HomeSeer/status/nomotion.png", 0, "No Motion")
```

And a battery feature uses the following `StatusGraphic` for a range of values:
```
statusGraphic = New StatusGraphic("/images/HomeSeer/status/battery_50.png", 37, 64)
statusGraphic.TargetRange.Suffix = "%"
```

**Comment by wvuyk** [comment]
Jon,

I tested this and indeed, I must have overlooked the `StatusGraphic.TargetRange` at first glances of using this class. Or was this the result of solving the bug you mentioned earlier?

I now also can find it back in the events creation (although there are some real challenges creating an event - other issue I guess). 

Guess this issue can be closed?

**Comment by jldubz** [comment]
Noting for internal use that some of this content should be moved over to the core documentation to help other users.
