### ISSUE TITLE
UnregisterDeviceIncPage NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#92]
**Environment and System Config**
- OS: [Windows, Linux, Mac, etc]
- Language: [VB]
- IDE: [VS2019]
- HomeSeer Version: [v4.0.5.0]
- PluginSDK Version: [v1.1.0.0]

**Describe the issue you are encountering**
When calling UnregisterDeviceIncPage I get NotImplementedException: The method or operation is not implemented and this needs to be used as this is not removed from the Add a new device list when the plugin is shutdown 

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. use RegisterDeviceIncPage in a plugin to register a link in the device Add a new device list
2. there is now no way to remove the link and it takes the user to the page even if the plugin is not running

**Expected behaviour**
The link should be removed by HS when the plugin is shut down like the other likes are or we need to use UnRegisterDeviceIncPage

-----

**Screenshots**

**Logs**

**Additional info**

**Comment by Enigmatheatre** [comment]
To Add to this if you enable the sample plugin it registers the link and then if you disable it there is still a link in the Add a device list.

**Comment by rjhdakota** [comment]
Logged has issue HS-750

**Comment by Enigmatheatre** [comment]
Rich,
Any update on this and other bugs in the SDK?

**Comment by rjhdakota** [comment]
Sorry, this was fixed in build 4.0.6.0. I missed the link from our system to Github.
