### ISSUE TITLE
HsFeature.HasControlForValue Method always returns false

### ISSUE THREAD

**Issue by Enigmatheatre** [HomeSeer/Plugin-SDK#93]
**Environment and System Config**
- OS: [Windows]
- Language: [VB]
- IDE: [VS2019]
- HomeSeer Version: [v4.0.5.00]
- PluginSDK Version: [v1.1.0.0]

**Describe the issue**
HsFeature.HasControlForValue Method always returns false.

**Steps to Reproduce**
Steps to reproduce the behaviour:
  Dim Feat As HomeSeer.PluginSdk.Devices.HsFeature
  Feat = hs4.GetFeatureByRef(331)
 Console.WriteLine("Feat.HasControlForValue(1) = " & Feat.HasControlForValue(1))

Returns:
Feat.HasControlForValue(1) = false

See screenshot of the device 331below

**Expected behaviour**
I would expect it to return true because there is a Status/Control 

-----

**Screenshots**
![image](https://user-images.githubusercontent.com/7591183/80629274-8ada5980-8a4a-11ea-82cb-3a993fb6c7df.png)

**Comment by spudwebb** [comment]
I have reproduced this bug, and I have proposed a fix in the SDK. It should be included in the next release.

**Comment by Enigmatheatre** [comment]
Spud, 
Any update on this as it is causing a part of my HS4 plugin not to function the way it did in HS3 unless you have another way to do this?

**Comment by spudwebb** [comment]
The fix is planed to be included in PluginSdk version 1.2.0.0, but I don; t know when it will be released.

**Comment by spudwebb** [comment]
version 1.2.0.0. is now released and includes the fix. I think this issue can be closed.

**Comment by Enigmatheatre** [comment]
I can confirm this is now functioning for me.
