### ISSUE TITLE
Action Config - InputView contents lost when selection list value changed

### ISSUE THREAD

**Issue by sjhill01** [HomeSeer/Plugin-SDK#94]
**Environment and System Config**
- OS: Windows
- Language: VB
- IDE: VS2017
- HomeSeer Version: v4.0.5.0
- PluginSDK Version: v1.1.0.0

**Describe the issue**
A clear and concise description of what the issue is to the best of your ability.

**Steps to Reproduce**
1. Create an AbstractActionType with a SelectListView and an InputView
2. Create a new Event in HS4 using that action.
3. Enter text in the input field.
4. Pick a value from the SelectListView.
5. Observe the input field is now blank.

**Expected behavior**
Data that has been entered should not be lost when changing a dropdown list selection inside an action ConfigPage.

**Comment by sjhill01** [comment]
Ok, I took the debugging of your event.html JS code as far as I could. Here's what's happening:

1. Text input changed
2. **viewValueChanged** called (via "change" listener on .jui-input)
   a. Input type falls into "else" condition
   b. A **viewChange** object is created that reflects the new value
   c. The **changes** Map has the **viewChange** added to it
   d. function returns - no further action taken.
3. Select input changed
4. **viewValueChanged** called (via "change" listener on .jui-input)
   a. Type = 'select-one', so falls into "else" condition
   b. A **viewChange** object is created that reflects the new value
   c. **SendPostback** is called (using an encrypted version of the **viewChange** object plus some other stuff)
5. **Somewhere in HS4** it handles the postback to the events.html page internally
   a. Based on the "other stuff" added to the data, **Somewhere in HS4** calls **OnEditAction** on the correct action of the correct plugin
   b. **OnEditAction** iterates through all of the items in the **viewChange** array and updates the corresponding **ConfigPage** views.
   c. **Somewhere in HS4** an empty response string is returned to **SendPostback**
6. The **success** callback in **SendPostback** executes
   a. Because the response from **Somewhere in HS4** is an empty string, the current "events.html" page is reloaded.
   b. Because the page is reloaded, the **changes** Map is lost and the input field reverts to empty.

_From what I can tell, here's the fix that's needed:_
In step 4c, the new viewChange should be added to the changes Map, and the changes Map should be used instead, which would send all as-yet-unprocessed changes to the plugin so that OnEditAction can rebuild all affected views in the ConfigPage.

**Comment by sjhill01** [comment]
And the **Somewhere in HS4** that's handling the event postback will need to change to handle arrays.

**Comment by sjhill01** [comment]
Any feedback on this?

**Comment by stefxx** [comment]
Having the same issue; very annoying that input gets lots if any other action is executed within same action before save.

**Comment by stefxx** [comment]
I continue to have issues creating logical event triggers/actions because of this. We really need a postback on a inputView change.

**Comment by spudwebb** [comment]
I see the problem. It's now tracked as HS-1486, and a fix is worked on.

**Comment by stefxx** [comment]
Yes! Thank you!

**Comment by spudwebb** [comment]
This is fixed in HS 4.2.7.0. Please test and reopen if you still have a problem.

**Comment by stefxx** [comment]
Excellent! Tested successfully!
