### ISSUE TITLE
ConvertLegacyData keeps being called, results are neve saved...

### ISSUE THREAD

**Issue by wvuyk** [HomeSeer/Plugin-SDK#96]
It took me a while to discover that for some  reason the methods to convert an action or trigger had been changed. I missed the updates on that.
I changed the plugin to use the ConvertLegacyData method, to discover that even until now the converted data is not saved. 
Documentation - as far I understand - is saying one has to fill the ConfigPage object with the correct views and, once conversion is ready, return the Data object. 
I would expect at this point the action is converted and can be stored? But instead the conversion is called multiple times per second. Even editing the action and pressing the save button won't help?

How can an event action (also for triggers) be converted and be done from then on?

Please advise

**Comment by spudwebb** [comment]
you're right, since SDK version 1.1.0, you have to override ConvertLegacyData instead of ProcessData. I have updated the documentation about that: https://docs.homeseer.com/display/HSPI/Reading+Legacy+Event+Data

I implemented this for the Chromecast and Ecobee action plugins and if I remember correctly, the data is not saved to the new format until you actually change something in the action and save. So yes that could be more optimized, but does it cause any other issues?

**Comment by wvuyk** [comment]
Spud,

thanks for your quick answer. 
Even after saving an action during event editing the conversion is being called. It does not stop then. If it did, I would not have mentioned this in my first post? 

> Even editing the action and pressing the save button won't help?

And this can be more optimized for sure as if the event is evaluated or edited, the conversion is taking place multiple times. 

Check this log (1 second!!!) of my plugin during edit...... Call me old fashioned, but this is a candidate for CPU cycle saving.

> 22:01:04.4375693 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:04.6280890 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:04.8175536 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:04.9881260 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:14.4413583 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:14.6258397 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:14.8047121 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:14.9822134 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:24.5060898 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:24.6896264 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:24.8691189 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:25.0440486 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted
> 22:01:34.4668473 -- (JowiHueActions.ConvertLegacyData) event action Slaapkamer Lampen uit converted

**Comment by spudwebb** [comment]
> Even after saving an action during event editing the conversion is being called
but did you try to actually change something in the action event and then save? I think I remember that editing and saving would not save to the new format, but editing, changing a value, and saving would.

**Comment by wvuyk** [comment]
Probably not, as all I wanted was to get rid of the conversion call. Will test that later, when I am testing on HS4 again. But I would not want to advise that to users of the plugin.......

**Comment by wvuyk** [comment]
@spudwebb @jldubz 

I just tested with the action conversion, by actually changing the action in the interface. 
Indeed then - finally - the conversion is no longer called anymore. To give you an idea of the response loss for conversion, the response for an event that is holding three plugin action steps is taking more then 3 seconds before it is opened. In those three seconds the conversion is called 15 times, 5 times per action.
Once the three actions are changed and saved, opening the event takes between 1 and 2 seconds, even after a fresh start of HS4. 
So optimization is highly recommended on this part. Preventing the loop in conversion is very important in my eyes. Maybe present a possibility to the ConvertLegacyData process to actually decide the data is complete without errors and to be saved immediately? This will improve user experiences.

Wim

**Comment by jldubz** [comment]
@wvuyk 

Thank you for the recommendations. Would you be able to share code that demonstrates this loop? We can work on optimizing it from there.

**Comment by wvuyk** [comment]
Sorry, no more. After two years I have worked around this issue and cannot recreate it

**Comment by jldubz** [comment]
PS we are actively investigating optimizing the event page
