### ISSUE TITLE
HS4 does not generate HSEVENT callbacks to HS3 plugin

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#97]
HS4 4.0.6.0, Windows

HSEvent callback registered as:
callback.RegisterEventCB(HomeSeerAPI.Enums.HSEvent.VALUE_CHANGE, IFACE_NAME, "")
Breakpoint set at start of:
Public Sub HSEvent(ByVal EventType As Enums.HSEvent, ByVal parms() As Object) Implements HomeSeerAPI.IPlugInAPI.HSEvent
Virtual device created with On/Off button for controlled testing.  Toggle the device on/off.  No callback to HSEvent generated.

Doing the same test with HS4 version of the same plugin does generate the callbacks.  Earlier versions of HS4 did produce the callback with HS3 pluign.  I do not know at what version the breakage occurred.

**Comment by rjhdakota** [comment]
Do you know if it's just this event type or any event type? Can you disable any other plugin that you have enabled just to make sure its not related to another plugin? I am not aware of any changes to the event handling. We did add a new event type, but that was outside of normal event handling.

**Comment by mcsSolutions** [comment]
I did a reboot of my system to support additional testing requested.  Following reboot the callbacks are being received.  During the original testing only one plug-in (mcsMQTT) was enabled via remote access through Visual Studio.  I believe the issue can be closed.

**Comment by rjhdakota** [comment]
Ok, closing for now, you can re-open if you see this again.
