### ISSUE TITLE
HS 4.0.8.0 - setup page problem

### ISSUE THREAD

**Issue by poki123** [HomeSeer/Plugin-SDK#99]
**Environment and System Config**
- OS: Linux
- Language: -
- IDE: -
- HomeSeer Version: 4.0.8.0
- PluginSDK Version: -

**Describe the issue**
Clean install of HS 4.0.8.0, license registration ok. Im unable to open the "setup" page, i see only grayed page with circle. others pages seems to be ok

**Steps to Reproduce**
1. Go to 'setup page'
**Screenshots**
![homeseer](https://user-images.githubusercontent.com/25682032/84762309-eea0ed80-afca-11ea-866d-701436f3e1b6.png)

**Logs**
If applicable, include log output from the plugin console and/or the HomeSeer logs.
[homeseer_logs.txt](https://github.com/HomeSeer/Plugin-SDK/files/4785951/homeseer_logs.txt)[HomeSeerLog.txt](https://github.com/HomeSeer/Plugin-SDK/files/4786018/HomeSeerLog.txt)

**Additional info**
Add any other information about the problem here.

**Comment by rjhdakota** [comment]
Hello, reports here are for issues with the plugin SDK. Can I ask you to report this issue on our service desk where general HS4 issues are to be reported. Thanks!

https://dev.homeseer.com/servicedesk/customer/user/login?destination=portals
